/* 
Program name: 	cclosure_g.cpp 
Author: 		Francois A. Gougeon
Date:			June 2025 (1st version May 1995)
Version:		3.2


Description:

C	From a bitmap showing individual (distinct) tree crowns
C	such as the one generated by program ITCISOL (or from other
c	bitmaps such as canopy from a simple threshold on NIR or NDVI)
C	this program generates a raster image where each pixel value
C	is relative to percentage canopy closure in a given neighbourhood.
C
C1	PARAMETERS
C
C	CCLOSURE is controlled by the following global parameters:
C
C	Name		Prompt						Count	Type
C
C	FILE		Database File Name				64	Char
C	DBIB		Bitmap of tree crowns (or other BM)		1	Int	
C	DBOC		Output Channel (canopy closure image)		1	Int
c	NFMASK		Non-forested Area Input Bitmap (a mask)		1	Int
C	REPORT		Reporting device				64	Char
C
C

C
C2	DBIB
C
C	Specifies a bitmap, often produced by the ITCISOL (Individual Tree  
C	Crown Isolation) program, to be used as reference in evaluating 
C	crown closure.

c
c2	NFMASK
c
c	Specifies an optional input bitmap (non forested mask)
c	to be used as mask eliminating certain areas from processing.
c	For exemple: to eliminate roads, pastures, open areas, ...

  
  
PROGRAM USAGE:

Run as (for examples):

>  cclosure_g  input_BM_file output_Ima_file NFMASK	

>  cclosure_g PRF_ISOL.tif PRF_CCLOSURE.tif PRF_NonFor.tif



Ackowlegment to GDAL:

GDAL - Geospatial Data Abstraction Library: Version 2.1.1 (July2016, 64bit), 
GDAL - Geospatial Data Abstraction Library: Version 3.0.0 (Dec. 2019, 64bit),
Open Source Geospatial Foundation, 
Thanks Frank (Warmerdam)

  
C
C1	REVISION HISTORY
C	
C	By François A. Gougeon 
C	(©)Natural Resources Canada
C	Canadian Forest Service
C	
C v1.0  May 1995	François Gougeon
c
c			- As STEMDENS.c	(ANSI C Version, PCI V5.3)
C				(some parts of code come from TREE_POS2.c)
c
c v1.1	Nov 1996	François Gougeon
c		
c			- Minor cleanup mods
c
c v1.2	Dec 1997	François Gougeon
c		
c			- Minor cleanups.
C
c V1.3  Feb. 2001	François Gougeon
c
c			- Minor modifications, debugging and improvements.
c
c V1.4  Feb. 2001	François Gougeon
c
c			- Changing IDBSegIO() to IDBBitmapIO() on bitmap input
c			  solved crashing on image output at end of program.
c		 	- Important,  DONT USE IDBSegIO() for bitmaps -- UNSTABLE 
c			  use IDBBitmapIO(), but not yet GDBBitmapIO()
c
c V1.5  Sept. 2001	Geoff Savinkoff
C
c			- Updated to use itc_io library to read a bitmap
C			- Updated to use operations from bitops library
C			- Updated help file with linking information and EASI prompts
c			- Added local variables (xsize,ysize,channels) for passing to functions
c			- Added a general channel description using IDBChanDescIO
c
c V1.5a	Oct. 2001	Geoff Savinkoff
c
c			- Replaced most IDB functions with GDB functions (not IDBPixelSize as 
c			  there are is no equivelant GDB function)
c			- Added GDBGeorefIO function for georeferencing information
c
c V1.6  May 2002	François Gougeon
c
c			- Fixing minor bug ("<=" rather than "<") making the process "fall off" the 
c			  image and crash at 99% completion (for some images).
c			- Cclosure now calculated using a 50x50 window (which corresponds to
c			  a quarter of an hectare at 1m/pixel) to be compatible with
c			  stemdens, thus no artifacts when used together to generate
c			  ITC stands (no double lines). 
c
c V1.7  April 2004	François Gougeon
c
c			- Canopy closure reported in percentage (0-100)
c			- Should run a bit faster.
c
c
c v1.8	Jan-Feb 2008	François Gougeon
c
c			- Minor "link" adaptations for PCI v10.n (N.B.: New incompatible PRM.PRM file)
c			and use of of VS8 compiler wanting to produce more secure code.
c			Most PCI routines are in PCI1000.dll, but not all. For examples,
c			IMPTime() and IMPReturn() are now in Core1000.dll
c			and IMPCounter() in Counter1000.dll
c			Also, since I dont have PCISDK or PCI/ProSDK, I've had to create LIBs 
c			from these DLLs to compile my progs (same for PCI 10.1)
c
c			- Also, problems with the REPORT (*Report) Variable in Core1000.dll
c			First use of report makes program crash (i.e., after the start message)
c			So, declare global var :	 FILE *Report;
c			and do immediately after the call to IMPSTATUS() :		
c			if(EQUALN(report,"TERM",4)) {Report=stdout;}else{Report = fopen(report, "w");}
c
c
c v2.0	June 2008	François Gougeon
c
c			- Introduced optional non-forest mask (NFMASK) so that crown closure can drop
c			abruptly to zero when hitting a non-forested area (e.g., specially a lake)
c			as opposed to, in previous versions, slowly going to zero from whatever the 
c			closure of the closest forest was. In addition to masking the non-forested
c			areas and making sure their crown closure is set to zero, the program also
c			makes sure that there is no decrease in crown closure in the neighbourhood
c			of such non-forested area (Note: This could create artefacts if your non-forest
c			mask is not precise, as it extrapolated the current forest closure up to the
c			border of the non-forest mask area).
c
c			Previously, not dealing directly with non-forested areas often created artifacts 
c			when the programs STEMDENS and CCLOSURE were used to generate forest stands, 
c			as segments (stands) of middle densities were often created between forested areas 
c			and lakes, creating an additional polygon, or a poorly positioned polygon around
c			lakes and other non-forested areas.
c
c			If needed, the past behavior (pre v2) of STEMDENS is available by not specifying
c			a non-forest mask (i.e., NFMASK= )
c
c
c v3.0	March 2016	François Gougeon
c
c			- Changed to a C++ program to deal with versions of PCI > v10.2
c				int main (), ".cpp" name, and extern "C" around .h include files
c			- Mods to some calls to fit new library definitions (as per .def and demangling)
c			  which also means mods to corresponding declaration .h files (e.g., gdb.h)
c			  (Since I dont have PCISDK or PCI/ProSDK, I have to create LIB and DEF from
c			  from their DLLs (via DUMPBIN and LIB) in order to compile my progs
c			- Modules in files like gdb.h need to be declared 'extern "C++" to link
c			  with proper name mangling (MSVC++ mangling)
c			- ***WORKED**  for PCI 10.3 that migrate its LIB to c++, 
c
c			- HOWEVER, more stuff is needed for PCI 2015 (64bit)
c			- PCI LIB need to be declared /MACHINE:x64 
c			  and prog compile with 64b version (i.e., vcvarsall amd64)
c			  cause all the call to lib are now with 64bit pointers 
c			- IMPStatus()  uses "char const *", so mod. that in ccltask.h (no mod in prog.)
c
c v3.1	Sept 2016	 François Gougeon	
c
c			- "bmsize" needs to be (int64) everywhere to deal with bitmaps > 2GB
c			- Also, loop counters (iii) relative to copying bitmap (i.e., bmsize)
c			- (int64) bitnum and its equations and others:  offsetbit
c			- Replaced GDBBitmapIO() by write_bmp() from itc_io.cpp for bitmaps > 2GB
c			- Replaced GDBByteIO() by write_ima8b() from itc_io.cpp to output
c			   full images > 2GB
c			- To use GDBByteIO() for section work, sections need to be < 2GB
c
c v3.2	June 2025	 François Gougeon	
c
c			- Migration to GDAL v3.10, v3.11
c



*********************
Ackowlegment to GDAL:

GDAL - Geospatial Data Abstraction Library: Version 2.1.1 (July2016, 64bit), 
GDAL - Geospatial Data Abstraction Library: Version 3.0.0 (Dec. 2019, 64bit),
Open Source Geospatial Foundation, 
Thanks Frank (Warmerdam)


*********************************


*/

#define RELEASE_MODE 1		// use to skip big sections
//#define DEBUG_ME 1		// if defined, prog. will show more info for debugging

#define FILENAME    132
#define VERSION "v3.2"
#define PROG_NAME "CCLOSURE"

#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <time.h>       // time_t, struct tm, time, localtime 
#include <math.h>

#include "gdal_priv.h"		// For GDAL library
#include "ogrsf_frmts.h"	// For OGR

#include "ITC-Suite_g.h"		// my newest GDAL variable setup
#include "itc_io_g.h"		// my newest GDAL image/bitmap input/output
#include "bitops.h"		// bit operations on bitmaps (mostly macros to be faster)

#include "hist_g.h"

	
// GLOBAL DECLARATIONS - Tons are needed to use with "itc_io_g.cpp"

int		Pixels, Lines, Channels;	// pixel and line starting at 1,1
int		xsize, ysize;			// pixel and line starting at 0,0
int 	data_type;

int64 	bmsize;		// size of bitmap in bytes 

int		bylines_flag = 0;		// by default proceed by full images (not by lines)

float		xpixsz, ypixsz;
char 		*Proj, *Proj2, *Datum, *Datum2, *Temp,*token;

double 		topleftX, transformX, topleftY, transformY; 	 /* for geographic mapping */

int 		ch_in, ch_out, in_ch[10], segm_in, in_segm[], segm_out;

GDALDataset	*ima_in, *ima_in2, *ima_out;
GDALDriver 	*piDriver, *poDriver;
GDALRasterBand	*piBand, *poBand;
GDALDataset	 *seg_in, *seg_out;
double		adfGeoTransform[6], adfGeoTransform2[6];
char 		**papszMetadata;
char	 **papszOptions;
int imaFile_opened;

char 	Description[80];
char 	Extension[10]; 		// global variable for other prog.
int	xcg, ycg;	



/* function declarations */

/* NONE */

/* global vars list */

unsigned char *Temp_ima;

time_t rawtime;
struct tm * timeinfo;


/***** main prog. ******/

int main(int argc, char *argv[])
{

/* local vars list */


char		filename[FILENAME], fullfilename[FILENAME], shortfilename[FILENAME];
char		basefname[FILENAME], mainfname[FILENAME], directory[FILENAME];
char		file_out[FILENAME], extension[10];
char 		*pch, *pch1, *pch2;

int 	i, j, ii, jj;
int 	istart,istop,jstart,jstop;

int64	bitnum, bitnum2, imasize,bmsize;
int 	imgarea, blocks;

int 	wsiz,sum, sum2;
PixVal 	*isolbitbuffer, *nfmaskbuf;
char 	seg_history[81], pix_units[9], timedate[17], chn_desc[81], geosys[17];
float 	pix_xsize, pix_ysize;
double	topleftX,transformX,topleftY,transformY;

char 	ans[80];

/* 
// PCI assign parameter pointers to argumnets 

args[0] = (void *) file;
args[1] = (void *) &dbib;
args[2] = (void *) &dboc;
args[3] = (void *) &nfmask;
args[4] = (void *) report;

// PCI setup standard interface 

IMPStatus ( "FILE,DBIB,DBOC,NFMASK,REPORT;",
            "C   ,I   ,I   ,I     ,C     ;", 
            "132 ,1   ,1   ,1     ,132   ;",
            "1   ,1   ,1   ,0     ,0     ;",
            "CCLOSURE.","FORCE", argcnt, args, argc, argv );

// To compensate for "faulty" Report variable from core1000.dll 

if(EQUALN(report,"TERM",4)) {Report=stdout;}else{Report = fopen(report, "w");} 

*/


//*************************************************

/* Print Program Header and time */

	time (&rawtime);
	timeinfo = localtime (&rawtime);

	fprintf(stdout,"\n\n\t\tStarting %s (%s) at %s\n", PROG_NAME, VERSION, asctime(timeinfo));

// Check input parameters (i.e., agrv[*])

	if (argv[1]== NULL) 
	  {printf("\n\n PROBLEM with input image %s \n",argv[1]);
	  printf("\tHave an INPUT image as first argument on command line \n");
	  printf("USAGE:  cclosure_g  input_BM_file output_Ima_file NFMASK	\n\n");
	  exit(1);
	  } 

	if (argv[2] == NULL) 
	  {printf("\n\n PROBLEM with output image %s \n",argv[2]);
	  printf("\tHave an OUTPUT image as second argument on command line \n\n");
	  printf("USAGE: cclosure_g  input_BM_file output_Ima_file NFMASK	\n\n");
	  exit(1);
	  } 

	if (argv[3] == NULL) 
	  {
	  printf("\n\t ### ERROR ### a third argument is needed \n");
	  printf("\nThat third argument is a non-forest mask  \n");
	  printf("USAGE: cclosure_g  input_BM_file output_Ima_file NFMASK	 \n\n");
	  exit(1);
	  }

	 // exit(-1);			// for debugging
	  
//#ifndef RELEASE_MODE
	 
//************************

// 		Opening INPUT  image file (BITMAP)

	printf("\n\t\t*Opening input bitmap file to use ...\n");	

 
	GDALAllRegister();  
	

	//ima_in = (GDALDataset *) GDALOpen( argv[1], GA_ReadOnly );	// GDAL direct

	ima_in = open_imaFile(argv[1]);		// using  "itc_io_g" does a lot of the setups

	if (ima_in == NULL) 
	  	{printf("\n\n PROBLEM opening input image file %s \n\n", argv[1]); exit(1);}

	
// Create SHORT file name (no dir) for display convenience and later, for output file description

	strcpy(shortfilename, argv[1]);

	pch = strtok(shortfilename,"/");
	while(pch != NULL)
	  {
		//printf ("pch : %s\n",pch);
		strcpy(shortfilename, pch);
		pch = strtok(NULL, "/");
	  }		
	printf("Shortfilename:  %s \n", shortfilename);

	

// setup size information for bitmaps and images 

	imasize =  Lines * (int64) Pixels;	// assumes 8-bit image 
	bmsize = (imasize + 7) / 8;
	blocks = (bmsize + 511) / 512;


// Reading ITC bitmap (or plain threholded (NDVI) vegetation bitmap)

	printf("\n\t *** Reading ITC bitmap <<%s>> \n", argv[1]);
	
	strcpy(fullfilename, argv[1]);
	isolbitbuffer = read_bitmap(fullfilename, 1);		// always 1 for tif file bitmap, different for PCI files 
	safety_zone(isolbitbuffer);
 

// Reading NFMASK bitmap 

//if (argcnt[3] == 0) nfmaskbuf = alloc_read_bmp(idb_fp, Pixels, ysize, 0);

if (argv[3] == 0) 	
	for (i = 1; i <= bmsize; i++)	nfmaskbuf[i] = 0;	
else
  {
  printf("\n\t *** Reading non-forest mask bitmap <<%s>> \n", argv[3]);
  
  	nfmaskbuf = read_bitmap(argv[3], 1);		// always 1 for tif file bitmap, different for PCI files 
	safety_zone(nfmaskbuf); 
  }  

// Allocate memory for output image buffer

printf("\n\t *** Allocating memory for output image\n");

Temp_ima = (unsigned char *) malloc(imasize);
check_mem(Temp_ima);



//		exit(-1);			// for debugging


/**********************************************************************/

/* scan the bitmap of tree crown to accumulate canopy closure data*/

/**********************************************************************/

printf("\n\t *** Accumulating canopy closure data\n\n\n");

wsiz = 25; 	/* size of evaluation window (2*wsiz) square = 50x50 */

  for ( i = 5 ; i < (Lines-5) ; i+=10 ) 	/* go by 10 to speed up the process */
  for ( j = 5 ; j < (Pixels-5) ; j+=10 ) 
    {
	bitnum = i * (int64)Pixels + j ;

/* simple scheme for border situations */
istart = i - wsiz;        /* normally, when away from borders */
istop =  i + wsiz;
jstart = j - wsiz;
jstop =  j + wsiz;

if ((i-wsiz)< 0) { istart = 0;  istop = 2*wsiz; }
if ((i+wsiz)>Lines) { istart = Lines-2*wsiz;  istop = Lines; }
if ((j-wsiz)< 0) { jstart = 0;  jstop = 2*wsiz; }
if ((j+wsiz)>Pixels) { jstart = Pixels-2*wsiz;  jstop = Pixels; }

/* sum crown material over a 50x50 area of the image (bitmap) */

    sum = 0; sum2 = 0 ;
    for ( ii = istart ; ii < istop ; ii++ )
    for ( jj = jstart ; jj < jstop ; jj++ ) 
        {
        bitnum2 = ii * (int64)Pixels + jj ;
        if (  testbit(isolbitbuffer, bitnum2) ) sum = sum + 1;
		if ( testbit(nfmaskbuf, bitnum2) ) sum2 = sum2 + 1;
        }
        
 /* for normalization to 100% */       
    
    sum = (int) ( 100. * (float)sum / (float)(4*wsiz*wsiz) );  

 
/* Paint a 10x10 area with same closure around pixel of interest */

  for ( ii = i-5 ; ii < i+5 ; ii++ )
  for ( jj = j-5 ; jj < j+5 ; jj++ ) 
	{
	/* Relative crown closure (in general) */
	
	if(sum2 == 0) *(Temp_ima + ii*(int64)Pixels + jj) = sum; 

	/* Relative crown closure re-adjusted for missing area due to non-forest */

	if( sum2 < 2000)
	  *(Temp_ima + ii*(int64)Pixels + jj) = sum * 2500 / (2500-sum2);
	else	/* if more than 80% is non-forested area, dont bother */
	  *(Temp_ima + ii*(int64)Pixels + jj) = 0;
	}

 
  /* Fast or slow display of progress depending on number of lines  */

	if (Lines < 5000)
		{ if( (j==5) && ((i-5)==((i-5)/100)*100) ) printf("%2.0f percent done\r", (float)i/Lines*100); }
	  else
		{ if( (j==5) && ((i-5)==((i-5)/500)*500) ) printf("%2.0f percent done\r", (float)i/Lines*100); }
	  
  }	/* end of 2nd main bitmap scanning loop */
  


/* For pixels that are purely non-forest, make crown closure zero */

  for ( i = 5 ; i < (Lines-5) ; i++ )	
  for ( j = 5 ; j < (Pixels-5) ; j++ ) 
    {
	bitnum = i * (int64)Pixels + j ;
	if (testbit(nfmaskbuf, bitnum))  *(Temp_ima + i*(int64)Pixels + j) = 0;
	}


	printf("\n\t ***  Analysis Done ***\n");


//	exit(-1);			// for debugging

//#ifndef RELEASE_MODE


/*******************************************************************************/

/* Output the canopy closure image */

/*******************************************************************************/


	printf("\n\n* Outputing canopy closure image to file : %s \n", argv[2]);

	sprintf(Description,"Canopy Closure Image from bitmap %s \0", shortfilename);
	
	write_image(Temp_ima, argv[2]);



// Close input and output images

	printf("\n\t*Closing all files and exiting program. \n");

//	GDALClose(ima_in);
//	GDALClose(ima_out);


	time (&rawtime);
	timeinfo = localtime (&rawtime);
	fprintf(stdout,"\n\n_______________________________\n");
	fprintf(stdout,"\n %s (%s) finished at %s\n\n", PROG_NAME, VERSION,  asctime(timeinfo));

	
// For people using this program via ArcGIS, give then some time to examine the results (before disappearing)

	if  (EQUALN("ArcGIS ",argv[argc-1],3) )
	{
	fprintf(stdout,"\n\n######\n");
	printf("\n Type anything to make this detailed window disappear and terminate %s ",PROG_NAME);
	ans[0] = getc(stdin); 		// gets any answer or <CR>
    }
	
//#endif
	
	exit(0);				// exit properly 

} 			// END OF MAIN PROGRAM 

