/* 
C+
C	CWD_SFIL_g.cpp	(Coarse Woody Debris Size Filter (with GDAL))
c	
c	A mod of ITCSFIL to pickup logs in a field (i.e., cut area) 
c	littered by coarse woody debris and stumps.
C
C	From a bitmap showing logs and other coarse woody debris (CWDBM)
c	(typically from using a threshold on a normalized blue band)
C	this program generates a bitmap containing only the logs
C	within a certain range of diameters (using lower and upper 
C	thresholds (in cm)), and/or a certain range of lengths 
c	(using lower and upper thresholds in metres).
c
c	The original bitmap is often obtained by simple thresholds of
c	possibly a normalized blue image (or NVEGMASK, NDVI_FG)
c
c	NOTE:  Length should be LONGER THAN FIVE(5) width to be considered a log or a branch 
c
C


*******************************************************************************

*** Run as:

>  CWD_SFIL_g  Name_CWD.tif Name_LOGs.tif Test_Areas.shp  10,100 1,100


Name_CWD.tif 	Input CWD bitmap
Name_LOGs.tif 	Output LOG bitmap
Test_Areas.shp  Test areas for which to report (or Test_Areas.tif - a bitmap)

DIAM_THR	Min & Max diameter (in cm) to include (Int)	10,100
LENG_THR	Min & Max length (in metres) to include	(Real)	1,100



*******************************************************************************

C Historical PCI Parameters

C1	PARAMETERS
C
C
C	LOGSFIL is controlled by the following global parameters:
C
C	Name		Prompt						Count	Type
C
C	FILE		Database File Name				64	Char
C	CWDBM		Bitmap of logs, CWD and stumps			1	Int	
C	LOGBM		Bitmap of logs of certain sizes			1	Int
C 	TESTSEG		Test Area Segments (BM/Vect)			16	Int
C	DIAM_THR	Min & Max diameter (in cm) to include		1-2	Int
C	LENG_THR	Min & Max length (in metres) to include		1-2	Real
C	REPORT		Reporting device				64	Char
C
C
C2	FILE
C
C	Specifies the name of the PCIDSK file containing the input and output
C	channels (images) or bitmaps (themes).
C
C	EASI>FILE="filename"
C
C2	CWDBM 
C
C	Specifies an input bitmap showing logs, stumps and coarse wooody debris
c	often generated by using simple thresholds on the input image
C
C	EASI>CWDBM=n
C
C2	LOGBM
C
C	Specifies an OUTPUT bitmap to contain only the logs (or debris)
C	of a certain lenghts and sizes as found in CWDBM 
C	If not specified, a new bitmap is created.
C
C	EASI>LOGBM=n
c
C2	TESTSEG
C
C	Specifies a list of testing areas (bitmaps or vector layers) to be used.
C	The bitmaps contain filled areas. The vector segments contain polygons.
c	They were typically delineated by the user on the screen and
c	often correspond to plot areas or stands. In polygon format,
c	such test areas could also have been imported from an existing
c	forest inventory from an GIS.  In vector layers, polygons that have parts
c	outside the image area will be disregarded
c
c
c	EASI>TESTSEG=n,n,n...
C
C2	DIAM_THR	
C
C	Range of log diameters (in cm) to keep in output bitmap  
C
C	EASI>DIAM_THR=n,m    | keeps logs with diameters between n and m cm
C	EASI>DIAM_THR=n      | keeps logs with diameters above between n cm
C
C2	LENG_THR
C
C	Range of log length (in meters) to keep in output bitmap.  
C
C	EASI>LEN_THR=n,m    | keeps logs with length between n and m meters
C	EASI>LEN_THR=n      | keeps logs with length above n meters
C
C
c
c
C2	REPORT
C
C	Specifies the file to append generated report to:
C
C	EASI> REPORT = "filename"
C
C	Note:  The following names have special meaning:
C
C	EASI> REPORT = "TERM"	| generates reports on your terminal
C	EASI> REPORT = "DISK"	| generates reports on file "IMPRPT.LST"
C	EASI> REPORT = "OFF"	| (may) switch off report generation
C

c1	HISTORY
c
c
C	François A. Gougeon (c)
C	Natural Resources Canada
c	Canadian Forest Service
c	Pacific Forestry Centre
C	Victoria, BC, Canada
C	
c
C	Revision History:
c
c
c v1.0	March 2012 	François Gougeon
c
c	- Modified from ITCSFIL.c to deal with logs and debris in a bitmap
c	rather than crowns (i.e.,ITCs).
c
c
c v1.1	April 2012	François Gougeon
c
c	- Minor improvement (e.g., history, etc.)
c
c v1.2 	Oct. 2014	François Gougeon

c	- Better separation of area criteria (dropped for the moment) from length criteria
c	- Introduced width measurement (additionnal items in object structure, still called "crown")
c	- Introduced volume calculation for logs
c	- Introduced plain text files output
c
c v1.3	Oct. 2014	François Gougeon
c
c	- More systematic on log length and diameters
c
c v1.4	Oct. 2014	François Gougeon
c
c	- Introduced reporting on a test area (e.g., a plot) rather than full image
c
c v1.5	Dec. 2014	François Gougeon
c
c	- Introduced the faster vect2rast (from itcpcdb.c from Feb 2003)
c	- Better history (length and diameter ranges reported)
c
c v2.0	Oct.2016	François Gougeon
c
c		- Changed to a C++ program to deal with versions of PCI > v10.2
c			int main (), ".cpp" name, and extern "C" around .h include files
c		- Mod to some call to fit new library definitions (as per .def demangling)
c		  which also means mods to corresponding declaration in .h files (e.g., gdb.h)
c		  (Since I dont have PCISDK or PCI/ProSDK, I have to create LIB and DEF from
c		  from their DLLs (via DUMPBIN and LIB) in order to compile my progs
c		- Modules in files like gdb.h need to be declared 'extern "C++" to link
c		  with proper name mangling (MSVC++ name mangling)
c		- ***WORKED**  for PCI 10.3 that migrate its LIB modules to c++, 
c
c		- HOWEVER, more stuff is needed for PCI 2015 (64bit)
c		- PCI LIB need to be made /MACHINE:x64 
c		  and prog compile with 64b version (i.e., vcvarsall amd64)
c		  cause all the call to lib are now with 64bit pointers 
c		- IMPStatus()  uses "char const *", so mod. that in ccltask.h (no mod in prog.)
c
c		-Mod. length threshold from integer to real to accomodate for length of 0.5 metre,
c		 for log found in piles which could display only apparent segments of 0.5 metre
c
c
c v3.0	June-Sept 2017	François Gougeon
c
c		- Mod. to use GDAL library rather than PCI library (thus named "cwd_sfil_g")
c		- Nice simple test prog. for that transition to GDAL
c		- Also, very useful: no need to loan a PCI dongle to Tony's group
c		- Convenient to use of tif files (images and bitmap) cause we were converting
c		  back and forth to/from tif to do the skeletonization via Fuji.
c		- Nice test prog. cause it has images, bitmaps, and vector layers
c		- paint_plot() replaced by code in Vector section for GDAL access to polygons
c		- vect2rast() used pratically as is (only very minor mods), although it has been
c		  modified to erase area (set_flag=0) which was found a safer way to deal
c		  with multiple small island in main shape (i.e., burn-in outer polygon,
c		  burn-out inner polygon)
c
c
c v3.1	Feb. 2018	François Gougeon
c
c
c		- Fixes minor bug relative to cleaning residual junk in output bitmap (1-bit tif)
c		  Need to be more careful about images starting at zero in GDAL, while keeping 
c		 image sometimes at (1,1) for PCI environment compatibility (generally when X,Y used)
c
c
c v3.2	Oct 2021	François Gougeon
c
c		- Minor mod. (related to ITC-Suite under GDAL 3.0.2) 
c		  I changed SEG_VEC for segm_vec and SEG_BIT for segm_bit, because
c		  ITC-Suite_g.h (called by bitops.h) define SEG_VEC and SEG_BIT differently
c
c		- Fixed confusion between two versions (formally decided by programmer)
c		one version reporting (.txt) the details of each polygon content (i.e., by plot)
c   	one version running the whole shape in one shot, with a less interesting text report.
c		First version had a bug and was not producing full results in the output bitmap.
c		A "while do" could be stopped at two places depending on the programmer	(with recompiling)
c		Probabbly a "special version" created 5 years ago and not documented.
c		Fixed using a extra internal bitmap, one used for the intermediate output of each loop (outbitbuf),
c		and one used for the final output bitmap (outBM)
c
c		- Arange to skip test areas (polgons) outside the image area rather than report zero logs.
c
c		- Using BORDER and prep_bmp_zero() not to "get off" image memory space
c
c
c v3.3	Dec 2021	François Gougeon
c
c		- Dealing with output colors to be compatible to PCI, ArcGIS, etc.
c
c		- Better(cruder) checking of georeferencing compatibility between input files
c			In case files are from different apps.
c
c		- Used "crown_list_flag" to decide if creating a full internal list of crowns(logs)
c		  NOTE: Full crown list could blow up the program stack on a full analysis (no test area) 
c		  of a big image
c
c		- BORDER Issues: preprocessing often creates thick borders around full image (so now BORDER=6)
c 			NOTE: Such borders (when set to 1) can lead to infinite regression, crashing the program
c
c v3.4	Feb. 2022	François Gougeon
c
C		- Printout a few more things in "Logs_CWD_SFIL.txt" for easier tracing of logs and comparison
C			with "log_ivol_g.cpp" logs (and more precise UTM coordinates)
c
C		- Printout of overall volume for quick comparison with log_ivol_g.cpp" results
c
c
C
C	
c	Linking information
c
c #	For PCI 10.1  (with MinGW gcc)
c 
c	gcc  -I"C:\pcisdk_v101\lib" -I"C:\ITC-Sources"  -o logsfil itc_io.c error.c logsfil.c -L 
c	"C:\Program c	Files (x86)\PCI Geomatics\Geomatica_V101\exe" -lpcic1010  -lcore1010 -lcounter1010
c
c
c	For PCI 2015, PCI 2017
c
c	To Set up Visual Studio 2015 (v14) environment variables (for 64 bit versions)
c	and to compile for 64 bit program using 64bit pointers
c
c	call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall" amd64
c
c	set CL= /MD /W3 /O2 /D "WIN32" /D "NDEBUG" /D "_CONSOLE" /D "_MBCS" /Fo"%RELEASE_OBJDIR%\\" /FD
c	set CL=%CL% /D "_CRT_SECURE_NO_DEPRECATE" /D "_CRT_NONSTDC_NO_DEPRECATE" /wd4996 /wd4244 /wd4101
c
c	set LINK=pcic201500.lib core201500.lib counter201500.lib  /subsystem:console /incremental:no /machine:x64 /DEFAULTLIB:MSVCRT
c
c
*******************************************************************************

*** To compile with Visual Studio (VS14)  (see VS14_GDAL_compile.txt)

call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

set INCLUDE=C:\gdal-2.1.1_v2\include;C:\libtiff-4.0.6_64b\tiff-4.0.6\libtiff;%INCLUDE%
set LIB=C:\gdal-2.1.1_v2\lib;C:\libtiff-4.0.6_64b\tiff-4.0.6\libtiff;%LIB%

set LINK=gdal_i.lib  libtiff_i.lib User32.lib

set CL= /MD

CL xxxxxxxxx.cpp /EHsc


Ackowlegment to GDAL:

GDAL - Geospatial Data Abstraction Library: Version 2.1.1 (July2016, 64bit), 
Open Source Geospatial Foundation, 
Thanks Frank (Warmerdam)

********************************************************************************

REM	For Visual Studio 2019 v16.3.10 (x64) on W-VIC-A144879 (on Ciara)

	REM ##### Better to do that  **VERY FIRST THING** (1st thing in cmd window)
	REM ####   Really slow on Ciara, fast on ASUS

call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall" amd64

REM	### COMPILATION default variables (in general for dynamic libs)

set CL= /MD 

set LINK=gdal_i.lib  proj_i.lib  User32.lib /subsystem:console /incremental:no /machine:x64 /DEFAULTLIB:MSVCRT /STACK:0X2000000

	REM for version 3.3.3

set LIB=C:\gdal_3.3.3\lib;%LIB%
set INCLUDE=C:\gdal_3.3.3\include;%INCLUDE%
set DESTDIR=C:\ITC-Suite_GDAL_v333\exe

C:\ITC-Suite_GDAL_v333\exe>  cl  %SRCDIR%\cwd_sfil_g.cpp /EHsc

********************************************************************************



		// End of documention

*/


//*****************************************************************************************


#define PROG_NAME "CWD_SFIL_G"
#define VERSION "v3.4"

#define Debug  0    // to skip unfinished sections

#define FILENAME    128
#define pi 3.14159
#define BITMAPS     16

#define MAX_INTERCEPT 100
#define BORDER 6				// need to be proportional to dd in width analysis


#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <time.h>       // time_t, struct tm, time, localtime 
#include <math.h>

#include "gdal_priv.h"		// For GDAL library
#include "cpl_conv.h" 		// for CPLMalloc()
#include "ogrsf_frmts.h"	// For OGR

#include "bitops.h"

// Now all in ITC-Suite_g.h, here called by bitops_h
//typedef unsigned char  PixVal;
//typedef signed __int64 int64;
//typedef unsigned __int64 uint64;

int	Pixels, Lines, Channels;

time_t rawtime;
struct tm * timeinfo;



// Structure - list of tree crown encountered and parameters 
// ***HERE*** in CWD_SFIL crown are objects like logs, stumps, ... 

typedef struct crown_info 
	{
	int area;			/* object  area */
	int init_x;			// initial position (x,y)
	int init_y;
	double init_East;		// initial position UTM
	double init_North;
	int xmin;			// diam in both directions
	int xmax;
	int ymin;
	int ymax;
	double UTM_East;			/* UTM centroid of object */
	double UTM_North;
	float length;			/* object length (m) */
	float width;			/* object width (m) */
	float volume;			/* object volume */
	int removed;			/* object removed flag */
	struct crown_info *next_crown;	// used to create a list
	} crown;


// Data structures for polgons


//data structure for points

	typedef struct MyPoint2D
	{
	double dX;
	double dY;
	} MyPoint2D;

//data structure for lines

	typedef struct MyLine2D
	{
	std::vector<MyPoint2D>LineString;
	} MyLine2D;

//data structure for a line feature

	typedef struct LineFeature
	{
	std::vector<MyLine2D>LinesOfFeature;
	} LineFeature;

//Holds Coordinates of Line Shapefile

	std::vector<LineFeature> LineLayer;


//data structure for rings

	typedef struct MyRing2D
	{
	std::vector<MyPoint2D>RingString;
	bool IsClockwised;
	} MyRing2D;


//data structure for polygons

	typedef struct MyPolygon2D
	{
	std::vector<MyRing2D> Polygon;
	} MyPolygon2D;

//data structure for a polygon feature

	typedef struct PolygonFeature
	{
	std::vector<MyPolygon2D>PolygonsOfFeature;
	}PolygonFeature;

//Holds Coordinates of Polygon Shapefile

	std::vector<PolygonFeature> PolygonLayer;



typedef struct
{
    double              x;
    double              y;
} GDBVertex;




/* function declarations */

void fill_log (int, int, crown *);
void fill_blob (int, int, crown *);
void fill_8c_blob (int, int, crown *);
void erase_log (int, int, crown *);
void erase_blob (int, int, crown *);
void erase_8c_blob (int, int, crown *);
void safety_zone(unsigned char *);
void prep_bmp_zero(PixVal *, int, int);
void init_rec(crown *);
void view_around(crown *);

//void 	paint_plot(GDBLayer, unsigned char *, int);


void 	vect2rast(int,  GDBVertex *, unsigned char *, int, int ShapeId, int set_flag);

int  	between(float a, float b, float c);


// Main list of logs (here crowns)
// (left as "crowns" for compatibilty with ITC Suite and because the word "log" is a problem (as in logarithm)
// *** NOTE ***: crown_list is mostly for debugging and can be turn off by  the "crown_list_flag"

crown_info	*crown_list;
crown_info 	*previous_crown;

int crown_list_flag = 0;			// use a SINGLE crown (log) object
//int crown_list_flag = 1;			// accumulate a list of crowns (logs) NB: could blow the stack


unsigned char *isolbitbuf, *outbitbuf, *testbitbuf, *isolbitbufcop, *outBM;

double 		topleftX, transformX, topleftY, transformY, botrightX, botrightY;
float		xpixsz, ypixsz, xcg_adjust, ycg_adjust;
//GDBVertex	*tmpVertices;
int		RingStart[24], RingField, RingStartCount;	/* at max., 24 sections to a shape */
int 		RingFlag2;		/* Flag on if rings are present within this particular shape */ 
int 		North;
int		xcg, ycg;

int 		shp_area;
float		shp_area_ha;

float		Total_area=0.0, pix_area, image_area_ha = 0.0;
int		Total_crowns=0;
int 	Poly_Outside = 0;		//to flag polygon that are outside the image area
int 	bmoffset = 0;

// for test area as shp file

   	PolygonFeature Polygon;
   	OGRPoint ptTemp;
	int k,h,last_vert;
	int NumberOfInnerRings; 
	int NumberOfExteriorRingVertices, NumberOfInteriorRingVertices, nVertex;



/****************************** main prog. ********************************/

int main(int argc, char *argv[])
{

/* local vars list */

FILE *idb_fp;
char file[FILENAME];
int dbib,dbob;
int diam_thr[10];
float leng_thr[10];


GDALDataset	*ima_in, *ima_out, *shp_in, *mask_in;

double		adfGeoTransform[6], adfGeoTransform2[6];

GDALDriver 	*poDriver;

char **papszOptions = NULL;


GDALRasterBand	*piBand, *piBand2, *poBand;
PixVal		*pafScanline;
PixVal		*In_line,*Out_line;
PixVal		*CWD_BM, *LOGs_BM, *TEST_BM;	// input and output bitmaps

char 	**papszMetadata;

int 	out_ch=1, input_ch[2], no_ch=1, ii=0;

char	*temp, *proj, *proj2;

char 	*fullfilename, *filename, *extension, *ext;
char 	*tstring, *p;
//char	*file_in, *file_out, *file_shp, *file_bit;
char	file_in[FILENAME], file_out[FILENAME], file_shp[FILENAME], file_bit[FILENAME];

int 	segm_vec=0, segm_bit=0;		// flags: mask segment is vector or bitmap


int	i, j, jj, no_items;
int	xsize, ysize, channels;
float	xpixsz, ypixsz;

uint64	bitnum, sizeBM;

int 	segnum;
int 	segtype;
int     testsegI[BITMAPS], testseg[BITMAPS];
int	lsizthr,hsizthr;
char	segflag, segname[9];
char    seg_history[56], seg_desc[81], geosys[17];
long 	start, seg_len;
char 	pix_units[9], timedate[17];

float	x_length, y_length, log_length;


FILE   *logs_fp, *diam_60Plus_fp;

//ProjInfo_t	pProj;
// GDBLayer 	player;


OGRLayer  	*piLayer, *poLayer;
OGRFeature 	*piFeature, *poFeature;
OGRFeatureDefn	*piFDefn, *poFDefn;
OGRFieldDefn	*piFieldDefn, *poFieldDefn;
OGRSpatialReference *piSRSIn,  *poSRSIn;
OGRGeometry 	*piGeometry, *poGeometry;

int 		iFeat=0, iField, layer_count, feat_count, field_count, last_feat,layer_toget, last_field;
int 		set_flag, TVertices=0;

int t_crown=0, e_crown=0, s_crown=0, j_count=0, isum=0;
float Total_volume=0.0;

crown *p1; 			// pointer to a single crown OR used in a list of crowns (logs)

GDBVertex * pasVertices;


// TEST LOG  - when testing for a specfic log - its initial positions

//double 		tlog_E = 0.0, tlog_N = 0.0; 		// no test log, no test log reports

double 		tlog_E = 331887.183,	tlog_N = 5526941.72;



//***************************************************************

//***************************** Start main prog. ****************

//***************************************************************


// Print Program Header and time 

	time (&rawtime);
	timeinfo = localtime (&rawtime);

	fprintf(stdout,"\n\t\tStarting %s (%s) at %s\n", PROG_NAME, VERSION, asctime(timeinfo));


// Register drivers for all formats 

	GDALAllRegister();

	temp = (char *) CPLMalloc(200);
	ext =  (char *) CPLMalloc(10);

//***************************************************************

// Check MAIN input parameters (i.e., agrv[*])

//*******************************************************************

// CWD image - 1bit tif image (i.e., bitmap)

	if (argv[1] == NULL) 
	  { printf("\n\n** PROBLEM with input CWD tif bitmap %s \n",argv[1]);
	  printf("\tHave an input CWD tif bitmap as first argument on command line \n");
	  printf("Typical use: CWD_SFIL_g  Name_CWD.tif Name_LOGs.tif Test_Areas.shp  10,100 1,100\n\n");
	  exit(1); } 

	//file_in = argv[1];		// CWD image (bitmap)
	strcpy(file_in, argv[1]);		// CWD image (bitmap)
	
// LOGs image - 1bit tif image (i.e., bitmap)

	if (argv[2] == NULL) 
	  { printf("\n\n** PROBLEM with output LOGs tif bitmap %s \n",argv[2]);
	  printf("\tHave an output LOGs tif bitmap as second argument on command line\n");
	  printf("Typical use: CWD_SFIL_g  Name_CWD.tif Name_LOGs.tif Test_Areas.shp  10,100 1,100\n\n");
	  exit(1); } 

	//file_out = argv[2];		// LOGs image (bitmap)
	strcpy(file_out,argv[2]);		// LOGs image (bitmap

// Area of interest in bitmap form or vector form (shp file)

	if( (argv[3]  == NULL) || (strncmp(argv[3],"nada",4) == 0) || ( strncmp(argv[3],"-",1) == 0) )
	  {
	  printf("\n***No \"area of interest\" file as third argument. Prog. will analyse the whole image. \n\n");
	  printf("NOTE: The whole image will be \"assumed\" to be a field of debris (CWD).\n");
	  printf("      This could implies artifacts outside a decent open area with CWD (i.e., in the forest)\n");
	  printf("HINT: Using \"nada\" could give you access to parameters 4 and 5 (diam and length thresholds)\n");
	  printf("      Here, defaults parameters 4 and 5 (diam and length thresholds) will be used\n\n");

	  diam_thr[0] = 10; diam_thr[1] = 100; leng_thr[0] = 1.0; leng_thr[1] = 100.0; 		// default values

	  printf("\t**Keeping logs of diameters between %d and %d cm\n", diam_thr[0],diam_thr[1]);
	  printf("\t**Keeping logs of length between %.1f and %.1f metres\n\n", leng_thr[0],leng_thr[1]);

	  goto L10;
	  } 

	  //printf("*Checking if mask %s is bitmap layer (i.e., .tif(nbits=1) OR vector layer (.shp)\n\n",argv[3]);

	strcpy(temp,argv[3]);

	//printf("\nFull name in 3rd arg : %s \n", temp);
	strtok(temp, ".");
	//printf("Base name : %s \n", temp);
 	ext = strtok(NULL, " .");
	//printf("Extension : %s \n", ext  );
	
	if( strncmp(ext,"shp",3) == 0) 	{ strcpy(file_shp,argv[3]); segm_vec = 1; printf("\nUsing a Vector test areas ...\n");}
	if( strncmp(ext,"tif",3) == 0) 	{ strcpy(file_bit,argv[3]); segm_bit = 1;printf("Using a Bitmap test areas ...\n"); }

	//exit(1);

//*********************************************************************

//	Other  input parameters (i.e., agrv[*])

//*******************************************************************	

// Check diameter thresholds 


L0:	if (argv[4] == NULL) 			// use default values
	  {
	  diam_thr[0] = 10; diam_thr[1] = 100; leng_thr[0] = 1.0; leng_thr[1] = 100.0; // default values
	  printf("\n\t**Keeping logs of diameters between %d and %d cm\n", diam_thr[0],diam_thr[1]);
	  printf("\t**Keeping logs of length between %.1f and %.1f metres\n\n", leng_thr[0],leng_thr[1]);
	  goto L10;
	  }

	if( (strncmp(argv[4],"nada",4) == 0) ||( strncmp(argv[4],"-",1) == 0) )
					 { diam_thr[0] = 10; diam_thr[1] = 100; goto L1;} 					// default values
 
	printf("\nDiameter thresholds to use: %s \n", argv[4]);

	jj = 0;
	strcpy(temp, argv[4]);
	p = strtok(temp, ",");

	while(p != NULL) 
	  {
 	  //printf("%s\n", p); 
	  diam_thr[jj++] = strtol(p,NULL, 10);
	  p = strtok(NULL, ",");
	  }
	no_items = jj;

	if(no_items > 2)  {printf("\nOnly two threshols are allowed (min,max) \n"); exit(1); }

L1:

	printf("\n\t**Keeping logs of diameters between %d and %d cm\n", diam_thr[0],diam_thr[1]);


// Check length thresholds

	if (argv[5] == NULL) { leng_thr[0] = 1.0; leng_thr[1] = 100.0;  goto L2;}  	// default values

	if( (strncmp(argv[5],"nada",4) == 0) || ( strncmp(argv[5],"-",1) == 0) )
				{ leng_thr[0] = 1.0; leng_thr[1] = 100.0;  goto L2;}  			// default values

	printf("\nLength thresholds to use: %s \n", argv[5]);
  
	jj = 0;
	strcpy(temp, argv[5]);
	p = strtok(temp, ",");

	while(p != NULL) 
	  {
 	  //printf("%s\n", p); 
	  leng_thr[jj++] = strtol(p,NULL, 10);
	  p = strtok(NULL, ",");
	  }
	no_items = jj;

	if(no_items > 2)  { printf("\nOnly two threshols are allowed (min,max) \n"); exit(1); }

L2:
	
	printf("\t**Keeping logs of length between %.1f and %.1f metres\n\n", leng_thr[0],leng_thr[1]);



//**************************************************************************

// Open input image file (a tif that is actually a bitmap NBITS=1)
  
//***************************************************************

L10:

	ima_in = (GDALDataset *) GDALOpen( file_in, GA_ReadOnly );
	
	if (ima_in == NULL) 
	  	{printf("\n\n PROBLEM opening input CWD file %s \n\n",file_in); exit(1);}
	
	fprintf(stdout,"\n\t*File \"%s\" was opened for reading\n\n",file_in);

// Print generic info (Driver used, image size, ... )

	printf("Driver: %s/%s\n", ima_in->GetDriver()->GetDescription(), ima_in->GetDriver()->GetMetadataItem(GDAL_DMD_LONGNAME) );

// Check that incoming channel is a bitmap (not an image)
	
	int segm_in = 1;
	piBand = ima_in->GetRasterBand(segm_in);		// Access bitmap channel (i.e, segment)
	//piBand = ima_in->GetRasterBand(0);			// nice test
	
	if(piBand == NULL)  
		{ printf("\n\t*Unable to get bitmap layer as specified\n\n"); exit(-1);}

	printf("\nOpening input bitmap channel (layer) %d of Type = %s \n",
						segm_in, GDALGetDataTypeName(piBand->GetRasterDataType()) );
	printf("Metadata item (NBITS): %s \n", piBand->GetMetadataItem("NBITS","IMAGE_STRUCTURE") );	

	if ( piBand->GetMetadataItem("NBITS","IMAGE_STRUCTURE") == NULL)
	  {
	  printf("\n\t*** Specified channel (%d) for training area is not a bitmap\n",segm_in);
	  printf("\nImage : %s Type = %s \n", ima_in->GetDescription(), GDALGetDataTypeName(piBand->GetRasterDataType()));
	  printf("Channel Description: %s \n", piBand->GetDescription() );
	  printf("\n***Please double check that input file (Hint: use \"gdalinfo\" on the file) \n  **Exiting**\n");
	  exit(1);
	  }


// #########
	

// Other info (color table info)

/*
	if( piBand->GetColorTable() != NULL )
	    printf("\t\t* Above bitmap has a color table with %d entries.\n\n",
            		piBand->GetColorTable()->GetColorEntryCount() );


// Other color table stuff

	//piBand->SetColorInterpretation(GDALColorInterp::GCI_PaletteIndex);	
	
	printf("\t\t* ColorInterpretation : %d \n", piBand->GetColorInterpretation() );
		//GCI_PaletteIndex=2 is OK
		
	printf("\t\t* PaletteInterpretation : %d \n", piBand->GetColorTable()->GetPaletteInterpretation() );
	// PaletteInterpretation GPI_RGB=1
	
	printf("\t\t* PaletteInterpretation Name : %s\n\n",
			GDALGetPaletteInterpretationName(piBand->GetColorTable()->GetPaletteInterpretation()));

	
	//piBand->GetColorTable()->GetColorMap();
	//piBand->GetColorMap();

// Input color table from input image

    const GDALColorEntry * col_ent;	
 
	col_ent = piBand->GetColorTable()->GetColorEntry(0);
	//std::cout << col_ent->c1 << std::endl;
 	printf("\t\t* Color entries for 0  : %d %d %d %d \n\n", col_ent->c1, col_ent->c2, col_ent->c3, col_ent->c4);

	col_ent = piBand->GetColorTable()->GetColorEntry(1);
 	printf("\t\t* Color entries for 1  : %d %d %d %d \n\n", col_ent->c1, col_ent->c2, col_ent->c3, col_ent->c4);


//#####

*/
	
// Print generic info

    Pixels = ima_in->GetRasterXSize();
	Lines = ima_in->GetRasterYSize(); 
	Channels = ima_in->GetRasterCount();
	
	printf( "Image size is %dP x %dL x %dCH\n\n", Pixels, Lines, Channels);
	xsize = Pixels; ysize = Lines;

// Print geographic info

  	//printf( "Full projection is %s \n\n", ima_in->GetProjectionRef() );

	proj = (char *) CPLMalloc(200);
	
	if( ima_in->GetProjectionRef() != NULL ) 
	  {
	  strncpy(temp, ima_in->GetProjectionRef(),30);
	  strtok(temp, "\"");
	  //printf("1st section : %s \n", temp);
 	  proj = strtok(NULL, "\"");
	  printf("Projection: %s \n", proj );
	  }
	else printf("Note: No Geographic \"Projection\" within that file\n");

	printf("Geographic Data within that file\n");

	if( ima_in->GetGeoTransform( adfGeoTransform ) == CE_None )
	  {
	  printf( "Origin = (%.2f,%.2f)\n",
            adfGeoTransform[0], adfGeoTransform[3] );
	  printf( "Pixel Size = (%.3f,%.3f)\n",
            adfGeoTransform[1], adfGeoTransform[5] );
	  }

	xpixsz = adfGeoTransform[1];		ypixsz = abs(adfGeoTransform[5]);
	transformX = adfGeoTransform[1];	transformY = adfGeoTransform[5];

	pix_area = abs(xpixsz*ypixsz);

	if (adfGeoTransform[5] < 0.0) North=1; else North=0;		// Northern hemisphere flag 


// Topleft pixel center coordinates ( ***** CENTERS ALL COORDINATES MID-PIXEL *****)

    topleftX = adfGeoTransform[0] + xpixsz/2;
    topleftY = adfGeoTransform[3] + ypixsz/2;

// Get bottom right geo. image coords 
	
    botrightX = (adfGeoTransform[1] * Pixels) + topleftX;
    botrightY = (adfGeoTransform[5] * Lines) + topleftY;
	image_area_ha = Pixels*Lines*xpixsz*ypixsz/10000;
	
    printf("Bottom right geo. coordinates: (%.2f, %.2f)\n", botrightX, botrightY);
    printf("Image area:  %.2f ha.\n", image_area_ha);

// Size of bitmaps in bytes

    sizeBM = sizeof(unsigned char) * ((Pixels * Lines + 7) / 8);
    printf("Size of bitmap (in bytes) %ld \n", sizeBM);
	
	//exit(1);

//**********************************************************************

// Open an output text files to get some specific results 


printf("\nPreparing output text file of logs meeting criteria : \"Logs_CWD_GDAL.txt\" \n\n");

logs_fp = fopen("Logs_CWD_SFIL.txt","w");

time (&rawtime); timeinfo = localtime (&rawtime);

fprintf(logs_fp,"\n\tFrom program %s (%s) at %s\n\n", PROG_NAME, VERSION, asctime(timeinfo));

fprintf(logs_fp,"\tLogs with length between %.1f and %.1f m\n",leng_thr[0],leng_thr[1]);

fprintf(logs_fp,"\tAND with diameter between %d and %d cm\n\n",diam_thr[0],diam_thr[1]);

fprintf(logs_fp,"\nLog No., Xinit, Yinit, Initial East and North, CGrav East and North, Length(m), Diameter(m), Area(p), Volume(m3) \n\n");



//**********************************************************************

// Read Input CWD bitmap   (i.e., a NBITS=1 tif)

//**********************************************************************

	fprintf(stdout,"\n\t **Reading CWD data (i.e., 1bit tif) from file \"%s\" ...\n\n", file_in);
	
	CWD_BM = (PixVal *) CPLMalloc(sizeof(PixVal)*Pixels*Lines); 	 // ### Full 8bit image
	
	//piBand = ima_in->GetRasterBand(0);		// nice test to see if it reacts
	//piBand = ima_in->GetRasterBand(1);		// was already open above
	
// Other info (color table)
/*
	if( piBand->GetColorTable() != NULL )
	    printf("\t\t* Band has a color table with %d entries.\n\n",
            		piBand->GetColorTable()->GetColorEntryCount() );
*/

// Read *** input image (Bitmap) *** in one shot

	  piBand->RasterIO(GF_Read, 0, 0, Pixels, Lines, CWD_BM, Pixels, Lines, GDT_Byte,0, 0 );


// Sum all pixels with image (bitmap) (as a check)

/*
	isum = 0;
 	for (i = 0; i < Lines; i++) 
	  for (j = 0; j < Pixels; j++) 
		isum = isum + CWD_BM[i*Pixels+j];
	printf("\n\t\t Checking - Sum of all \"bytes\" in CWD image in memory : %d \n\n", isum);
*/

// Print some pixels to see

/*	printf("\n\t Some pixels around pixel 4635 line 7950 : \n\n");

 	for (i = 7934; i < 7964; i++) 
	  {
	  for (j = 4620; j < 4650; j++) printf("%d ", CWD_BM[i*Pixels+j]); 
	  printf("\n");
	  }
*/

// Turn 8bit image into a bitmap for further processing (i.e.,to be compatible with PCI version of main code)

	printf("\t* Turning input tif (nbits=1) into a bitmap in memory\n");

	isolbitbuf = (PixVal *) CPLMalloc(sizeBM);		 // create input bitmap

	for ( i = 0 ; i < (ysize) ; i++ )		// image starts at zero
	for ( j = 0 ; j < (xsize) ; j++ ) 
	  {
	  bitnum = (i)*(int64)Pixels + j ;		// bitnum starts at zero
	  if (CWD_BM[i*Pixels+j])  setbit(isolbitbuf, bitnum);
	  }


// Sum all bits in bitmap (as a check)

	//printf("\n\t\t Checking - Sum of all \"set bits\" in bitmap in memory ...\n");
/*
	isum = 0;
 	for ( i = 0 ; i < (ysize) ; i++ )		// image starts at zero
	for ( j = 0 ; j < (xsize) ; j++ ) 
	  {
	  bitnum = (i)*(int64)Pixels + j ;		// bitnum starts at zero
	  if(testbit(isolbitbuf, bitnum)) isum++;
	  }
	printf("\n\t\t Checking - Sum of all \"set bits\" in input CWD bitmap  : %d \n\n", isum);
*/

// create safety zone not to go off image

	//safety_zone(isolbitbuf);
	prep_bmp_zero(isolbitbuf, xsize, ysize);

// Make a copy  of isolbitbuf to possibly use many times with different test area mask

	isolbitbufcop = (PixVal *) CPLMalloc(sizeBM);	
	for (i = 0; i < sizeBM; i++) *(isolbitbufcop + i) = (*(isolbitbuf + i));


// Create OUTPUT bitmap and its image 

	outbitbuf = (PixVal *) CPLMalloc(sizeBM);		 // Create temp output bitmap

	outBM = (PixVal *) CPLMalloc(sizeBM);	 		// Create real output bitmap
	   
	LOGs_BM = (PixVal *) CPLMalloc(sizeof(PixVal)*Pixels*Lines);  // Create memory for output tif(nbits=1) file


	//exit(-1);			// for debugging 

//**********************************************************************

// If no test area -> do the full image

	if( (segm_vec + segm_bit) == 0)  goto Main;


//***********************************************************************

// If given a bitmap TEST AREA, open the bitmap test area as testbitbuf 

//*******************************************************************

//	   printf("\n\t* Created testbitbuf in memory \n\n");

	testbitbuf = (PixVal *) CPLMalloc(sizeBM);						// bitmap
	TEST_BM = (PixVal *) CPLMalloc(sizeof(PixVal)*Pixels*Lines); 	 // ### Full 8bit image

//  OPEN ** bitmap file ** to use as area of interest (i.e., cut area with debris)

	if (segm_bit)
	{

	printf("\n**Reading test area bitmap (i.e., 1bit tif) from file %s ...\n\n", file_bit);

	mask_in = (GDALDataset *) GDALOpen( file_bit, GA_ReadOnly );
		
	if (mask_in == NULL) 
	  	{printf("\n\n PROBLEM opening test area (BM) file %s \n\n",file_bit); exit(1);}

	fprintf(stdout,"\n\t*File \"%s\" was opened for reading\n\n",file_bit);

// Print generic info (Driver used, image size, ... )

	printf("Driver: %s/%s\n", mask_in->GetDriver()->GetDescription(), mask_in->GetDriver()->GetMetadataItem(GDAL_DMD_LONGNAME) );

// Check that incoming channel is a bitmap (not an image)

	int segm_in = 1;
	piBand2 = mask_in->GetRasterBand(segm_in);		// Access bitmap channel (i.e, segment)
	if(piBand2 == NULL)  
		{ printf("\n\t*Unable to get bitmap layer as specified\n\n"); exit(-1);}

	printf("\nOpening input bitmap channel (layer) %d of Type = %s \n",
						segm_in, GDALGetDataTypeName(piBand2->GetRasterDataType()) );
	printf("Metadata item (NBITS): %s \n", piBand2->GetMetadataItem("NBITS","IMAGE_STRUCTURE") );	

	if ( piBand2->GetMetadataItem("NBITS","IMAGE_STRUCTURE") == NULL)
	  {
	  printf("\n\t*** Specified channel (%d) for training area is not a bitmap\n",segm_in);
	  printf("\nImage : %s Type = %s \n", mask_in->GetDescription(), GDALGetDataTypeName(piBand2->GetRasterDataType()));
	  printf("Channel Description: %s \n", piBand2->GetDescription() );
	  printf("\n***Please double check that input file (Hint: use \"gdalinfo\" on the file) \n  **Exiting**\n");
	  exit(1);
	  }
	  
// Print generic info

    Pixels = mask_in->GetRasterXSize(); Lines = mask_in->GetRasterYSize(); Channels = mask_in->GetRasterCount();
	printf( "Image size is %dP x %dL x %dCH\n\n", Pixels, Lines, Channels);
	xsize = Pixels; ysize = Lines;

// Print geographic info

  	//printf( "Full projection is %s \n\n", mask_in->GetProjectionRef() );

	proj2 = (char *) CPLMalloc(200);
	
	if( mask_in->GetProjectionRef() != NULL ) 
	  {
	  strncpy(temp, mask_in->GetProjectionRef(),30);
	  strtok(temp, "\"");
	  //printf("1st section : %s \n", temp);
 	  proj2 = strtok(NULL, "\"");
	  printf("Projection: %s \n", proj2 );
	  }
	else printf("\nNOTE: No Geographic \"Projection\" within that file\n");

// May need to check that Geographic projection is same as main	(i.e, proj2 = proj)

// Get  geographic location 

	if( mask_in->GetGeoTransform( adfGeoTransform2 ) == CE_None )
	  {
	  printf( "Origin = (%.2f,%.2f)\n",
            adfGeoTransform2[0], adfGeoTransform2[3] );
	  printf( "Pixel Size = (%.3f,%.3f)\n",
            adfGeoTransform2[1], adfGeoTransform2[5] );
	  }


// Check that geographic location is "roughly" same


	 for (ii = 0; ii < 6; ii++)
	 {		 
	   //if (adfGeoTransform2[ii] != adfGeoTransform[ii])
	   if ((int)adfGeoTransform2[ii] != (int)adfGeoTransform[ii])
	   {printf("\nINCOMPATIBILTIES with geographic coordinates of main file\n\n"); exit(-1);}
	 }
	 
// Reading test area bitmap per se
	
	piBand2->RasterIO(GF_Read, 0, 0, Pixels, Lines, TEST_BM, Pixels, Lines, GDT_Byte,0,0);

// Sum all pixels with image (bitmap) (as a check)
/*
	isum = 0;
 	for (i = 0; i < Lines; i++) 
	  for (j = 0; j < Pixels; j++) 
		isum = isum + TEST_BM[i*Pixels+j];
*/
	//printf("\n\t\t Checking - Sum of all \"bytes\" in \"test area\" image in memory : %d \n\n", isum);


// Turn 8bit image into a bitmap for further processing (i.e., more compatible with PCI version)


	printf("\n\t* Turning input tif (nbits=1) into bitmap in memory\n\n");

	//for ( i = 0 ; i < (ysize) ; i++ )		// image starts at zero

	for ( i = 3 ; i < (ysize) ; i++ )		// some junk at bottom of bitmap 4
	for ( j = 0 ; j < (xsize) ; j++ ) 

	  {
	  bitnum = (i)*(int64)Pixels + j ;		// bitnum starts at zero
	  if (TEST_BM[i*Pixels+j])  setbit(testbitbuf, bitnum);
	  }

// Sum all bits in bitmap (as a check)

	isum = 0;
 	for ( i = 0 ; i < (ysize) ; i++ )		// image starts at zero
	for ( j = 0 ; j < (xsize) ; j++ ) 
	  {
	  bitnum = (i)*(int64)Pixels + j ;		// bitnum starts at zero
	  if(testbit(testbitbuf, bitnum)) isum++;
	  }
	  
	//printf("\n\t\t Checking - Sum of all \"set bits\" in \"test area\" bitmap in memory : %d \n\n", isum);
	
	shp_area = isum;	// in this case bitmap area

	goto PreMain;
	
	//exit(1);

	}		// end of "if (segm_bit)"


//*******************************************************************************************

//  OPEN ** shp file ** to use as areas of interest (i.e., cut area with debris or sample areas)

//****************************************************************************************

	printf("\n\n* Test areas of interest are in vector format\n\n");
	
	//shp_in = (GDALDataset*) GDALOpenEx( file_shp,GA_ReadOnly, NULL, NULL, NULL );
	shp_in = (GDALDataset*) GDALOpenEx( file_shp, (GA_ReadOnly || GDAL_OF_VECTOR), NULL, NULL, NULL );
	//shp_in = static_cast<GDALDataset*> (GDALOpenEx( file_shp, GDAL_OF_VECTOR, NULL, NULL, NULL ) );
	//shp_in =  (GDALDataset *) GDALOpen( file_shp, GA_ReadOnly );
	
	if( shp_in == NULL )
	  {
	  printf( "\n ****Failed to open input \"shp\" file.\n" );
	  exit( 1 );
	  }
	fprintf(stdout,"\n\t **File \"%s\" was opened for reading polygon areas of interest \n\n", file_shp);

// Print generic info (Driver used, image size, ... )

	printf("Driver used: %s/%s\n", shp_in->GetDriver()->GetDescription(), shp_in->GetDriver()->GetMetadataItem(GDAL_DMD_LONGNAME) );

// Open first (and only) layer

	layer_count =  shp_in->GetLayerCount();
	if(layer_count == NULL) { printf("\n\t*There are no vector layer in this file \n"); exit(-1);}
	printf("\n* Number of layers in vector file is %d \n\n", layer_count);

	if ( layer_count != 1 )
	  {
	  fprintf(stdout,"\n\t ##### Present version only deal with one layer shp file \n\n");
	  exit(1);
	  }

	layer_toget = 0;		// Layer numbers start at zero
	
	piLayer = shp_in->GetLayer(layer_toget);
	//piLayer = shp_in->GetLayerByName("WHO_All_SBX_RBX_Plots");	

	if(piLayer == NULL) {printf("\n\t**The layer specified (%d) may not exist**\n",layer_toget); exit(1);}
				
	piLayer->ResetReading();

	//fprintf(stdout,"\n\tAccessing layer %d \n\n",layer_toget+1);

	//exit(1);

// Number of features (i.e., polygons) in that layer and number of fields in that layer

	piFDefn = piLayer->GetLayerDefn();
	feat_count = piLayer->GetFeatureCount();
	field_count = piFDefn->GetFieldCount();
	fprintf(stdout,"Layer %d of current file has %d features with %d fields each\n\n", layer_toget+1, feat_count, field_count);


// Get polygon spatial reference

  	//printf( "SHP file projection is %s \n\n", shp_in->GetProjectionRef() );

	proj2 = (char *) CPLMalloc(200);

	if( shp_in->GetProjectionRef() != NULL ) 
	  {
	  strncpy(temp, shp_in->GetProjectionRef(),30);
	  strtok(temp, "\"");
	  //printf("1st section : %s \n", temp);
 	  proj2 = strtok(NULL, "\"");
	  printf("Shp file Projection: %s \n", proj2 );
	  }
	else printf("\nNote: No Geographic \"Projection\" within that file\n");
	

// May need to check that Geographic projection is same as main	(i.e, proj2 = proj)


// Get  geographic location 

	if( shp_in->GetGeoTransform( adfGeoTransform2 ) == CE_None )
	  {
	  printf( "Origin = (%.2f,%.2f)\n",
            adfGeoTransform2[0], adfGeoTransform2[3] );
	  printf( "Pixel Size = (%.2f,%.2f)\n",
            adfGeoTransform2[1], adfGeoTransform2[5] );
	  }

// Check that geographic location is "roughly" same
/*
	 for (ii = 0; ii < 6; ii++)
	 {		 
	   //if (adfGeoTransform2[ii] != adfGeoTransform[ii])
	   if ((int)adfGeoTransform2[ii] != (int)adfGeoTransform[ii])
	   {printf("\nINCOMPATIBILTIES with geographic coordinates of main file\n\n"); exit(-1);}
	 }
*/	

	
//**********************************************************************

// Getting polygon AND multipolygon vertices


// prep list of vertices for my vect2rast() - assuming island in main poly are smaller poly

	nVertex =  10000;		// arbitrary number
  	pasVertices = (GDBVertex *)  CPLMalloc(nVertex * sizeof(GDBVertex));

  // #### Make sure testbitbuf is zeroed before putting stuff in it  
  	 for ( ii = 0 ; ii < sizeBM ; ii++ ) testbitbuf[ii] = 0; 

	shp_area = 0;		// reset shape area (will be added to, or substract to depending on set_flag in vect2rast()

	printf("\nLooping through features (polygons) to burn into test area bitmap ...\n\n");

	TVertices = 0;
	while ( piFeature = piLayer->GetNextFeature() )
	  {
	  iFeat++;	// keep track of feature number
	  printf("\n**For feature %d \n", iFeat);

	  TVertices = 0;	// reset total no. vertices of shape (this is to check that all were considered)
 	  //shp_area = 0;		// reset shape area (will be added to, or substract to depending on set_flag in vect2rast()

  // #### Make sure testbitbuf is zeroed before putting stuff in it  
  	 for ( ii = 0 ; ii < sizeBM ; ii++ ) testbitbuf[ii] = 0;

	 
/*
	  // Sometimes shp files from PCI file (from ras2poly) have a "full extent polygon" as first polygon (skip that)

	  piFieldDefn = piFDefn->GetFieldDefn(2);
	  if ( (strncmp(piFieldDefn->GetNameRef( ),"PixelValue",10) == 0) && (piFeature->GetFieldAsInteger(2) == 0) )
	    {
	    printf("\nHERE, skipping 1st polygon cause a full area polygon\n");
	    //piFeature = piLayer->GetNextFeature(); 		//skip 1st polygon - a full area polygon
	    }
*/

	  piGeometry = piFeature->GetGeometryRef();

	  printf("Geometry is of type : %d \n", piGeometry->getGeometryType());


// #### For polygons

	  if ( piGeometry != NULL && wkbFlatten(piGeometry->getGeometryType()) == wkbPolygon )
	    {
	    OGRPolygon *piPolygon = (OGRPolygon *)piGeometry;

	    Polygon.PolygonsOfFeature.resize(1);
	    NumberOfInnerRings = piPolygon->getNumInteriorRings();
            OGRLinearRing *piExteriorRing = piPolygon->getExteriorRing();
	    printf("Number of inner rings = %d \n", NumberOfInnerRings);

            Polygon.PolygonsOfFeature.at(0).Polygon.resize(NumberOfInnerRings+1);
            Polygon.PolygonsOfFeature.at(0).Polygon.at(0).IsClockwised = piExteriorRing ->isClockwise();

            NumberOfExteriorRingVertices = piExteriorRing->getNumPoints();
            Polygon.PolygonsOfFeature.at(0).Polygon.at(0).RingString.resize(NumberOfExteriorRingVertices);
	    printf("NumberOfExteriorRingVertices = %d \n", NumberOfExteriorRingVertices);

// Get exterior ring vertices 

            for ( k = 0; k < NumberOfExteriorRingVertices; k++ )
               {
               piExteriorRing->getPoint(k,&ptTemp);
               MyPoint2D pt;
               pt.dX = ptTemp.getX();
               pt.dY = ptTemp.getY();
               Polygon.PolygonsOfFeature.at(0).Polygon.at(0).RingString.at(k) = pt;
               pasVertices[k].x = pt.dX ;
               pasVertices[k].y = pt.dY ;
               }

// Using my vector to raster (to bitmap) painting routine

	   nVertex = k;
	   fprintf(stdout,"\n* Painting feature %d in raster in memory (nVertex=%d) \n", iFeat, nVertex);
	   
	   vect2rast(nVertex, pasVertices, testbitbuf, xsize, iFeat, set_flag=1);
	   
	   if (Poly_Outside) goto CONT_LOOP;		// if this Ploygon was outside the image, dont do anything for it

	   TVertices = TVertices  + nVertex ;

// get ALL interior ring vertices 

	if( NumberOfInnerRings > 0) printf("Erasing %d inner rings\n", NumberOfInnerRings);

         for ( h = 1; h <= NumberOfInnerRings; h++ )
           {
               OGRLinearRing *piInteriorRing = piPolygon ->getInteriorRing(h-1);

               Polygon.PolygonsOfFeature.at(0).Polygon.at(h).IsClockwised = piInteriorRing->isClockwise();
               NumberOfInteriorRingVertices = piInteriorRing->getNumPoints();
	       //printf("NumberOfInteriorRingVertices = %d \n", NumberOfInteriorRingVertices);

               Polygon.PolygonsOfFeature.at(0).Polygon.at(h).RingString.resize(NumberOfInteriorRingVertices);

               for ( k = 0; k < NumberOfInteriorRingVertices; k++ )
                 {
                 piInteriorRing ->getPoint(k,&ptTemp);
                 MyPoint2D pt;
                 pt.dX = ptTemp.getX();
                 pt.dY = ptTemp.getY();
                 Polygon.PolygonsOfFeature.at(0).Polygon.at(h).RingString.at(k) = pt;
                 pasVertices[k].x = pt.dX ;
                 pasVertices[k].y = pt.dY ;
                 }

// Using my vector to raster (bitmap) painting routinee

	   nVertex = k;
	   //fprintf(stdout,"\n\n* Un-painting feature %d in raster in memory (nVertex=%d) \n", iFeat, nVertex);
	   vect2rast(nVertex, pasVertices, testbitbuf, xsize, iFeat, set_flag=0);
	   TVertices = TVertices  + nVertex ;

           }	// burn (actually unburn) each inner ring separately


	//printf("For feature %d total number of vertices considered %d \n", iFeat, TVertices);

	   }		// end of if polgygon


// ####  For multipolygon (for multiple geometries)


	  if ( piGeometry != NULL && 
		( wkbFlatten(piGeometry->getGeometryType()) == wkbMultiPolygon ) )
	    {
	    OGRMultiPolygon *piMultiPolygon = (OGRMultiPolygon *)piGeometry;
            int NumberOfGeometries = piMultiPolygon ->getNumGeometries();
	    Polygon.PolygonsOfFeature.resize(NumberOfGeometries);


           for ( j = 0; j < NumberOfGeometries; j++ )
           {
               OGRGeometry *piPolygonGeometry = piMultiPolygon ->getGeometryRef(j);
               OGRPolygon *piPolygon = ( OGRPolygon * )piPolygonGeometry;
               NumberOfInnerRings = piPolygon ->getNumInteriorRings();
               OGRLinearRing *piExteriorRing = piPolygon ->getExteriorRing();

               Polygon.PolygonsOfFeature.at(j).Polygon.resize(NumberOfInnerRings+1);
	       printf("Number of inner rings = %d \n", NumberOfInnerRings);

               Polygon.PolygonsOfFeature.at(j).Polygon.at(0).IsClockwised = piExteriorRing ->isClockwise();
               NumberOfExteriorRingVertices = piExteriorRing ->getNumPoints();
               Polygon.PolygonsOfFeature.at(j).Polygon.at(0).RingString.resize(NumberOfExteriorRingVertices);
               printf("NumberOfExteriorRingVertices = %d \n", NumberOfExteriorRingVertices);

               for ( k = 0; k < NumberOfExteriorRingVertices; k++ )
                 {
                 piExteriorRing->getPoint(k,&ptTemp);
                 MyPoint2D pt;
                 pt.dX = ptTemp.getX();
                 pt.dY = ptTemp.getY();
                 Polygon.PolygonsOfFeature.at(j).Polygon.at(0).RingString.at(k) = pt;
                 pasVertices[k].x = pt.dX ;
                 pasVertices[k].y = pt.dY ;
                 }

	       nVertex = k;
	       fprintf(stdout,"\n* Painting feature %d in raster in memory (nVertex=%d) \n", iFeat, nVertex);
	       vect2rast(nVertex, pasVertices, testbitbuf, xsize, iFeat, set_flag=1);
	       TVertices = TVertices  + nVertex ;

// get ALL interior ring vertices 

	      if( NumberOfInnerRings > 0) printf("Erasing %d inner rings\n",NumberOfInnerRings);

              for ( h = 1; h <= NumberOfInnerRings; h++ )
               {
                   OGRLinearRing *piInteriorRing = piPolygon ->getInteriorRing(h-1);
                   Polygon.PolygonsOfFeature.at(j).Polygon.at(h).IsClockwised = piInteriorRing ->isClockwise();
                   NumberOfInteriorRingVertices = piInteriorRing ->getNumPoints();
                   Polygon.PolygonsOfFeature.at(j).Polygon.at(h).RingString.resize(NumberOfInteriorRingVertices);
	           //printf("NumberOfInteriorRingVertices = %d \n", NumberOfInteriorRingVertices);

                   for ( k = 0; k < NumberOfInteriorRingVertices; k++ )
                     {
                     piInteriorRing->getPoint(k,&ptTemp);
                     MyPoint2D pt;
                     pt.dX = ptTemp.getX();
                     pt.dY = ptTemp.getY();
                     Polygon.PolygonsOfFeature.at(j).Polygon.at(h).RingString.at(k) = pt;
                     pasVertices[k].x = pt.dX ;
                     pasVertices[k].y = pt.dY ;
                     }

	      nVertex = k;
	      //fprintf(stdout,"\n\n* Un-painting feature %d in raster in memory (nVertex=%d) \n", iFeat, nVertex);
	      vect2rast(nVertex, pasVertices, testbitbuf, xsize, iFeat, set_flag=0);
	      TVertices = TVertices  + nVertex ;

              }	// end of number of inner rings

	    }		//  end of number of Geometries

             PolygonLayer.push_back(Polygon);

	    // printf("For feature %d total number of vertices considered %d \n", iFeat, TVertices);

	    }		//end of multipolygon 



	 }			// ### End of feature loop (when all sub-test areas are done at once)



//********************************************************************

// Apply mask to main CWD image so that work is only done on such test areas

//********************************************************************

PreMain:

if(segm_bit || segm_vec)
  {

	printf("\n\t*Applying \"test areas mask\" to input CWD bitmap so only these areas are considered ... \n\n");

	  for (i = 0; i < sizeBM; i++)
		*(isolbitbuf + i) = (*(isolbitbufcop + i)) & (*(testbitbuf + i));


// Sum all bits in bitmap (as a check)

	//printf("\n\t\t Checking - Sum of all \"set bits\" in bitmap in memory ...\n");
/*
	isum = 0;
 	for ( i = 0 ; i < (ysize) ; i++ )		// image starts at zero
	for ( j = 0 ; j < (xsize) ; j++ ) 
	  {
	  bitnum = (i)*(int64)Pixels + j ;		// bitnum starts at zero
	  if(testbit(isolbitbuf, bitnum)) isum++;
	  }
*/
	//printf("   Sum of all \"set bits\" after mask was applied : %d \n\n", isum);

  }

	//exit(1);

/**********************************************************************/

//	Main processing section

/**********************************************************************/

Main:


printf("\n\t **Copying input bitmap to OUTPUT bitmap so that you can then ERASE unwanted material \n\n");

// If no test area used, do the full image

	//if((segm_vec+segm_bit)==0)  memcpy(outbitbuf, isolbitbuf, sizeBM); 
	
// Copy all as test area mask dealt with earlier
	
	memcpy(outbitbuf, isolbitbuf, sizeBM);

// if test areas are used copy only section to work on so you dont mess-up other sections 

/*
if(segm_bit || segm_vec)
	{
	  for (i = 0; i < sizeBM; i++)
		if (*(testbitbuf + i)) *(outbitbuf + i) = *(isolbitbuf + i) ;
	}
*/


//	Fill-in objects and get parameters from each 

	t_crown=0, e_crown=0, s_crown=0, j_count=0, isum=0, Total_volume=0.0;

// Creating a list of all objects  (if crown_list_flag says so)

if (crown_list_flag)
{
crown_list = (crown *) malloc(sizeof(crown));
init_rec(crown_list);			// empty crown at top of list
previous_crown  = crown_list;		// previous log is top of list	
}


/* Instead of creating a list of all objects, use the SAME CROWN OBJECT for all logs */

if (! crown_list_flag)
{
	p1 = (crown *) malloc(sizeof(crown));
	init_rec(p1);
}


// For additional safety, create a "zeroed" border around image

	prep_bmp_zero(isolbitbuf, xsize, ysize);

	
	printf("\n\n\tScanning for logs and coarse woody debris ...\n\n");

/* Scanning input bitmap */

for ( i = BORDER ; i < (ysize-BORDER) ; i++ )			// image starts at (1,1)
for ( j = BORDER ; j < (xsize-BORDER) ; j++ ) 
  {

  bitnum = (i-1)*(int64)Pixels + j-1 ;		// bitnum starts at zero

// Find an initial area (two pixels) of debris material 
// Fill that object and record parameters 


 if (   testbit(isolbitbuf, bitnum) &&
		( testbit(isolbitbuf,bitnum+1)
		|| testbit(isolbitbuf,bitnum+xsize) 
		|| testbit(isolbitbuf,bitnum+xsize+1)  
		|| testbit(isolbitbuf,bitnum+xsize-1) ) )
  {


// Create a new object in the list to store individual log info

if(crown_list_flag)
	{
	p1 = (crown *) malloc(sizeof(crown));
	init_rec(p1);
	previous_crown->next_crown = p1;
	}	

//	Initial ifo about log

	t_crown = t_crown + 1 ;					// log number
	p1->init_x = j; p1->init_y = i;					// filling intial positions
	p1->init_East = topleftX + transformX * p1->init_x;
	p1->init_North = topleftY + transformY * p1->init_y;	

//	For debugging PRINT image around test tree log

	//if ( (floor(p1->init_East) == floor(tlog_E)) && (floor(p1->init_North) == floor(tlog_N))) view_around(p1);

	//printf("GOT HERE (L,P) %d %d\n",i,j);

	fill_8c_blob(j, i, p1);		 /* in the INPUT bitmap (also erases in isolbitbuf) */

	//printf("GOT HERE 2\n");	

// Other info about log from the fill()

	x_length = xpixsz * (p1->xmax - p1->xmin +1);		// in metres 
	y_length = ypixsz * (p1->ymax - p1->ymin +1);
	p1->length = sqrt(x_length * x_length + y_length * y_length );	// in metres 
	p1->width = (p1->area * xpixsz * ypixsz) / p1->length; 		// in metres 
	p1->volume = 3.14159 * pow((p1->width/2),2) * p1->length ;
	p1->UTM_East = topleftX + transformX * (p1->xmax + p1->xmin)/2 ;
	p1->UTM_North = topleftY + transformY * (p1->ymax + p1->ymin)/2 ;

//	if(t_crown < 10) printf("\nObject %d : p1->length %.2f p1->width %.2f \n",t_crown,p1->length,p1->width);


/**********************************************************************/

/* REMOVE objects (in output bitmap) based on input criteria */

/**********************************************************************/

/* Length should be LONGER THAN FIVE(5) width to be considered a log or a branch (otherwise erase) */

	if ( !(p1->removed) && (p1->length < (5 * p1->width ) ) )
	  {
	  erase_8c_blob(j,i,p1);			// in outbitbuf
	  e_crown = e_crown + 1 ;
	  p1->removed = 1;
	  /*fprintf(stdout,"Removed Object: %.2f %.2f %.2f %.2f %d %.2f \n ",
				p1->UTM_East, p1->UTM_North, p1->length, p1->width, p1->area, p1->volume); */
	  }

/* Remove objects with inappropriate diameters  (as per input) */

	if ( !(p1->removed) && ( ((int)(100*p1->width)) < diam_thr[0]) || ( ((int)(100*p1->width)) > diam_thr[1]) )
	  {
	  erase_8c_blob(j,i,p1);	
	  e_crown = e_crown + 1 ;
	  p1->removed = 1;
	  /* fprintf(stdout,"Removed Object: %.2f %.2f %.2f %.2f %d %.2f \n ",
				p1->UTM_East, p1->UTM_North, p1->length, p1->width, p1->area, p1->volume); */
	  }

/* Remove (if not done already) objects with inappropriate length (as per input) */

	if ( !(p1->removed) &&  (p1->length < leng_thr[0]) || (p1->length > leng_thr[1]) )
	  {
	  erase_8c_blob(j,i,p1);		 
	  e_crown = e_crown + 1 ;
	  p1->removed = 1;
	  /*fprintf(stdout,"Removed Object: %.2f %.2f %.3f %.3f %d %.3f \n",
				p1->UTM_East, p1->UTM_North, p1->length, p1->width, p1->area, p1->volume); */
	  }


 // PRINT info about LOG RETAINED to plain file 

	if (  !(p1->removed) ) 
			{fprintf(logs_fp,"Log %d: %d %d %.2f %.2f  %.2f %.2f %.3f %.3f %d %.3f \n",
				t_crown, p1->init_x, p1->init_y, p1->init_East, p1->init_North, p1->UTM_East, p1->UTM_North, 
						p1->length, p1->width, p1->area, p1->volume); }

	Total_volume = Total_volume + p1->volume;
	
	}	/* end of 2x2 area loop  */

	s_crown = t_crown - e_crown;	
	
	if (crown_list_flag) previous_crown = p1;		//for next object 
	
    if (! crown_list_flag) init_rec(p1);			// when using SINGLE object (no list) reset object
	
    if( ((i/100)*100 == i) && (j == 3) ) printf(" %d lines done - logs = %d \r", i, s_crown); 

	
  }				/* end main bitmap (test area) scanning loop */
  

//printf("\n*DONE* - %d lines done\n\n", i); 
printf(" %d lines done\n\n", Lines); 

shp_area_ha = (float)shp_area*pix_area/10000;
s_crown = t_crown - e_crown;

printf("\t %d object detected -- %d object removed (not meeting our criteria)\n", t_crown, e_crown);
printf("\t Total object of interest detected : %d in this area of %.2f ha.\n", s_crown, shp_area_ha );

fprintf(logs_fp,"\n\t %d object detected -- %d object removed (not meeting our criteria)\n", t_crown, e_crown);
fprintf(logs_fp,"\t Total object of interest detected : %d in this area of %.2f \n\n", s_crown, shp_area_ha );

Total_area = Total_area + shp_area_ha;
Total_crowns = Total_crowns + s_crown;


/**********************************************************
	Cleans up of junk tree crowns (small and ill-formed)
	*** CAREFUL *** It will clean out of outbitbuf
	everything left in isolbitbuf (not just single pixel items)
************************************************************/


printf("\nCleaning up small debris (less than detectable debris) ... \n");

j_count = 0;

for ( i = 0 ; i < ysize ; i++ )			// here, image starts at zero
for ( j = 0 ; j < xsize ; j++ ) 
  {
  bitnum = (i)*(int64)Pixels + j ;		// bitmap starts at zero

  if ( testbit(isolbitbuf, bitnum) ) 		// if debris left in INPUT bitmap 
    {
    clearbit(outbitbuf, bitnum);		 // CLEAR in the OUPUT bitmap 
    j_count = j_count + 1;
    }
  }

printf("\t %d junk pixels removed \n", j_count);

// Move partial results to final output bitmap

j_count = 0;
for ( i = 0 ; i < ysize ; i++ )			// here, image starts at zero
for ( j = 0 ; j < xsize ; j++ ) 
  {
  bitnum = (i)*(int64)Pixels + j ;		// bitmap starts at zero

  if ( testbit(outbitbuf, bitnum) ) 	
    {
    setbit(outBM, bitnum);		 // copy to final OUPUT bitmap 
    j_count = j_count + 1;
    }
  }

printf("\n\t %d pixels moved to final bitmap\n", j_count);

CONT_LOOP: // some polygon test area may have been outside the image and skipped, cont. for others

	// EXEPTION: Loop to be done "only once" with bitmap-based test areas
	
if(!segm_vec) goto End;	


// }		// end of feature LOOP (when looping separately for each test area of a shp file)


//****************************************************************************
//****************************************************************************

End:

printf("\n************************************\n");
printf("\n		IN SUMMARY \n");
printf("\n************************************\n");

if( (segm_vec + segm_bit) == 0)  Total_area = image_area_ha;

printf("\n*** TOTAL number of objects  of interest detected %d \n", Total_crowns);

printf("\n*** Total area covered is %.2f ha.\n", Total_area );

printf("\n*** Total aprox. volume is %.2f (m3/ha) \n\n", Total_volume/Total_area);


fprintf(logs_fp,"\tLogs with length between %.1f and %.1f m\n",leng_thr[0],leng_thr[1]);
fprintf(logs_fp,"\tAND with diameter between %d and %d cm\n\n",diam_thr[0],diam_thr[1]);
	
fprintf(logs_fp,"\t*** TOTAL number of objects  of interest detected %d \n", Total_crowns);
fprintf(logs_fp,"\t*** Total area covered is %.2f ha.\n", Total_area );
fprintf(logs_fp,"\t*** Total aprox. volume is %.2f (m3/ha) \n\n", Total_volume/Total_area);
	

time (&rawtime); timeinfo = localtime (&rawtime);
fprintf(logs_fp,"\n\tFrom program %s (%s) at %s\n\n", PROG_NAME, VERSION, asctime(timeinfo));
	

//********************************************************************

// Write Output TIF file and information 

//********************************************************************

// Select the driver for the tif output file

	  poDriver = GetGDALDriverManager()->GetDriverByName("GTiff");

	if(poDriver == NULL) 
	   {
	   printf("\n ###Cant find proper driver for this file type %s \n\n", "GTiff"); 
	   exit( 1 );
	   }

// Create a tif file equivalent of a bitmap (NBITS=1)

	fprintf(stdout,"\n\t** Creating file \"%s\" and opened for writing\n\n", file_out);

 	CSLDestroy( papszOptions );
  	papszOptions = CSLSetNameValue( papszOptions, "NBITS", "1" );
    	//papszOptions = CSLSetNameValue( papszOptions, "COMPRESS", "PACKBITS" );

	ima_out = (GDALDataset *) poDriver->Create( file_out, Pixels, Lines, 1, GDT_Byte, papszOptions );

// check that opening worked 

	if (ima_out == NULL) 
	      { printf("\n\n PROBLEM opening output image file %s \n\n", file_out); exit(1); }


// Copy the metadata (GeoTransform, projection, ...)

	fprintf(stdout,"\n* Writing Georef data to outputfile %s\n",file_out);	

	ima_out->SetGeoTransform(adfGeoTransform);
	
	ima_out->SetProjection(ima_in->GetProjectionRef() );		// assuming input bitmap had one
		
	

// Converting "real bitmap" into byte-size image for GDAL output as (nbits=1) tif

//	printf("\n\t* Turning internal bitmap in memory into (nbits=1) tif for output \n\n");

	for ( i = 0 ; i < (ysize) ; i++ )		// image starts at zero
	for ( j = 0 ; j < (xsize) ; j++ ) 
	  {
	  bitnum = (i)*(int64)Pixels + j ;		// bitnum starts at zero
	  if ( testbit(outBM, bitnum) ) (LOGs_BM[i*Pixels+j] = 1);
	  
	  //if ( testbit(outbitbuf, bitnum) ) (LOGs_BM[i*Pixels+j] = 1);	  
	  //if ( testbit(testbitbuf, bitnum) ) (LOGs_BM[i*Pixels+j] = 1);		// to double check on vect2rast() results
	  }


// Write resulting FULL image in one shot (LOGs bitmap)  to output image file

	printf("\n\tWriting selected logs and debris to output bitmap (1bit tif) : %s \n", file_out);

	poBand = ima_out->GetRasterBand( 1 );
	
// Color table	(assumes that the input bitmap has a decent color table)

	//poBand->SetColorTable(piBand->GetColorTable());
	

// Prep an OUTPUT color table (decent for most apps)
		
	GDALColorTable * col_tab_out = nullptr;		// declare output colour table pointer
	col_tab_out =  &GDALColorTable();			// construct output colour table	
	
// Color entries
	
    GDALColorEntry * col_ent_out = nullptr;		// declare
	col_ent_out = &GDALColorEntry();			// construct (i.e., reserve memory)
	
	col_ent_out->c1 = 0; col_ent_out->c2 = 0; col_ent_out->c3 = 0; col_ent_out->c4 = 255;
	col_tab_out->SetColorEntry(0, col_ent_out);
	//col_tab_out->SetColorEntry(1, col_ent_out);		// for TESTING
	
	col_ent_out->c1 = 255; col_ent_out->c2 = 255; col_ent_out->c3 = 255; col_ent_out->c4 = 255;	
	col_tab_out->SetColorEntry(1, col_ent_out);
	//col_tab_out->SetColorEntry(0, col_ent_out);	// for TESTING

// Write Color Table out to bitmap(tif)  file
			
	poBand->SetColorTable(col_tab_out);	
		
// Write description to output bitmap(tif) file

	poBand->SetDescription("Cwd_sfil_g - Logs of interest from debris (used in volume assessment)");
	
// Write resulting FULL image
	
	poBand->RasterIO(GF_Write, 0, 0, Pixels, Lines, LOGs_BM, Pixels, Lines, GDT_Byte,0, 0 );

// Sum all pixels with image (bitmap)

	isum = 0;
 	for (i = 0; i < Lines; i++) 
	  for (j = 0; j < Pixels; j++) 
		isum = isum + LOGs_BM[i*Pixels+j];

	//printf("\n\t\tSum of all bytes (or bits) in image in memory : %d \n\n", isum);

// Print some pixels

/*
	printf("\n\t Some pixels around pixel 4635 line 7950 : \n\n");

 	for (i = 7934; i < 7964; i++) 
	  {
	  for (j = 4620; j < 4650; j++) printf("%d ", LOGs_BM[i*Pixels+j]); 
	  printf("\n");
	  }
*/


	printf("\n\tWriting selected logs to plain text file : Logs_CWD_SFIL.txt\n");


//*********************************************



// Close input and output images

Exit:	printf("\nClosing all files and exiting program. \n");

	GDALClose(ima_in);
	GDALClose(ima_out);



	fclose(logs_fp);		/* close output text files */

time (&rawtime);  timeinfo = localtime (&rawtime);
fprintf(stdout,"\n\n_______________________________\n");
fprintf(stdout,"\n %s (%s) finished at %s\n\n", PROG_NAME, VERSION,  asctime(timeinfo));



} 		// end of main function





/**************************************************************************/

		/* FUNCTIONS */

/**************************************************************************/

/* function to initialize crown records */

void init_rec(crown *p )

{
	 p->area = 0;		/* crown area */
	 p->init_x = 0;			// initial position (x,y)
	 p->init_y = 0;
	 p->init_East= 0.0;		// initial position UTM
	 p->init_North= 0.0;
	 p->xmin = Pixels;	/* diam in both directions*/
	 p->xmax = 0;
	 p->ymin = Lines;
	 p->ymax = 0;
	 p->UTM_East = 0.0;
	 p->UTM_North = 0.0;
	 p->length = 0.0;	
	 p->width = 0.0;
	 p->volume = 0.0;
	 p->removed = 0;	/* flag */

}

/********************************************/

/* This function is a 4-connected recursive fill routine for a crown in a bitmap.
   It is destructive of the object in that bitmap (i.e.: clears bit).
   X goes in pixel direction. Y goes in line direction.   
   It accumulates crown area and min&max in both direction */

void fill_blob(int x, int y, crown *pb)

{
	int64 bitnum;
	bitnum = (y-1)*(int64)Pixels + x-1 ;
	clearbit(isolbitbuf, bitnum);
	pb->area = pb->area + 1 ;
	if( x > pb->xmax ) pb->xmax = x;
	if( y < pb->ymin ) pb->ymin = y;
	if( y > pb->ymax ) pb->ymax = y;
	if( x < pb->xmin ) pb->xmin = x;

	if ( testbit(isolbitbuf, bitnum+Pixels) ) 	fill_blob(x,y+1,pb);
	if ( testbit(isolbitbuf, bitnum-1) ) 		fill_blob(x-1,y,pb);
	if ( testbit(isolbitbuf, bitnum-Pixels) ) 	fill_blob(x,y-1,pb);
	if ( testbit(isolbitbuf, bitnum+1) ) 		fill_blob(x+1,y,pb);
}


/********************************************/
/* This function is an 8-connected recursive fill routine for a crown in a bitmap.
   It is destructive of the object in that bitmap (i.e.: clears bit).
   X goes in pixel direction. Y goes in line direction.   
   It accumulates crown area and min&max in both direction */

void fill_8c_blob(int x, int y, crown *pb)

{
	int64 bitnum;
	bitnum = (y-1)*(int64)Pixels + x-1 ;

	clearbit(isolbitbuf, bitnum);

	pb->area = pb->area + 1 ;
	if( x > pb->xmax ) pb->xmax = x;
	if( y < pb->ymin ) pb->ymin = y;
	if( y > pb->ymax ) pb->ymax = y;
	if( x < pb->xmin ) pb->xmin = x;

	if ( testbit(isolbitbuf, bitnum-Pixels-1) ) 	fill_8c_blob(x-1,y-1,pb);
	if ( testbit(isolbitbuf, bitnum-Pixels) ) 	fill_8c_blob(x,y-1,pb);
	if ( testbit(isolbitbuf, bitnum-Pixels+1) ) 	fill_8c_blob(x+1,y-1,pb);
	if ( testbit(isolbitbuf, bitnum-1) ) 		fill_8c_blob(x-1,y,pb);
	if ( testbit(isolbitbuf, bitnum+1) ) 		fill_8c_blob(x+1,y,pb);
	if ( testbit(isolbitbuf, bitnum+Pixels-1) ) 	fill_8c_blob(x-1,y+1,pb);	
	if ( testbit(isolbitbuf, bitnum+Pixels) ) 	fill_8c_blob(x,y+1,pb);
	if ( testbit(isolbitbuf, bitnum+Pixels+1) ) 	fill_8c_blob(x+1,y+1,pb);
}

/********************************************/

/* This function is a  recursive fill routine for a log in a bitmap.
   It is destructive of the object in that bitmap (i.e.: clears bit).
   X goes in pixel direction. Y goes in line direction.   
   It accumulates crown area and min&max in both direction */

void fill_log(int x, int y, crown *pb)

{
	int64 bitnum;
	bitnum = (y-1)*(int64)Pixels + x-1 ;
	clearbit(isolbitbuf, bitnum);
	pb->area = pb->area + 1 ;
	if( x > pb->xmax ) pb->xmax = x;
	if( y < pb->ymin ) pb->ymin = y;
	if( y > pb->ymax ) pb->ymax = y;
	if( x < pb->xmin ) pb->xmin = x;
	if( (y > 3796) && (y < 3803) && (x > 4624)) printf(" %d %d \n",x,y);

	if ( testbit(isolbitbuf, bitnum+1) ) 		fill_log(x+1,y,pb);
	if ( testbit(isolbitbuf, bitnum+Pixels+1) ) 	fill_log(x+1,y+1,pb);
	if ( testbit(isolbitbuf, bitnum+Pixels) ) 	fill_log(x,y+1,pb);
	if ( testbit(isolbitbuf, bitnum+Pixels-1) ) 	fill_log(x-1,y+1,pb);
	if ( testbit(isolbitbuf, bitnum-Pixels+1) ) 	fill_log(x+1,y-1,pb);
}

/********************************************************/


/* This function is a 4-connected recursively erases a crown from a bitmap.
   X goes in pixels direction. Y goes in line direction.   */

void erase_log(int x, int y, crown *pb)

{
	int64 bitnum;
	bitnum = (y-1)*(int64)Pixels + x-1 ;
	clearbit(outbitbuf, bitnum);
	
	if ( testbit(outbitbuf, bitnum+1) ) 		erase_log(x+1,y,pb);
	if ( testbit(outbitbuf, bitnum+Pixels+1) ) 	erase_log(x+1,y+1,pb);
	if ( testbit(outbitbuf, bitnum+Pixels) ) 	erase_log(x,y+1,pb);
	if ( testbit(outbitbuf, bitnum+Pixels-1) ) 	erase_log(x-1,y+1,pb);	
	if ( testbit(outbitbuf, bitnum-Pixels+1) ) 	erase_log(x+1,y-1,pb);
}



/********************************************/

/* This function is a recursively erases a crown from a bitmap.
   X goes in pixels direction. Y goes in line direction.   */

void erase_blob(int x, int y, crown *pb)

{
	int64 bitnum;
	bitnum = (y-1)*(int64)Pixels + x-1 ;
	clearbit(outbitbuf, bitnum);
	
	if ( testbit(outbitbuf, bitnum+Pixels) ) 	erase_blob(x,y+1,pb);
	if ( testbit(outbitbuf, bitnum-1) ) 		erase_blob(x-1,y,pb);
	if ( testbit(outbitbuf, bitnum-Pixels) ) 	erase_blob(x,y-1,pb);
	if ( testbit(outbitbuf, bitnum+1) ) 		erase_blob(x+1,y,pb);	
}




/********************************************************/
/* This function is a 8-connected recursively erases a crown from a bitmap.
   X goes in pixels direction. Y goes in line direction.   */

void erase_8c_blob(int x, int y, crown *pb)

{
	int64 bitnum;
	bitnum = (y-1)*(int64)Pixels + x-1 ;
	clearbit(outbitbuf, bitnum);

	if ( testbit(outbitbuf, bitnum-Pixels-1) ) 	erase_8c_blob(x-1,y-1,pb);
	if ( testbit(outbitbuf, bitnum-Pixels) ) 	erase_8c_blob(x,y-1,pb);
	if ( testbit(outbitbuf, bitnum-Pixels+1) ) 	erase_8c_blob(x+1,y-1,pb);
	if ( testbit(outbitbuf, bitnum-1) ) 		erase_8c_blob(x-1,y,pb);
	if ( testbit(outbitbuf, bitnum+1) ) 		erase_8c_blob(x+1,y,pb);
	if ( testbit(outbitbuf, bitnum+Pixels-1) ) 	erase_8c_blob(x-1,y+1,pb);	
	if ( testbit(outbitbuf, bitnum+Pixels) ) 	erase_8c_blob(x,y+1,pb);
	if ( testbit(outbitbuf, bitnum+Pixels+1) ) 	erase_8c_blob(x+1,y+1,pb);

}


/**************************************************************/

/* tell whether the first value (a) is between the other two (b,c) */

int between(float a, float b, float c)
{
  if( (c > b) && (a<c) && (a>=b) ) return(TRUE);
  if( (b > c) && (a<b) && (a>=c) ) return(TRUE);
  return(FALSE);
}



/****************************************************************************/


/* This function creates a safety zone around a bitmap for fills() not
   to get out of image array and crash the program */

void safety_zone(unsigned char *bitmap)
{
  extern int Lines, Pixels, Channels;
  int i,j;

  for (j=1, i=1 ; i<=(Lines) ; i++ )	  clearbit(bitmap, ((i-1)*(int64)Pixels + j-1) );
  for (j=Pixels, i=1 ; i<=(Lines) ; i++ ) clearbit(bitmap, ((i-1)*(int64)Pixels + j-1) );
  for (i=1, j=1 ; j<=(Pixels) ; j++ )	  clearbit(bitmap, ((i-1)*(int64)Pixels + j-1) );
  for (i=Lines, j=1 ; j<=(Pixels) ; j++ ) clearbit(bitmap, ((i-1)*(int64)Pixels + j-1) );
}

/**************************************************************/


/*	This is a function to convert a single forest stand from a vector-form (i.e., a polygon) 
	to a filled bitmap stand (using center of pixel in or out as criteria for pixel in or out)
	*****   SERIOUS MODS in FEB 2013 **** should be faster
*/

void vect2rast(int nVertex, GDBVertex *inVertices, unsigned char *mask_data, int xsize, int hShapeId, int set_flag)
  {
  int ii, jj, kk, kkk, x, y, icount, ipos;
  int64 bitnum;
  float xx, yy, xmin, xmax, ymin, ymax, slope, xp;
  int ixmin, ixmax, iymin, iymax;
  float line_xx[MAX_INTERCEPT], line_xp[MAX_INTERCEPT], n_line_xx[MAX_INTERCEPT], n_line_xp[MAX_INTERCEPT];
  GDBVertex *	tmpVertices;
  
  
  Poly_Outside = 0;	// reset global flag about polygon being outside image area


/* Convert geographic coordinates to image coordinates (all vectors of poly) */

  tmpVertices = (GDBVertex *) malloc(nVertex * sizeof(GDBVertex));

  for (kk = 0; kk < nVertex; kk++)
    {
    tmpVertices[kk].x = (inVertices[kk].x - topleftX) / transformX ;
    tmpVertices[kk].y = (inVertices[kk].y - topleftY) / transformY ;
    }


// FOR DEBUG - print vertices in image coordinates

//  fprintf(stdout,"In vect2rast() - Printing some vertices in image coordiantes\n");

//  for (kk=0; kk<nVertex; kk++)
/*
  for (kk=0; kk<12; kk++)
    {
    fprintf(stdout," %d = %8.2f,%8.2f ", kk+1, tmpVertices[kk].x, tmpVertices[kk].y);
    if ( ((kk+1)/4)*4 == (kk+1) ) fprintf(stdout,"\n");
    }
  fprintf(stdout,"\n");
*/

  /* gather x and y minimums and maximums positions of polygon (i.e. bounding square) */

  xmin = xmax = tmpVertices[0].x;
  ymin = ymax = tmpVertices[0].y;

  for (kk=1; kk< nVertex; kk++)
    {
    if (xmax < tmpVertices[kk].x) xmax = tmpVertices[kk].x;
    if (xmin > tmpVertices[kk].x) xmin = tmpVertices[kk].x;
    if (ymax < tmpVertices[kk].y) ymax = tmpVertices[kk].y;
    if (ymin > tmpVertices[kk].y) ymin = tmpVertices[kk].y;
    }

  ixmin = (int) (xmin); iymin = (int) (ymin);	/* round-off on generous side (outside area)*/
  ixmax = (int) (xmax+1); iymax = (int) (ymax+1);

  xcg = (int) (0.5 + (xmax + xmin)/2);	
  ycg = (int) (0.5 + (ymax+ymin)/2);   /* approx center of grav. */


 //   printf("\n Area of interest: xmin,ymin,xmax,ymax = %8.2f,%8.2f,%8.2f,%8.2f\n", xmin,ymin,xmax,ymax); 

//    printf("Area of interest xmin,ymin,xmax,ymax,xcg,ycg = %d  %d  %d  %d  %d  %d\n\n", ixmin,iymin,ixmax,iymax,xcg,ycg); 	
 
/* Disregard this polygon if part of it are outside the image */
 
  if ( (ixmin < 1) || (iymin < 1) || (ixmax > Pixels) || (iymax > Lines) )
	{
	fprintf(stdout,"\n*NOTE*: A part of this polygon is outside the image area.\n");
	fprintf(stdout,"*NOTE*: This polygon will be DISREGARDED in reporting CWD/LOG info.\n");
	Poly_Outside = 1;
	//HFree(tmpVertices);
	return;
	}

/*
		SCAN (line by line) the square area delimited by xmin,xmax,ymin,ymax 
*/

    for(y = iymin; y <= iymax; y++)		/* for each image line of that bounding square */
      {
      icount = 0;
	  yy = (float) y - 0.5;

	/* for the given polygon, check witch line segment intercepts that image line */

	  kkk=0;
	  for (kk=0; kk < (nVertex-1); kk++)	/* for all vertices of polygon */
	    {
	    /* bypass invisible ring connectors  */
	    if ( RingFlag2 && (kk == (RingStart[kkk]-1) ) ) {kk++; kkk++;} 

 	    if ( between(yy,tmpVertices[kk].y,tmpVertices[kk+1].y) )
		  {
		  /* if(y==4257) printf("\nImage line 4257 is cut by vertex %d to %d \n", kk, kk+1); */


		  /* compute X projections of pixel center on that line */ 

		  slope = (tmpVertices[kk+1].y - tmpVertices[kk].y) / (tmpVertices[kk+1].x - tmpVertices[kk].x);

		  /* yp = slope * (xx - tmpVertices[kk].x) + tmpVertices[kk].y; */

		  xp = 1/slope * (yy - tmpVertices[kk].y) + tmpVertices[kk].x;

		  /* if ( y>4250 && y<4260)
			   fprintf(stdout,"\nFor image line = %d  and xp = %8.3f using vector %d,%d \n",y,xp,kk+1,kk+2); */

		  line_xp[icount] = xp;
		  icount++;

		  }	/* end of if between vertices */

	     }	/* end of vertices scanning */

	  /* if( y>4250 && y<4260) fprintf(stdout,"\t For line %d, icount = %d \n", y, icount); */

	if ( icount > MAX_INTERCEPT) 
	  {
	  fprintf(stderr,"\n ### ERROR ### (in vect2ras) \n");
	  fprintf(stderr,"\n Shape %d intercepts an image line %d MORE THAN %d times\n", hShapeId, y, MAX_INTERCEPT);
	  fprintf(stderr,"\n Shape may have a flat line that too long for the software \n\n");
	  exit(-1); 
	  }

	// fprintf(stdout,"\t For line %d, icount = %d \n", y, icount);

	if ( icount == 1) 
	  {
	  fprintf(stdout,"\n ### ERROR ### (in vect2ras) \n");
	  fprintf(stderr,"\tMay have singular point in shape %d \r",hShapeId);
	  fprintf(stdout,"\n OR shape %d in shp layer may not be a closed shape.\n", hShapeId);

	  fprintf(stdout,"\n Start and End X coordinates: %f and %f \n", 
					tmpVertices[0].x,tmpVertices[nVertex-1].x);
	  fprintf(stdout,"\n Start and End Y coordinates: %f and %f \n", 
					tmpVertices[0].y,tmpVertices[nVertex-1].y);
	  exit(-1); 
	  }

/* sort intersection info by increasing xp coordinates */

	for (jj = 0; jj<icount; jj++)
	  {
          xmin = line_xp[0]; ipos = 0;
	  for (ii = 1; ii<icount; ii++) { if (line_xp[ii] < xmin) { xmin = line_xp[ii]; ipos = ii; } }
	  n_line_xp[jj] = line_xp[ipos];
	  line_xp[ipos] = 100000;	/* arbitrary big number for item not to be used */
	  }



/*
	fprintf(stdout,"\t Sort is done \n");
	for (jj = 0; jj<icount; jj++) fprintf(stdout,"\t %f ", n_line_xp[jj]);
	fprintf(stdout,"\n");
*/


/*	Fill between pairs of line intersections.
	Only use the pixel itself ((int)+1) if center of pixel is inside the crown,
	otherwise use the next inside pixel.
	This is implemented via +1.5 on the left and +0.5 on the right.
*/

     for (jj = 0; jj<icount; jj+=2)
	{
	x = (int) (n_line_xp[jj] + 1.5);		/* initial pixel position */
	while( x <= ((int)(n_line_xp[jj+1] + 0.5)) )	/* paint line until next intersection */
	  {
	  bitnum = ((int64)xsize*(y-1)) + x-1;
	  if(set_flag) 
		{ setbit(mask_data,bitnum); shp_area++; }
	  else
		{ clearbit(mask_data,bitnum); shp_area--; }

	  x++;
	  }
	}

     }		/* end of for each line */


/* FOR DEGUGGING 

  fprintf(stdout,"\nRasterized tree crown: \n");
  fprintf(stdout," Covers area xmin,xmax,ymin,ymax = %d,%d,%d,%d\n", ixmin,ixmax,iymin,iymax);

  for(i = iymin; i <= iymax; i++)
   {
    for(j = ixmin; j <= ixmax; j++)
	{
	bitnum = ((int64)xsize*(i-1)) + j-1;
	fprintf(stdout," ");
	if(testbit(mask_data,bitnum)) fprintf(stdout,"X");
	else  fprintf(stdout,".");
	}
   fprintf(stdout,"\n");
   }
   fprintf(stdout,"\n");
*/
	 
  //HFree(tmpVertices);

  /* fprintf(stdout,"Getting out of vect2rast() for shape: %d \n",hShapeId); */

  }	/* end of function */



/****************************************************************************/


// skip code that is not ready 

#if Debug



/*
   This function paints plot boundaries defined as vectors into a plot bitmap
*/

void paint_plot(GDBLayer layer, unsigned char *bitmap, int xsize)

{			
GDBShapeId	hShapeId;
GDBVertex	*pasVertices;
int		nVertex;
int		 j, kk, notclosed, outsideflag;

/* loop to get all shapes within the layer */

  printf("\nPainting vector-defined test areas into a bitmap in memory ... \n\n");      
  
  RingFlag2 = 0;
  notclosed = 0;
  for ( hShapeId = GDBGetFirst(layer);
	hShapeId != GDBNullShapeId; 
	hShapeId = GDBGetNext(layer, hShapeId) )
    { 
    pasVertices = GDBGetVertices(layer, hShapeId, &nVertex);

    printf("\t Shape ID = %d Vertices = %d NorthHemisphere = %d\n", hShapeId, nVertex, North); 

    /* Check for Rings, even for vector layers where the RingStart attribute is not used */
 
    RingStartCount = 0; kk=0;
    for(j=1; j < nVertex-1; j++)
       {

	/* printf("%d   X and Y vertices: %.3f %.3f \n", j-1, pasVertices[j-1].x, pasVertices[j-1].y); */


        if ( (pasVertices[j].x == pasVertices[kk].x) && (pasVertices[j].y == pasVertices[kk].y) ) 
          {
	  RingFlag2 = 1;
	  RingStart[RingStartCount] = j+1;
	  RingStartCount++;
	  kk=j+1; j++;
          }
       }

	  if(RingFlag2) 
	    {
	    fprintf(stdout,"\tThere is(are) %d ring(s) within shape %d starting at : ", RingStartCount, hShapeId);
            for (kk=0; kk<RingStartCount; kk++) fprintf(stdout," %d ", RingStart[kk]+1);

	    // fprintf(stdout,"\nWill avoid vector segments (staying invisible) at : ");
            // for (kk=0; kk<RingStartCount; kk++) fprintf(stdout," %d ", RingStart[kk]);
            // fprintf(stdout,"\n");
	    }


    /* if polygon has no ring as per RingStart attribute (or other check), verify that it is a closed shape */

    	if( !RingFlag2 && ((pasVertices[0].x != pasVertices[nVertex-1].x) 
			|| (pasVertices[0].y != pasVertices[nVertex-1].y) ) )  notclosed=1; 

	/* If multiple polygons within a shape, verify that they are all closed forms */

	if (RingFlag2)
	{
	if( (pasVertices[0].x != pasVertices[RingStart[0]-1].x) 
			|| (pasVertices[0].y != pasVertices[RingStart[0]-1].y) ) notclosed=1;
	// fprintf(stdout,"\n 1 Checking that ring %d from %d to %d is closed\n", 0, 1, RingStart[0]);

	for (kk=1; kk<RingStartCount; kk++)
		{
		if( (pasVertices[RingStart[kk-1]].x != pasVertices[RingStart[kk]-1].x) || 
				( pasVertices[RingStart[kk-1]].y != pasVertices[RingStart[kk]-1].y) ) notclosed=1;
		// fprintf(stdout,"\n 2 Checking that ring %d from %d to %d is closed\n", kk, RingStart[kk-1]+1, RingStart[kk]);
		}
	if( (pasVertices[RingStart[RingStartCount-1]].x != pasVertices[nVertex-1].x) 
			|| (pasVertices[RingStart[RingStartCount-1]].y != pasVertices[nVertex-1].y) ) notclosed=1;
	// fprintf(stdout,"\n 3 Checking that ring %d from %d to %d is closed\n", kk, RingStart[RingStartCount-1]+1, nVertex);
	}

	
	// if(!notclosed) fprintf(stdout,"\n No problems with the %d rings on shape %d \n\n", RingStartCount, hShapeId);
	

	if(notclosed)
	{
	fprintf(stderr,"\n #### WARNING  ### \n");
	fprintf(stderr,"Unable to deal with Polygon (Shape=%d) in vector layer (may not be a closed shape)\n", hShapeId); 
	if (Report != stdout)
	  fprintf(Report,"Unable to deal with Polygon (Shape=%d) in vector layer (may not be a closed shape)\n", hShapeId); 
	fprintf(stderr,"\n ***** Program will exit.\n");
	if (Report != stdout) fprintf(Report,"\n ***** ITCTAS will exit.\n");
	exit(-1);
	}
 
    /* Check if the current shapeID is in the image limits. If so paint it, if not continue to next one */
   
    outsideflag = 0;
    
    for(j=0; j < nVertex; j++)
      {
      /* printf("Outsider check : X and Y vertices: %.3f %.3f \n", pasVertices[j].x, pasVertices[j].y); */

      if ( (pasVertices[j].x <= topleftX) || (pasVertices[j].x >= botrightX) ||
           ( North && ( (pasVertices[j].y >= topleftY) || (pasVertices[j].y <= botrightY) ) )   ||  
           (!North && ( (pasVertices[j].y <= topleftY) || (pasVertices[j].y >= botrightY) ) ) ) 
        {
        outsideflag = 1;
        break;
        }
      }
 
     
    if(outsideflag)
      {
	  fprintf(stderr,"\n #### WARNING  ### \n");
	  fprintf(stderr,"Shape %d considered outside the image area and will be disregarded.\n",hShapeId); 	      
      } 

    if(!outsideflag)
      {
 
      /* paint vector plot to a bitmap */

      //fprintf(stdout,"\n\t* Painting shape %d in raster in memory ... \n", hShapeId);

      vect2rast(nVertex, pasVertices, bitmap, xsize, hShapeId, layer);

	/* HFree(pasVertices);	 free vector storage memory (W7 does not like) */
      } 


    fprintf(stdout,"\n\t* Shape %d painted in raster in memory. \n\n", hShapeId);
    RingFlag2 = 0;

    }			/*end of loop for each sub-plot */

  /* fprintf(stdout,"Getting out of paint_plot() \n"); */
      
} /*end of function */




#endif



/*******************************************************/


/* Put a safety border (CLEAR BIT) around a bitmap in order not to fall off the image (section) */
/* Here, the global variable "bmoffset" (a line offset) is used to work on image sections */
/* xsize and ysize are image (or section) sizes in pixels and lines */

void prep_bmp_zero(PixVal *bmp, int xsize, int ysize)
{
  int     i, j;

  // printf( "\nPreparing bitmap safety border ...\n");

/* upper border */

  for (i = 0; i < BORDER; i++)
  for (j = 0; j < xsize; j++) 
	clearbit(bmp, (bmoffset+i) * (int64)xsize + j);

  //fprintf(stdout,"\n Upper border done at line: %d \n", bmoffset);

/* lower border */

  for (i = ysize - BORDER; i < ysize; i++)
  for (j = 0; j < xsize; j++) 
	clearbit(bmp, (bmoffset+i) * (int64)xsize + j);

  //printf("\n Lower border done at last line: %d at last position %I64d Pixels \n", bmoffset+ysize,(bmoffset+ysize)*(int64)xsize); 

  for (i = 0; i < ysize; i++) 
  { 
	  /* left side */
  for (j = 0; j < BORDER; j++)
	clearbit(bmp, (bmoffset+i) * (int64)xsize + j);

	/* right side */
  for (j = xsize - BORDER; j < xsize; j++)
	clearbit(bmp, (bmoffset+i) * (int64)xsize + j);

  }

}


/**********************************************

/**************************************************************/



/* Put a safety border (CLEAR BIT) around a bitmap in order not to fall off the image (section) */
/* Here, the global variable "bmoffset" (a line offset) is used to work on image sections */
/* xsize and ysize are image (or section) sizes in pixels and lines */

void view_around(crown * p1)
{
	int ii,jj;
	uint64 bitnum2;
	printf("\nFor debug: Printing  BITMAP neighbourhood - Centered on x,y: %d %d \n",p1->init_x,p1->init_y);

   	for ( ii = p1->init_y-10 ; ii <= (p1->init_y+20) ; ii++ )	
	  {
	  printf(" %d  ", ii);
   	  for ( jj = p1->init_x-10 ; jj <= (p1->init_x+10); jj++ ) 
	    {
	    bitnum2 = (ii-1)*(int64)Pixels + jj-1;	

	    if (testbit(isolbitbuf, bitnum2)) printf("X"); else printf(":");
	    }
	  printf("\n");
	  }
	  
}	  
	  
/******************************************************************/
/*******************************************************/