/*
/*
Program name: 	itcca_g.cpp (for GDAL)
Author: 		Francois A. Gougeon
Date:			Sept. 2020 (COVID-19 version)

**********************************
C+
C	ITCCA.cpp		Individual Tree Crown (ITC) Classification Accuracy
C
C	ITCCA determines the classification accuracy of an Individual Tree Crown
C	Classification Process.  A confusion matrix is generated, based on the testing
C	bitmaps that the user specifies and the bitmaps produced from ITCSC as a result of
C	the classification.  The result is a table (matrix) showing both counts of trees
C	and percentages, plus the average accuracy and the overall accuracy.  As well, the
C	counts for unclassified trees is included (percentages and accuracy reflect the
C	presence of the unclassified trees).  The Kappa Coefficient and Kappa Variance
C	is calculated (not including the unclassified trees in the classifications), and 
C	the average crown area of the correctly classified tree crowns is displayed.
C
C
C1	PARAMETERS
C
C
C	ITCCA is controlled by the following global parameters:
C
C	Name		Prompt						Count Type
C
C	FILE		PCI Database File Name				64	Char
C	ISOLBIT		ITC Bitmap from ITCISOL				1	Int
C 	TESTSEG		Testing Area Bitmaps/polygons			16	Int
C	CLASSBIT	Classification Bitmaps				16	Int
C	POSBIT		Pointer Bitmap	(Tree positions)		 1	Int
C	BITBOUND	Boundary ITCs:INC/EXC/AUTO/CGRAV/POINTS		64	Char
C	REPORT		Report Mode: TERM/OFF/filename			64	Char
C
C
C2	FILE
C
C	Specifies the name of the PCIDSK file containing the testing bitmaps
C	and classification bitmaps.
C
C	EASI>FILE="filename"
C
C2	ISOLBIT
C
C       Specifies a bitmap produced by the ITCISOL (Individual Tree Crown
C       Isolation) program to be used as a mask of the image.  This bitmap
C       will be used along with the CLASSBITs to construct a bitmap of the
C	unclassified tree which will be used to construct the confusion matrix.
C
C	EASI>ISOLBIT=n
C
C2	TESTSEG
C
C	Specifies the list of Testing segments (bitmaps or vector layers) to be used
c	to test an ITC classification (one TESTSEG per species)
c	The bitmaps generally contain filled areas from homogeneous stands, or for mixed 
c	stands, filled individual tree crowns that are "known" trees of a given species.
c
C	One testing bitmap(or vector layer), that may contain more than one test area
c	(HINT: spread them all over your image for results to be more representative),
c	is used per species (class) and compared against the classification results for 
c	that species (class), thus, building up the confusion matrix leading to the 
c	estimation of classification accuracy.
C
C	EASI>TESTSEG=n,n,n...
C
C2	CLASSBIT
C
C	Specifies a list of Classification Bitmaps. These are bitmaps that were
C	generated by the ITCSC program as a result of ITCs classification.
C	One bitmap is specified per species, showing the ITCs classified into that 
C	species. This is compared against the Testing areas (TESTSEG) in order
C	to generate the confusion matrix leading to the estimation of classification 
c	accuracy.
c
C	EASI>CLASSBIT=n,n,n...
c
C2      POSBIT		Pointer Bitmap	(Tree positions)
C
C       Specifies a segment which contains a tree position Bitmap. Only used here
c	in the BITBOUND=POINTS mode, where the POSBIT bitmap points to the tree crowns
c	that should be considered for the classification accuracy assessment.
C
c	EASI>POSBIT=n
c
C2      BITBOUND
C
C       Possible values: INC / EXC  /AUTO / CGRAV / POINTS
c	(Inclusive or Exclusive or Automatic or Center_of_gravity or Pointers).
C
C	EASI>BITBOUND="value"
c
C       Specifies whether tree crowns that fall on the boundary of Testing
C	Bitmaps (or polygons) should be included (INC) or excluded (EXC), or have their
c	insertion decided upon automatically (AUTO) based on having 50% of their crown 
c	area inside the area, or based on their "center of gravity" (stem?) being 
c	inside (CGRAV) the training (testing) area.
C	POINTS is a separate case in which the POSBIT bitmap contains pointers
c	to the tree crown to consider.
C
C       Inclusive:
C                   o	All crowns that have at least 2x2 pixels inside the training
c					(testing) area are included in the output.
c
C       Exclusive:
C                   o	Crowns that are only partially in the training (testing) area
c					(trees on area boundaries) are disregarded (generally).
C                   o	Exception: If a tree less than 10% of its crown area
c					sticking out of the testing area, it is considered IN.
c
c	Automatic
c                  o	Crowns are included in the output if more than 50% their crown
c		    		area is inside the training (testing) area.
c
c	CGRAV
c                  o	Crowns are included in the output if their center of gravity
c					(tree stem?) is inside the training (testing) area.

c	POINTS
c                  o	Crowns are included in the output if their is a pointer
c					(a set pixel) in POSBIT that points to the crown.
c					o	If this is the case, the full crown content is used
c					independent of the size of the pointer.
C
C2	REPORT
C
C	Specifies the file to which the generated report should be appended.
C
C	EASI> REPORT = "filename"
c
c	Note:  The following names have special meaning:
c
c	EASI> REPORT = "TERM"	| generates reports on your terminal
c	EASI> REPORT = "DISK"	| generates reports on file "IMPRPT.LST"
c	EASI> REPORT = "OFF"	| (may) switch off report generation
C
C1	DETAILS
C
C	ITCCA
C
C       ITCCA determines the classification accuracy of an Individual Tree Crown
C       Classification Process.  A confusion matrix is generated, based on the testing
C       bitmaps that the user specifies and the bitmaps produced from ITCSC as a result of
C       the classification.  The result is a table (matrix) showing both counts of trees
C       and percentages, plus the average accuracy and the overall accuracy.  As well, the
C       counts for unclassified trees is included (percentages and accuracy reflect the
C       presence of the unclassified trees).  The Kappa Coefficient and Kappa Variance
C       is calculated (not including the unclassified trees in the classifications), and the
C       average crown area of the correctly classified tree crowns is displayed.
C
C
C2	GENERAL PROCESS (may not be up-to-date)
C
C	The following general procedure is followed by ITCCA:
C
C	The bitmap masks are read into memory from the specified input file.  These masks
C	include the bitmaps produced from the ITCSC program as a result of classification
C	(CLASSBIT) and a set of testing areas (TESTSEG).  The ISOLBIT is also loaded in
C	and along with the CLASSBITs, used to construct a bitmap of the unclassified trees.
C
C	The test area then compared, 2 at a time (1 from TESTSEG and 1 from CLASSBIT)
C	with all combinations being looked at. The unclassified bitmap is also considered
C	along with the CLASSBITs.  These two bitmap masks are ANDed together so that they
C	form a fourth bitmap mask which is used for processing.
C
C	The new mask is scanned and the number of trees that are found to be contained
C	in that mask are recorded in a matrix.  As well, we keep track of the number of
C	pixels that make up crowns that have been correctly classified.  This will be used
C	to form the average crown area of the crowns.  When processing the bitmap masks,
C	the value of BITBOUND is considered here.  If INC is specified, all partial trees
C	are considered, while EXC causes partial trees to be rejected.  After all
C	combinations of CLASSBITs and TESTSEGs have been looked at we have a complete matrix
C	of sums of trees.  The horizontal "axis" of the matrix lists the ground truth
C	classes, while the vertical axis lists the thematic (classified) classes.  This
C	is our confusion matrix.
C
C	The total number of trees in each column are summed, and as well, the grand
C	total of the trees is formed.  Each entry in a column is also calculated as a
C	percent of the number of trees in a column entry over the total number of trees
C	in the column.  The numbers on the main diagonal represent the accuracy of the
C	classification in classifying the individual species.  One extra row of the matrix
C	represents the unclassified trees.  The percentages and totals reflect the addition
C	of the unclassified trees in the matrix.  The percentages of the diagonal elements
C	are averaged to form the Average Accuracy.  As well, the number of trees on the
C	main diagonal are summed.  This value is divided by the total number of trees to
C	form the Overall Accuracy.  Using the entries in the confusion matrix (without the
C	unclassified row) the Kappa Coefficient and Kappa Variance is generated.  The
C	confusion matrix, and accuracies are displayed.  As well, the average crown area
C	of the trees that were correctly classified (those represented on the main diagonal
C	of the matrix) is displayed in both pixels and in a units measure (eg:  Sq Metre).
C
C
C2	BITMAP MASKS AND BOUNDARIES 
C
c	**** NOT up-to-date relative to BITBOUND
c
C	Three different types of bitmap masks are used by ITCCA.  The first kind is a
C	series of testing bitmaps (TESTSEG) which have been constructed by the user.  This
C	can consist of a filled region (all trees contained in the region), filled tree
C	crowns (an individual tree), or individual points (also indicating individual
C	trees to be considered).
C
C	The second kind of bitmap are the bitmaps that we generated by the ITCSC program
C	(CLASSBIT).  These bitmaps are the results of the classification based on the
C	generated signatures.  Each bitmap in the set represents the results of a single
C	species classification.
C
C	The third kind of bitmap is the ISOLBIT which is from the Individual Tree Crown
C	Isolation program.  This is used along with the CLASSBITs to build a bitmap of
C	the unclassified tree crowns.
C
C	Together, for each pair of bitmaps (1 from TESTSEG, 1 from CLASSBIT) two bitmaps are
C	ANDed together bitwise to form a fourth bitmap.  The unclassified bitmap is
C	also considered with the CLASSBITs in the process.  This bitmap is then scanned and
C	all the trees contained in the bitmap are recorded in the confusion matrix.  Once
C	all combinations have been scanned, we have the information for our complete
C	confusion matrix, and we can do additional calculations on the data.
C
C	When the fourth bitmap is scanned the BITBOUND value is considered.  Possible values
C	for BITBOUND include INC or EXC.  If INC is specified this indicates an "inclusive"
C	border on the TESTSEGs.  That is trees which are partially in a region (but not
C	entirely) are included in the confusion matrix calculations.  If EXC is specified,
C	partial trees are rejected for confusion matrix calculations.  Generally, the
C	following should be considered:
C
C
C2	CONFUSION MATRIX
C
C	Once all the data from the bitmaps has been collected, we have a confusion
C	matrix with the sum totals of trees.  The horizontal "axis" of the matrix lists
C	the ground truth classes (our testing areas) while the verical axis lists the
C	thematic (classified) classes.  The total number of trees in each column are
C	summed.  Percentages are calculated for each element in the matrix as a ratio of
C	the number of trees divided by the total number of trees in the column.  The
C	last row of the confusion matrix represents the totals for unclassified tree
C	crowns.  The totals, and percentages are affected by the unclassified results.
C
C	The numbers down the main diagonal represent the accuracy of the classification
C 	for the respective individual species.  We average these percentages to form the
C	Average Accuracy.  The total number of trees on the main diagonal are summed and
C	is expressed as a ratio with the total number of trees in the matrix.  This is
C	the Overall Accuracy.  As well, the confusion matrix totals (without the
C	unclassified crowns) are used to form the Kappa Coefficient and the Kappa Variance.
C	The average crown area of the correctly classified crowns (those on the main
C	diagonal) is also displayed.
C
C
C3	HISTORY
C
c	Francois A. Gougeon, Ph.D.
c	Digital Remote Sensing Research
c	
c	Dept. of Natural Resources (C)
c	Canadian Forest Service 
c	
c	Pacific Forestry Centre
c	506 West Burnside Rd.
c	Victoria, British Columbia, 
c	Canada, V8Z 1M5
c	
c	Revision History:
c
c  Ron Petrick (at PNFI)
c    Version 0.9 September 1994		Prog. creation (concept Francois Gougeon)
c    Version 1.0 November  1994		ANSI C Conversion, upgrade to PCI V5.3
c
c V1.1	Dec.1996	 Simon Alexander (at PFC)  	
c
c					Converted to handle 16bit images,clean up
c					memory handling, start made on
c					integrating itc suite.
c 
c V1.2	Jan-Feb 97	Fran�ois A. Gougeon
c
c			Various cleanups of old code and debugging,
c			change in parameters nomemclature and handling
c
c v1.3	March 97	Fran�ois A. Gougeon	
c
c			Improved look of confusion matrix
c
c v1.4	April 97	Fran�ois A. Gougeon	
c
c			Fixed a bug with loop bitmap size ((+7)/8 not 
c			for each line)
c
c v1.5	May 97		Fran�ois A. Gougeon		
c
c			To speedup by using macros instead of functions
c			for bit operations and 2x2 detection of minimun
c			crowns
c
c v 2.0	July 98		Fran�ois A. Gougeon	
c
c			-Introduced more BITBOUND options. Now we have:
c				INC/EXC/AUTO/CGRAV/POINTS
c			thus introduced EXTBIT for POINTS mode
c			-Various clean up, so more appropriate counts
c
c v2.1 Oct 2001		Geoff Savinkoff		
c
c			- Added global variables Lines, Pixels
c
c	Dec 2001	- Updated help file with linking information and EASI prompts
c			- Replaced most IDB functions with GDB functions (Not IDBPixelSize as 
c			     there is no equivelant GDB function).
c			- Defined xsize, ysize, channels as local variables to pass to functions to be
c			  consistent with other programs.
c			- Updated to display time at start and end of program
c			- Added georeferencing information with GDBGeorefIO
c
c
c v2.2	April-May 2007	Fran�ois A. Gougeon
c
c				- Minor adaptations for PCI v10 and its new PRM.PRM file 
c				  Most PCI routines are in PCI1000.dll, but not all.
c				  For example, IMPTime() and IMPReturn() are now in Core1000.dll
c				  and IMPCounter() in Counter1000.dll
c				  Since I dont have PCISDK or PCIProSDK, I had to create LIBs 
c				  from their DLLs to compile my progs.
c
c				  Also, problem with the REPORT (*Report) Variable
c
c
c v2.3	Sept. 2007	Fran�ois A. Gougeon
c
c				- Updated to take georeferenced polygons in vector layers (one per class)
c				instead of only taking only bitmaps as test areas to check classification.
c				PCI parameter TESTBIT is now called TESTSEG to reflect that change.	
c
c v2.4	July 2008	Fran�ois A. Gougeon
c
c				- Changed EXTBIT to POSBIT to reflect its real nature and to avoid confusion
c				during ITC analyses between the EXTBIT in ITCSSG and ITCSC (typically, a lit mask)
c				and a pointer bitmap (pointing to crowns to use)
c	
c
c v3.0	July 2009	Fran�ois A. Gougeon
c
c				- Modified to deal with huge images (bitmaps in this case).
c				  Major change to the architecture of the program.
c				  It implies much more disk access, as bitmaps are read many times (as
c				  opposed to once in previous version), but it needs less memory.
c
c v3.1	Aug 2009	Fran�ois A. Gougeon
c
c				- Modified to accept "short hand" notation on TESTSEG and CLASSBIT,
c				  which also implies that up to 32 classes can now be assessed.
c				  For example:	CLASSBIT= 24,-27,47,-51
c
c v3.2	Oct. 2009	Fran�ois A. Gougeon
c
c				- Modified to remove unnecessary use of "double" instead of "float".
c
c v3.3	Dec. 2009	Fran�ois A. Gougeon
c
c				- Modified to switch automatically between a mode for small images (as in versions
c				previous to v3.0 that were doing it all in memory) and a mode for big images (v3.n),
c				based on "whether or not" your Windows NT computer has at least 2GB of memory available
c				to run applications. In small image mode, test areas and classes bitmaps are read 
c				only once at the beginning of the program, making it faster.
c
c v3.4	 July 2010	Fran�ois A. Gougeon
c
c				- Making better decision on using "small image mode" based on the
c				  amount of memory that the computer actually has at its disposal.
c				- The user can now impose the quantity of total memory to use (within XP 
c				  limits, at the moment) using the new ITC/PCI environment variable named
c				  ITC_MEM (specified in GB, e.g.: ITC_MEM = 2.5). 
c				  If not already in DEFITC.EAS,
c				  use the following line to define the new PCI env. vars. :
c				  define ITC_MEM=n,1.0,3.0,-1,"Memory to use (in GB) according to user"
c				- Capable of dealing with FILENAME (thus path) up to 132 chr long. as per 
c				  new standards (PCI > v10.n)
c			
c v3.5	 Jan. 2012	Fran�ois A. Gougeon	
c
c				- Modified to handle bitmaps bigger than 2G positions by reading them
c				in two sections (i.e., the old PCI functions that I have access to
c				are not up to part yet). Itc_io.c was modified to take care of that.
c				- Bitops.c was also modified to use int64 vars to use with pointers 
c				for operations on bitmaps. Calls to setbit(), testbit(), etc.
c				have to be modified to use an (int64) pointer, typically by casting.
c				- Thus, "bitnum" need to be declared "int64 bitnum" everywhere
c				- Be careful of parenthesis as they may prevent "auto casting" to int64
c				from working (i.e., calculation gets done in int32, then cast to int64
c				with bad results. For exemple:
c				"bitnum = (int64) ((y-1)*Pixels) + x-1;" 
c				should be: "bitnum = (y-1)*(int64)Pixels + x-1;"
c
c v4.0	April 2016	Fran�ois A. Gougeon
c
c			- Changed to a C++ program to deal with versions of PCI > v10.2
c			     int main (), ".cpp" name, and extern "C" around .h include files
c			- mod to some call to fit new library definitions (as per .def demangling)
c			  which also means mods to corresponding declaration .h files (e.g., gdb.h)
c			  (Since I dont have PCISDK or PCI/ProSDK, I have to create LIB and DEF from
c			  from their DLLs (via DUMPBIN and LIB) in order to compile my progs
c			- modules in files like gdb.h need to be declared 'extern "C++" to link
c			  with proper name mangling (MSVC++ mangling)
c			- ***WORKED**  for PCI 10.3 that migrate its LIB to c++, 
c
c			- HOWEVER, more stuff is needed for PCI 2015 (64bit)
c			- PCI LIB need to be /MACHINE:x64 
c			  and prog compile with 64b version (i.e., vcvarsall amd64)
c			  cause all the call to lib are now with 64bit pointers 
c			- IMPStatus()  uses "char const *"
c
c v4.1	Sept 2016	 Fran�ois Gougeon	
c
c
c			- "bmsize" needs to be (int64) everywhere to deal with bitmaps > 2GB
c			- also, loop counters (iii) relative to copying bitmap (i.e., bmsize)
c
c v4.2	Dec 2016	 Fran�ois Gougeon	
c
c			- ITCCA (in CGRAV and INC mode) could consider ITC remnants when an ITC was folding back
c			  into the test area leaving a blob in the "andbuffer" with no corresponding ITC anymore
c				Check:  // test if ITC not used already (i.e., erased)
c			This does not affect the other modes as they have to compare size in/out to decide
c
c
c v5.0a		Sept. 2020	Fran�ois Gougeon
c
c			- Mod for GDAL and tif and shp files (from PCI v4.2)
c
c			Note: To check memory usage, enable "Ok to continue" and use
c			> tasklist /fi "imagename eq itcca_g.exe"    in another cmd window
c
c
c v5.1a		May 2021	Fran�ois Gougeon
c
c			- Modified program for complete independence from the PCI environment (no call to lib)
c			- Given modern computer's capabilities, working by image sections has been removed
c			- If ever needed, you may pick it up from the PCI version of the program, 
c			but you need to modify that part for GDAL
c			- Introduced more flexibity to specify input files, specially training area files
c
c
c Fran�ois Gougeon  v5.2a		May 2023
c
c			- NOT to assume that all files are in the default directory from which the program is run ANYMORE
c				Previously, everything was assumed in same directory and run from a cmd window from there.
c				NOW, 
c				the **path used with the main input file** is used when creating the default input/output file names
c				This was necessary for ArcGIS Toolkit integration.
c
c
c Fran�ois Gougeon  v5.3a		Nov-Dec 2024  
c
c			- Introduces more flexibiity for training areas and classes filenames
c
C			- Deals better with default input param such as AUTO (now "-" or "#" acceptable)
c
c 			- Waits after error messages (before exiting ) for ArcGIS users not to miss message
c
c			NOTE:	Range of style 6-13 (rather than 6,-13) are now acceptable
c
c
c Fran\E7ois Gougeon  v5.4		Aug. 2025
c
c       - To deal with Linux use of "slash" versus Windows "backslash", 
c           finally realizing that Windows can do both, so program for "slash"
c           and using path_len rather than jj
c			
c
C-
c  Dependencies: ***OLD ***
c	
c  This program runs under the PCI EASI/PACE Image Analysis System.
C	EASI/PACE is a copyright of 	PCI Inc., 50 West Wilmot St., 
C					Richmond Hill, Ontario, Canada
c
c	Libraries:	pci.a   	(PCI EASI/PACE)
c			libm.a		(Standard Math Library)
c	
c	Includes:	pci.h		(PCI EASI/PACE)
c			string.h	(Standard C string header file)
c			math.h		(Standard C math header file)
c 			itc_io.h	standard itc suite I/O routines
c 			bitops.h	to use macros for bit operations instead of functions,
c					 to speed up (less pushing and poping)
c
c
c  Linking information (or use the Makefile)
c
c	gcc -c -O -I/package/pci7.0/lib  -o itcca.o itcca.c
c	g++ -O -o ./exe/ITCCA.EXE itcca.o itc_io.o error.o
c				   /package/pci7.0/lib/pci.a -lm -lsocket -lnsl -ldl
C



*** To compile with Visual Studio (VS14)  (see VS14_GDAL_compile.txt)

call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

set INCLUDE=C:\gdal-2.1.1_v2\include;C:\libtiff-4.0.6_64b\tiff-4.0.6\libtiff;%INCLUDE%
set LIB=C:\gdal-2.1.1_v2\lib;C:\libtiff-4.0.6_64b\tiff-4.0.6\libtiff;%LIB%

set LINK=gdal_i.lib  libtiff_i.lib User32.lib

set CL= /MD

CL xxxxxxxxx.cpp /EHsc

***********************************************

NOTE: Newest GDAL library have included "libtiff" no need to have it anymore

set INCLUDE=D:\GDAL_3.0.0\include;%INCLUDE%
set LIB=D:\GDAL_3.0.0\lib;%LIB%
set LINK=gdal_i.lib  libtiff_i.lib User32.lib
set CL= /MD
CL xxxxxxxxx.cpp /EHsc

set path=D:\GDAL_3.0.0;%PATH%		// to run programs

***  GDAL v3.0.0 has problem getting to its projection library, so do:

set PROJ_LIB=D:\GDAL_3.0.0\projlib



*********************
Ackowlegment to GDAL:

GDAL - Geospatial Data Abstraction Library: Version 2.1.1 (July2016, 64bit), 
GDAL - Geospatial Data Abstraction Library: Version 3.0.0 (Dec. 2019, 64bit),
Open Source Geospatial Foundation, 
Thanks Frank (Warmerdam)


*******************************************************************************************
******************************************************************************************

c
c	PROGRAM USAGE
c
c
c	> itcca_g BaseFilename ISOLBIT TESTSEG  CLASSBIT BITBOUND

	where "basefilename" is typically the main tif file contaninng the image (but not used)
	Here, it is just used to create the proper prefix for ISOLBIT, TESTSEG and CLASSBIT files
	ISOLBIT is a bitmap of ITC delineated tree crowns, typically called BFname_ITC.tif
	TESTSEG  can be bitmap or vector layer test areas (or a combination) (e.g., BFname_BM13.tif BFname_VEC2.shp)
	CLASSBIT files are bitmaps resulting from an ITC classification with ITCCA_G
	BITBOUND is as per PCI definition above. POINTS mode is not implemented yet.above 

	> itcca_g SECTEUR_IRGB.tif 7  10,-12 16,-18 AUTO 
		Will use SECTEUR_BM7.tif as ITC bitmap.
		Will use SECTEUR_BM10.tif to BM12 *OR* VEC10 to Vec12 as testing areas
		will use SECTEUR_Class16.tif to Class18 as bitmaps from classification

	> itcca_g SECTEUR_IRGB.tif SECTEUR_ISOL.tif 12,-14 1,-3 

	> itcca_g SECTEUR_IRGB.tif ITC 12,-14 1,-3 

		Will use SECTEUR_ITC.tif as ITC bitmap.

	> itcca_g SECTEUR_IRGB.tif ITC Secteur_VEC.shp,12,-14 1,-3 

	Test areas are : Secteur_VEC12.shp Secteur_VEC13.shp Secteur_VEC14.shp

	>itcca_g SECTEUR_IRGB.tif ISOL Secteur_VEC.shp,13,2 1,-2

	Test areas are : Secteur_VEC13.shp and Secteur_VEC2.shp 

	Class bitmaps are : Secteur_Class1.tif and Secteur_Class2.tif
	
	
	Both test areas and class filenames can be explicit (if different from our convention)
	
 	> itcca_g PRF_ADS_19x9km.tif PRF_NIR_ISOL.tif PRF_nnnn.shp,6,-13 PRF_xxx.tif,1,-8


	
*************************************************************************
*************************************************************************
*/

//#define PARTIAL_GDAL	1	// still in the process of converting, thus some PCI lib still needed
							// ALSO, important to resolve conflicts between gdb.h and itc_io_g.h
							// about GDBVertex


#define VERSION "v5.4"
#define PROG_NAME "ITCCA"
#define FILENAME    132
#define BITMAPS     32
#define MAX_INTERCEPT 100


#ifdef PARTIAL_GDAL
extern "C" {
#include "pci.h"
#include "itc_io.h"
#include "bitops.h"
}
#endif

/* 
#include "ogr_api.h"
#include "ogr_srs_api.h"
//#include "commonutils.h"
#include "cpl_port.h"

#include <stdarg.h>
#include <stddef.h>
 */

#include <stddef.h>		// standart C inclusions
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <limits.h>
#include <time.h>       // time_t, struct tm, time, localtime

//#include "gdal_priv.h"		// For GDAL library
//#include "ogrsf_frmts.h"	// For OGR


#include "ITC-Suite_g.h"		// my newest GDAL variable setup
#include "itc_io_g.h"		// my newest GDAL image/bitmap input/output
#include "bitops.h"		// bit operations on bitmaps (mostly macros to be faster)




/* function declarations */

void check_parameters(char *);
void fill(int, int, int, unsigned char *, int *);
void fill_cg(int, int, int, unsigned char *, int *);
void scan_for_tree(unsigned char *, unsigned char *, int, int, char *, int, int);
void scan_for_tree_inc(unsigned char *, unsigned char *, int, int, int, int);
void scan_for_tree_exc(unsigned char *, unsigned char *, int, int, int, int);
void scan_for_tree_auto(unsigned char *, unsigned char *, int, int, int, int);
void scan_for_tree_cgrav(unsigned char *, unsigned char *, int, int, int, int);
void scan_for_tree_points(unsigned char *, unsigned char *, int, int, int, int);

//void paint_plot(GDBLayer, unsigned char *, int);
//void vect2rast(int, GDBVertex *, unsigned char *, int, GDBShapeId, GDBLayer);

PixVal 	*vector2bitmap(char *, int);
void 	vect2rast_g(int, GDBVertex2D *, unsigned char *, int, int, int);



//int  between(float a, float b, float c);		// now in itcio_g.cpp
void process_matrix(void);
//void view_matrix(FILE *, int, char *);
void view_matrix(int, char *);
void upper_case(char *);
//void read_testseg(int);
void param_expand(int, int *,  int *, int *);

// Global variables

int		confusion_matrix[BITMAPS + 1][BITMAPS];
float           sum_cols[BITMAPS];
int		pix_count[BITMAPS];
float           totsum, overacc, avgacc, kappa, varkappa;
int             nclass, ntest;
int             blocks;
int64		bmsize;
int		Pixels, Lines, Channels;
//float		xpixsz,ypixsz;
char		pixunit[40], timedate[17];
int		sum_x, sum_y;
int		PointMet, pointmode=0;

GDBVertex	*tmpVertices;
unsigned char	*ext_mask;
char		geosys[17];
double		topleftX, transformX, topleftY, transformY;

int             isolbit, extmask=0;
int             itestseg[BITMAPS], testseg[BITMAPS];
int             iclassbit[BITMAPS], classbit[BITMAPS];
FILE           *idb_fp, *tas_fp, *class_fp;
char		segflag, segname[9];
long 		start, length;
//int 		segtype;
int 		TA_segtype[BITMAPS];
int			small_ima = 1;				// flag is ON when working in small image mode (all in memory)
int				ixmin, ixmax, iymin, iymax;
int				xcg, ycg;		/* center of gravity (aprox.) of current man tree */

unsigned char  *classbuffer, *testbuffer, *classbitbuffer;
unsigned char  *andbuffer, *isolbitbuffer, *unclassbuf;
unsigned char  *classbitbuf[BITMAPS + 1], *testbitbuf[BITMAPS];

char 		Extension[10]="";

FILE *Report;    /* To compensate for "faulty" Report variable from core1000.dll */


// Global variables to read images, bitmaps and vector layers with GDAL (Specially with itc_io_g.cpp)

GDALDataset	*ima_in, *ima_out, *seg_in, *poDS;
GDALDriver 	*piDriver, *poDriver;
GDALRasterBand	*piBand,*piBand2,*poBand;

//OGRLayer    *psLayer, *poLayer; 		//poLayer & poFeature are only used when creating a separate output shp file
//OGRFeature 	*piFeature, *poFeature;
//OGRFeature 	*gpiFeature, *gpoFeature;		// usefull to pass Feature pointer to other function (was a test)
OGRFeatureDefn	*piFDefn, *poFDefn;
OGRFieldDefn	*piFieldDefn;
OGRFieldDefn	*poFieldDefn;

OGRSpatialReference *piSRSIn,  *poSRSIn;
OGRGeometry 	*piGeometry, *poGeometry;

PixVal		*pafScanline;
uint16		*pafScanline16;

char **papszOptions = NULL;
char **papszMetadata;

float		xpixsz, ypixsz;
char 		*Proj, *Proj2, *Datum, *Datum2, *Temp,*token;
double		adfGeoTransform[6], adfGeoTransform2[6];

char 	 	description[128];		// for PCI
char 	 	Description[128];		// for GDAL via write_bitmap()

int 		ch_in, ch_out, in_ch[10], segm_in, in_segm[10];
int			imaFile_opened;

int			bylines_flag;			// default is to read/write by image (faster),
int	by_lines=0, by_image=1;			// default is to read/write by image (faster), 

//int 	BM_ERR=0, VEC_ERR=0;
//int	SEG_BIT=101, SEG_VEC=116;		//PCI nomemclature

int		data_type;			// need to be global	
//int		segtype[32];
int    sp_indx = 0 ; 			//temp for debugging
int 	class_field;


// MAIN PROGRAM 

int main(int argc, char *argv[])
{

/* var list */

int      i, j, k, ii, jj, kk;
int64	iii;
int     mask1, mask2;
int		xsize, ysize, channels;

char            boundtype[64];
char            report[FILENAME];
void           *args[7];
int             argcnt[7];
int64			mem_needed,  mem_avail_SYS;
float			numbuf[1];
int				actval;


char 	filename[FILENAME], temp[FILENAME], temp2[FILENAME], fullfilename[FILENAME];
char	file_ITC[FILENAME], file[FILENAME], given_fname[FILENAME];

char 	file_TAS[BITMAPS][FILENAME];
char 	file_CLASS[BITMAPS][FILENAME];
int 	name_given = 0;		// flag if base name was given for testing areas
char 	*file_in, *p;
char	ext[4], seg_no[3];

		
char	basefilename[FILENAME], shpfilename[FILENAME], clsfilename[FILENAME];
char	basefname[FILENAME];		// use more for temp names
int		basef_len;	
char	path[FILENAME], main_path[FILENAME], tst_path[FILENAME], cls_path[FILENAME];

int 	path_len, main_path_flag, tst_path_flag, cls_path_flag;	
int 		PCI_File = 0;			// initial flags for image file type
int 		TIF_File = 0;
char 	*pt;			// a generic char or string pointer
	
	
time_t 	rawtime;
struct 	tm * timeinfo;
char	answer[40];

// assign PCI parameter pointers to argumnets 

/*
args[0] = (void *) file;
args[1] = (void *) &isolbit;
args[2] = (void *) itestseg;
args[3] = (void *) iclassbit;
args[4] = (void *) &extmask;
args[5] = (void *) boundtype;
args[6] = (void *) report;

// setup standard interface

IMPStatus("FILE, ISOLBIT, TESTSEG, CLASSBIT, POSBIT, BITBOUND, REPORT;",
		  "C,    I,       I,       I,        I,      C,        C;",
		  "132,  1,       16,      16,       1,      64,       132;",
		  "1,    1,       1,       1,        0,      1,        0;",
		  "ITCCA.", "FORCE", argcnt, args, argc, argv);
*/

/* To compensate for "faulty" Report variable from core1000.dll */

//if(EQUALN(report,"TERM",4)) {Report=stdout;}else{Report = fopen(report, "w");} 

	Report = stdout;

// ****************************************************************************

// Print Program Header 

	time (&rawtime);  timeinfo = localtime (&rawtime);
	printf("\n\t\tStarting %s (%s) at %s\n", PROG_NAME, VERSION, asctime(timeinfo));

// Registers for all types of files with GDAL

	GDALAllRegister(); 	

// ***************

// Check arguments on command line


	if (argc < 5) 
	  {
	  printf("\n\t *** PROBLEM with INPUTS parameters \n");
	  printf("\nUSAGE:  itcca_g BaseFilename ISOLBIT TESTSEG  CLASSBIT BITBOUND\n");
	  printf("\n\nRead the error message before program exits   ..."); 	// for user time to read when using ArcGIS
	  answer[0] = getc(stdin); 		// gets any answer or plain <CR>
	  exit(-1);
	  }   


// ***************

Arg1:

// Check *First argument* on command line

// OPEN image FILE  and get info (needed for input parameteers checking)
// Will report if PCI or TIF file

	strcpy(filename, argv[1]);
	
	ima_in = open_imaFile(filename);		// OPEN  image file (PCI or TIF) and get info about it
	
	xsize = Pixels; ysize = Lines;			// use throughout program
	
	//dbiw[0]=0; dbiw[1]=0; dbiw[2]=Pixels; dbiw[3]=Lines;		// for analysis by full image 
	
	bmsize = (Pixels * (int64)Lines + 7) / 8; 
	printf("\nBitmap size (in bytes): %I64d \n", bmsize);
	printf("Image Description: %s \n", ima_in->GetDescription() );
	
	// Extension is a global parameter set by Open_imaFile()
	
	if (EQUALN(Extension,"pix",3)) PCI_File = 1;	// everything is in the PCI file
	if (EQUALN(Extension,"tif",3)) TIF_File = 1;	// everything is in directory, mostly as tif files

	if (! ( PCI_File || TIF_File))
	  {
	  printf("\n\n**ERROR** Program not able to deal with image file of type %s\n\n", Extension);
	  exit(-1);
      }

// Create base file name  
	 
// Need to get "basefilename" when full path is involved
// Basefile name has path + head of file name (typically correspond to "named area" of study e.g. PRF)
// Area name is assumed separated from rest of file name by an underscore
// However, be careful as there could be underscores in the path

	strcpy(fullfilename,argv[1]);			// main input filename (and possibly its dir)
	
	for (ii=0; ii < strlen(fullfilename); ii++)		// search for last underscore position
	  {
	  jj = strlen(fullfilename) - ii;				// start from the end
	  //printf("Count back: %d",j);
	  if(fullfilename[jj] == '_') {basef_len = jj;	break;}	// find last underscore in full file name
	  }
	//printf("\nBase Filename Length:  %d \n", basef_len);
  	
	strncpy(basefilename, fullfilename,  basef_len);		// get that part of  the full file name
	basefilename[basef_len] = '\0';   					// make it a string to be safe
	
	printf("\n\nBase file name ::  %s \n", basefilename);	
	//exit(-1);
	

	

// 	Get full directory  PATH to that MAIN file (maybe to be used by others)

 
	strcpy(fullfilename,argv[1]);			// main input filename (and possibly its dir)
	//printf("Full Filename:  %s \n", fullfilename);
	//printf("\n Fullfilename string length is  %d \n", (int)strlen(fullfilename));
	
	jj = 0; path_len = 0;
	for (ii=0; ii < strlen(fullfilename); ii++)			// could be slash or backslash
	  {
	  jj = strlen(fullfilename) - ii;		// from the end of full file name
	  if( (fullfilename[jj] == '/') || (fullfilename[jj] == '\\') ){path_len = jj;	break;}	// find last slash in full file name
	  }  
	//printf("\nPath Length:  %d \n", path_len);
	//printf("\n jj =  %d \n", jj);	


	if(path_len == 0) strcpy(main_path, "./");				// no path  - impose a default path
	else
	  {
	  strncpy(path, fullfilename, path_len+1);		// get the path (inc. last slash)
	  path[path_len+1] = '\0';   					// null character manually added 
	  strcpy(main_path, path);	  
	  }

	printf("\n  Path of main file ::  %s \n", main_path);			// may have full path to directory
	
	//exit(-1);		// for debugging
 		

// *****************************

// Check argument argv[2] on command line : ISOLBM 

Arg2:

	printf("\nAs per user input, ISOLBIT number (or file) to use: %s \n", argv[2]);	

	// First check - no multiple comma-separated entries allowed for this one
	

	strcpy(temp, argv[2]);  pt = strtok(temp, ","); ii = 0;
	while(pt != NULL) 
	  {
 	  //printf("%s\n", pt); 
	  ii = ii + 1;
	  pt = strtok(NULL, ",");
	  }
	int no_items = ii;

	if(no_items > 1) 	
	  {
	  printf("\nAs per user input, ISOLBIT channel number to use: %s \n", argv[2]);
	  printf("\n\t** ERROR This require a single entry (and no range allowed)\n\n");
	  exit(-1);
	  }
	  
	// Special notation cases (ITC or ISOL)
	
	strcpy(basefname, basefilename);	

	if(EQUALN(argv[2],"ITC",3)) 
		{
		file_in = strncat(basefname,"_ITC",4);  
		strncat(file_in,".tif",4);
		strcpy(file_ITC, file_in);
		printf("ISOLBIT file_in  :  %s \n", file_ITC); 
		goto Arg3; 
		}	
	
	if(EQUALN(argv[2],"ISOL",4)) 
		{
		file_in = strncat(basefname,"_ISOL",5);  	
		strncat(file_in,".tif",4);
		strcpy(file_ITC, file_in);
		printf("ISOLBIT file_in  :  %s \n", file_ITC); 
		goto Arg3; 
		}
 
 
	isolbit = strtol(argv[2],NULL,10);			// pickup ISOLBM number - used with both file types
	

	// Check if user entry is a full file name (i.e., it"s not just a plain number)
	
	if (isolbit == 0)				// if not number, then it's a specific file name
	  {
	  strcpy(file_ITC, argv[2]);
	  printf("\n\t*Will use ITC file %s \n\n", file_ITC);		// that's all
	  goto Arg3;
	  }
 
	  
	// If single number was used, Create an input file name for ISOLBM file	(e.g.: SECTEUR_BM4.tif)

	
	file_in = strncat(basefname,"_BM",4); strncat(file_in,argv[2],3); 	 	// Specific bitmap number
	
	strncat(file_in,".tif",4);
	strcpy(file_ITC, file_in);
	
	printf("\n\t* ISOLBIT filename will be  :  %s \n", file_ITC);   

	  
// *****************************

// Check argument argv[3] on command line : TESTSEG 

Arg3:	  	//exit(-1); 		// For testing
	
	printf("\nTest area file and numbers (%s) should correspond to separate .tif or .shp files\n\n",  argv[3]);

	name_given = 0;		// reset name given flag

	strcpy(temp, argv[3]); 
	
// Check if user entry has a file name in it(i.e., it"s not just plain numbers)
	
	  if (strtol(argv[3],NULL,10) == 0)				// if not just numbers, then it has a specific file name
	    {
		pt = strtok(temp, ",");  			// remove numbers after file name
		//printf("\t\t* temp is :  %s \n", temp); 
		pt = strtok(temp, "."); 			// remove extension after file name
		strcpy(ext, strtok(NULL, " "));				// get extension to put back later			
		strcpy(given_fname,temp);
		
		// check if already a number (nn) in filename (before extension) and REMOVE IT 
		// To facilitate using copy and paste (e.g., PRF_Vec6.shp,6,-13) 
		// It will not kill other numbers in file name or in path

		if(isdigit(given_fname[strlen(given_fname)-1]))  given_fname[strlen(given_fname)-1]='\0';
		if(isdigit(given_fname[strlen(given_fname)-1]))  given_fname[strlen(given_fname)-1]='\0';	
			
		name_given = 1;			// flag that a specific base name for training area was given
		printf("\t*Will use file prefix (given_fname) \"%s\" and extension \"%s\" for testing areas\n\n", given_fname, ext);
		//exit(-1);
		}	  

	//	printf("\n\n #1   argv[3]=%s  temp=%s  pt=%s  \n", argv[3], temp, pt);


// Adjust for common notation (e.g.: 6-13), different than PCI notation (e.g.: 6,-13)

// On detecting a minus sign, not preceeded by a comma, 
//	insert a comma (& keep minus sign needed by param_expand() )

	strcpy(temp2, argv[3]);
	jj = 0;
	for (ii=0; ii < strlen(temp2); ii++)
	  { 
	  temp[jj] = temp2[ii]; 	  // just copy 	  
	  if ( (temp2[ii] == '-') && (temp2[ii-1] != ',') ) { temp[jj] = ','; temp[++jj] = '-'; }
	  jj++;
	  }
	  temp[jj] = '\0';
	  
//	printf("\ntemp = %s \n", temp);
//	exit(-1);

// Prepare to deal with numbers after file name *OR* channel numbers only			  
	  
	// For numbers after file name, goto 1st comma, then 2nd comma and to get the 1st digit(at pointer p)
	
	//if(name_given) { strcpy(temp, argv[3]); pt = strtok(temp, ","); pt = strtok(NULL, ","); } 
	if(name_given) { pt = strtok(temp, ","); pt = strtok(NULL, ","); }
	//printf("\n\n #2   argv[3]=%s  temp=%s  pt=%s  \n\n", argv[3], temp, pt);
	//exit(-1);
	
	//	 For channel numbers only -- goto 1st comma  and to get the 1st digit (at pointer p)

	//if(!name_given) { strcpy(temp, argv[3]); pt = strtok(temp, ",");  }
	if(!name_given) { pt = strtok(temp, ",");  }
	//printf("\n\n #3   argv[3]=%s  temp=%s  pt=%s  \n", argv[3], temp, pt);
	//exit(-1);




// Get the various comma-separated items into a list -- ** OK ** for PCI notation (e.g.: 6,-13)
// Pointer "p" points to 1st digit
 
	ii = 0;
	while(pt != NULL) 
	  {
	  //printf("*** %s\n", pt); 
	  itestseg[ii++] = strtol(pt,NULL, 10);			//  list of no. for test areas to use
	  pt = strtok(NULL, ",");
	  }
	no_items = ii;


	//printf("\nTEST SEG - no of INPUT items = %d \n", no_items);

// Expand the list of test segments if ranges (minus sign) are being used
// 		This make possible short hand notation using "PCI range style" (e.g., 10,-13)
// 		making possible for up to 32 test areas (classes) to be used 

	param_expand(no_items, itestseg, testseg, &ntest);	
	
	if(ntest > BITMAPS ) 
		{fprintf(stderr,"\n ERROR - max # of classes(32)  exceeded \n"); exit(-1); }

	//printf("TEST SEG - no real items = %d \n", ntest);
 /*  
	printf("\nInput test area numbers to use : \n");
	for(i=0; i<ntest; i++) 	printf("Test area %d is %d \t", i+1, testseg[i]);
	printf("\n\n");
 */

//	exit(-1);			// for debugging

 
	
// 	Get full directory  PATH for these  files 

	path_len=0;	jj=0; 
	tst_path_flag = 1 ;		// assume that path was supplied within test file string
 
	strcpy(fullfilename, argv[3]);
	//printf("Full Filename:  %s \n", fullfilename);
	//printf("\n Fullfilename string length is  %d \n", (int)strlen(fullfilename));
	
	for (ii=0; ii < strlen(fullfilename); ii++)			// could be slash or backslash
	  {
	  jj = strlen(fullfilename) - ii;		// from the end of full file name
	  if( (fullfilename[jj] == '/') || (fullfilename[jj] == '\\') ){path_len = jj;	break;}	// find last slash in full file name
	  }  
	//printf("\nPath Length:  %d \n", path_len);	


	if(path_len == 0)			// NO PATH was supplied with shp file string
	  {
	  tst_path_flag = 0; 				//no path was supplied with shp file string
	  //strcpy(path, "./");				// no path  - impose a default path
	  strcpy(tst_path, main_path);				// OR use MAIN file path	  
	  //strcpy(basefname, fullfilename);		//so base_fname is fullfilename
	  }

/* 	  
	if(path_len > 0) 				// path was supplied with shp file string
	  {	
	  tst_path_flag = 1; 				// path was supplied with shp file string
	  strncpy(path, fullfilename, path_len+1);		// get the path (inc. last slash)
	  path[path_len+1] = '\0';   					// null character manually added 
	  strcpy(tst_path, path);
	
//	base_fname = fullfilename after path

 	  ii =0 ;
	  jj = path_len + 1;			// end of path in fullfilename
	  strcpy(fullfilename, argv[3]);	
	  while(fullfilename[jj] != NULL)  basefname[ii++] = fullfilename[jj++];
 	  
	  }
*/

	
//	printf("SHP Full Filename:  %s \n", fullfilename);

//	printf("\n  Path of TEST files is ::  %s \n", tst_path);			// may have full path to directory





// IF base file name already given 	for training area 

	  if(name_given)
	  {
	  //strcpy(temp,given_fname);		// for example: secteur_VEC.shp  
	  // separate extension to put back late
	  //strcpy(basefname, strtok(temp,"."));		// get base file name  (e.g., secteur_VEC)
	  //strcpy(ext, strtok(NULL, " "));				// get extension to put back later
		
	  strcpy(basefname, given_fname);
	  strcpy(shpfilename, basefname);	
	  printf("\n\tTest area base_fname = %s Extension =  %s \n\n", basefname, ext);	


// Create training areas names and check existance

	  for(i=0; i<ntest; i++)		// check all possible training areas
		{
		// ArcGISPro requires full path, so add main file path			
		if (!tst_path_flag) {strcpy(temp, main_path); strcat(temp, shpfilename);}
		//if (tst_path_flag) strcpy(temp, tst_path);			// if a path was given with the signatures, add that one
					
		if (tst_path_flag) strcpy(temp, shpfilename);
		
		//itoa(testseg[i],seg_no,10); 	  // get segment number
		sprintf(seg_no,"%d",testseg[i]);
	    strncat(temp,seg_no,3);	
	    strcat(temp,".");	
	    strcat(temp,ext);	
		strcpy(file_TAS[i],temp);
		
		printf("Testing area file to use  :  %s \n", file_TAS[i]); 	

// CHECK file existence
 	
		tas_fp = fopen(file_TAS[i], "r");	
		if (tas_fp == NULL) 
		  {
		  printf("\n\n\t*File %s may not exist. Please double check. EXITING \n\n", file_TAS[i]); 
		  printf("\n\nRead the error message before program exits ..."); // for user time to read when using ArcGIS
		  answer[0] = getc(stdin); 		// gets any answer or plain <CR>
		  exit(-1); 
		  }		
		  
		if(EQUALN(ext,"shp",3)) TA_segtype[i] = SEG_VEC;		// this layer is of vector  type
		if(EQUALN(ext,"tif",3))	TA_segtype[i] = SEG_BIT;		// this layer is of bitmap type	
 
		}		// for all TAs	
		 	  
		goto Arg4;
		
	  }			// for name given

//		exit(-1);	// for debugging
	
	// If NO NAME was given, create possible names
	
 	// Create DEFAULT (AUTOMATIC) input file names from given numbers		e.g.: SECTEUR_BM14.tif

	for(i=0; i<ntest; i++)
		{		
	/*     strcpy(fullfilename,filename);			// main filename as base
	    //printf("fullfilename :  %s \n", fullfilename);
	    basefname = strtok(fullfilename,".");
	    //basefname = strtok(basefname,"/");
		basefname = strtok(basefname,"_");
	    //printf("basefname  :  %s \n", basefname);
		 */
			
		strcpy(basefname, basefilename);		
		
	    file_in = strncat(basefname,"_BM",3); 
	    //printf("file_in  :  %s \n", file_in);    
 		//itoa(testseg[i],seg_no,10); 	  // get segment number
		sprintf(seg_no,"%d",testseg[i]);	
		
	    strncat(file_in,seg_no,3);	  	  	
 	    strncat(file_in,".tif",4);
	    //printf("file_in  :  %s \n", file_in); 					
		strcpy(file_TAS[i], file_in);  
	    printf("%d Testing Area  file_in  :  %s \n", i+1, file_TAS[i]); 	

		TA_segtype[i] = SEG_BIT;			// remember type of file			
		//printf("\n SEG_BIT = %d \n",SEG_BIT);
		
		// Check if file exist as a Bitmap Training Area -- could be a "shp" file Training Area
		
		tas_fp = fopen(file_TAS[i],"rb");
		if (tas_fp) { fclose(tas_fp); continue;	}	// if OK, check next signature
		
		if (!tas_fp) 		// if not OK check if came from a Vector Training Area
		  { 
		  //printf("*** As such, that file does not exist - Will try a different variation\n"); 
	   
		  strcpy(basefname, basefilename);	

		  file_in = strncat(basefname,"_VEC",4); 
		  //printf("file_in  :  %s \n", file_in);    
		//itoa(testseg[i],seg_no,10); 	  // get segment number
		sprintf(seg_no,"%d",testseg[i]); 	  
		  strncat(file_in,seg_no,3);	  	  	
		  strncat(file_in,".shp",4);
		  //printf("file_in  :  %s \n", file_in); 					
		  strcpy(file_TAS[i], file_in);  
		  printf("%d Testing Area  file_in  :  %s \n", i+1, file_TAS[i]); 	

		  TA_segtype[i] = SEG_VEC;			// remember type of file
		  //printf("\n SEG_VEC = %d \n",SEG_VEC);
		
		  // check if that file exist
		  
		  tas_fp = fopen(file_TAS[i],"rb");
		  
		  if (!tas_fp) 
			{ 
			printf("\n   *** File may not exist !!! \n\n"); 		
			printf("\nRead the error message before program exits   ..."); 	// for user time to read when using ArcGIS
			answer[0] = getc(stdin); 		// gets any answer or plain <CR>
			exit(-1);
			}

		  fclose(tas_fp);
		  }	
		  
		printf("\t For testing area %d - Will use : %s \n\n", i+1, file_TAS[i]);
		
		}			// end of for each test area
	
	

// *****************************

// Check argument argv[4] on command line : CLASSBIT 

Arg4:	  //exit(-1); 	// useful for degugging inputs

/*
	// for user to check on all input TA files before proceeding	DEBUGGING
	
	printf("\n\nOK to continue(y/n)? ");
	//scanf("%s",answer);			// gets any answer, but NEEDS  one
	answer[0] = getc(stdin); 		// gets any answer or plain <CR>
	if(answer[0]=='n')  exit(-1);
 */
	
	printf("\n\nClass files and numbers (%s) should correspond to separate .tif  files\n\n",  argv[4]);			

	// Check if user entry has a file name already in it(i.e., not just numbers)


	name_given = 0;		// reset name given flag

	strcpy(temp, argv[4]); 	
		
	  if (strtol(argv[4],NULL,10) == 0)				// if not numbers, then it's a specific file name mentionned 
	    {
		pt = strtok(temp, ",");  		// remove numbers after file name
		pt = strtok(temp, "."); 		// remove extension after file name
		strcpy(ext, strtok(NULL, " "));		// get extension to put back later
		strcpy(given_fname,temp);			// get filename (and possibly a path)
		//printf("\n\nClasses Given_fname %s and its length %zd \n", given_fname, strlen(given_fname));
		
		// check if already a number in filename and REMOVE IT (usefull for cut & paste of a filename)
		if(isdigit(given_fname[strlen(given_fname)-1]))  given_fname[strlen(given_fname)-1]='\0'; //rm one digit
		if(isdigit(given_fname[strlen(given_fname)-1]))  given_fname[strlen(given_fname)-1]='\0'; //rm a 2nd digit		
	
	    printf("\n\t*Will use given file prefix (given name) \"%s\" for class bitmaps\n\n", given_fname);	
		name_given = 1;			// flag that a specific base name for training area was given
		//exit(-1);
		}	  


// Adjust for "common" notation (e.g.: 6-13), different than PCI notation (e.g.: 6,-13)

// On detecting a minus sign, not preceeded by a comma, 
//	insert a comma (& keep minus sign needed by param_expand() )


	for(ii = 0; temp[ii] != '\0'; ii++) { temp[ii] = ' '; }   // clean up temp

	strcpy(temp2, argv[4]);
	jj = 0;
	for (ii=0; ii < strlen(temp2); ii++)
	  { 
	  temp[jj] = temp2[ii]; 	  // just copy 	  
	  if ( (temp2[ii] == '-') && (temp2[ii-1] != ',') ) { temp[jj] = ','; temp[++jj] = '-'; }
	  jj++;
	  }
	  temp[jj] = '\0';

	//printf("\ntemp = %s \n", temp);


// Prepare to deal with numbers after file name *OR* channel numbers only			  
	  
	// For numbers after file name, goto 1st comma, then 2nd comma and to get the 1st digit(at pointer p)
	
	if(name_given) { pt = strtok(temp, ","); pt = strtok(NULL, ","); }

	//printf("\n\n #2   argv[3]=%s  temp=%s  pt=%s  \n\n", argv[3], temp, pt);
	//exit(-1);
	
	//	 For channel numbers only -- goto 1st comma  and to get the 1st digit (at pointer p)

	if(!name_given) { pt = strtok(temp, ",");  }
	
	//printf("\n\n #3   argv[3]=%s  temp=%s  pt=%s  \n", argv[3], temp, pt);
	//exit(-1);


// Get the various comma-separated items into a list   iclassbit[]
	
	ii = 0;
	while(pt != NULL) 
	  {
 	  //printf("*** %s\n", pt); 
	  iclassbit[ii++] = strtol(pt,NULL, 10);			//  possible list of test areas  to use
	  pt = strtok(NULL, ",");
	  }
	no_items = ii;
 
 
// Expand list of class bitmaps if range was used

// This make possible short hand notation using PCI ranges (and "common" range)
//  also make possible (and convenient) for up to 32 signatures (& classes) to be used 

	param_expand(no_items, iclassbit, classbit, &nclass);
	if(nclass > BITMAPS ) 
		{fprintf(stderr,"\n ERROR - max # of classes(32)  exceeded \n"); exit(-1); }

/* We want (need) a balanced results */

	if(nclass != ntest)
	{
	fprintf(stderr,"\n ERROR - The number of test segments and the number of classes\n");
	fprintf(stderr,"\t\t are different. This is not appropriate. Task exiting \n\n");
	printf("\n\nRead the error message before program exits   ..."); 	// for user time to read when using ArcGIS
	answer[0] = getc(stdin); 		// gets any answer or plain <CR>
	exit(-1);
	}


	
// 	Get full directory  PATH for these  files 

	path_len=0;	jj=0; 
	cls_path_flag = 1 ;		// assume that path was supplied within test file string
 
	strcpy(fullfilename, argv[4]);
//	printf("Full Filename argv[4]:  %s \n", fullfilename);
//	printf("\n Fullfilename string length is  %d \n", (int)strlen(fullfilename));
	
	for (ii=0; ii < strlen(fullfilename); ii++)			// could be slash or backslash
	  {
	  jj = strlen(fullfilename) - ii;		// from the end of full file name
	  if( (fullfilename[jj] == '/') || (fullfilename[jj] == '\\') ){path_len = jj;	break;}	// find last slash in full file name
	  }   
	  fullfilename[path_len] = '\0';
	  
 	  strcpy(cls_path, fullfilename);			// when a path is given 
	  
	    
//	printf("\nPath Length:  %d \n", path_len);	
//	printf("\nPotential path for classes:  %s \n", fullfilename);

	if(path_len == 0)			// NO PATH was supplied with class  file string
	  {
	  cls_path_flag = 0; 				//no path was supplied with shp file string
	  //strcpy(path, "./");				// no path  - impose a default path
	  strcpy(cls_path, main_path);				// OR use MAIN file path	  
	  //strcpy(basefname, fullfilename);		//so base_fname is fullfilename
	  }

	printf("\nPath for classes is or will be :  %s \n\n", cls_path);


	//printf("\nInput class bitmap to use : \n");
	//for(i=0; i<nclass; i++) 	printf("Class %d is %d \t", i+1, classbit[i]);
	//printf("\n\n");

	//exit(-1);

//	printf("\nBasefilename = %s \n\n", basefilename);


// Create input file names from the given numbers		e.g.: SECTEUR_CLASS14.tif
	
	if(!name_given)			// if no file name given (just numbers) Create input file names
	{
	for(i=0; i<nclass; i++)
		{	
	
		strcpy(basefname, basefilename);  	 // basefilename  (may already have a path)	
		
	    file_in = strncat(basefname,"_CLASS",6); 
	    //printf("file_in  :  %s \n", file_in);    
  	    //itoa(classbit[i],seg_no,10); 
		sprintf(seg_no,"%d",classbit[i]);		
	    strncat(file_in,seg_no,3);	  	  	
 	    strncat(file_in,".tif",4);
	    //printf("file_in  :  %s \n", file_in); 					
		strcpy(file_CLASS[i], file_in);  
	    printf("%d Class bitmap file_in  :  %s \n", i+1, file_CLASS[i]); 	
	
		// check if that file exist
		  
		class_fp = fopen(file_CLASS[i],"r");
		if (!class_fp)
			{ 
			printf("\n   *** File may not exist !!! \n\n"); 		
			printf("\nRead the error message before program exits  ..."); 	// for user time to read when using ArcGIS
			answer[0] = getc(stdin); 		// gets any answer or plain <CR>
			exit(-1);
			}
		fclose(class_fp);		
		
		}		
	
	}
	
	
// IF other base file name already given 	for training area 

	  if(name_given)
	  {
	  //strcpy(temp,given_fname);		// for example: secteur_VEC.shp 
		// separate extension to put back later
	    //strcpy(basefname, strtok(temp,"."));		// get base file name  (e.g., secteur_VEC)
        //strcpy(ext, strtok(NULL, " "));				// get extension to put back later
	

		// ArcGISPro requires full path, so add main file path
		
		if (cls_path_flag) strcpy(basefname, given_fname);	
		if (!cls_path_flag) {strcpy(basefname, main_path); strcat(basefname, given_fname);}	

	    strcpy(clsfilename, basefname);	
	    printf("\n\tClass Base_fname = %s Extension =  %s \n\n", basefname, ext);	

		
		strcpy(shpfilename, basefname);
		
	  for(i=0; i<ntest; i++)		// check all possible training areas
		{
		strcpy(temp,shpfilename);
  	    //itoa(classbit[i],seg_no,10); 
		sprintf(seg_no,"%d",classbit[i]);
	    strncat(temp,seg_no,3);	
	    strcat(temp,".");	
	    strcat(temp,ext);	
		strcpy(file_CLASS[i],temp);
		
		printf("Class bitmap file to use  :  %s \n", file_CLASS[i]); 	
	

		// CHECK file existence
	
		tas_fp = fopen(file_CLASS[i], "r");	
		if (tas_fp == NULL) 
		  {
		  printf("\n\n\t*File %s does not exist. Please double check. EXITING \n\n", file_CLASS[i]); 
		  exit(-1);
		  }
		
		}		// for all classes 	
		 	  
		goto Arg5;
		
	  }			// for name given

// *****************************

// Check argument argv[5] on command line : BITBOUND 

Arg5:	
 	  
// Check that  BITBOUND  parameter is valid 

 if ( (argc < 6) || EQUALN(argv[5],"-",1 ) || EQUALN(argv[5],"#",1 ) )
	{
	strncpy(boundtype, "AUTO",4); 		// default mode if none specifieds
	boundtype[4] = '\0';   			// null character manually added
	printf("\n\tUsing default Boundary type: %s \n", boundtype);
	}
  else
	{	
	strncpy(boundtype, argv[5], 6);			
	check_parameters(boundtype);
	printf("\n\tBoundary type: %s \n", boundtype);
	}	

	// for user to check on all input files before proceeding	
	
	printf("\n\nOK to continue(y/n)? ");
	//scanf("%s",answer);			// gets any answer, but NEEDS  one
	answer[0] = getc(stdin); 		// gets any answer or plain <CR>
	if(answer[0]=='n')  exit(-1);

		
		
// *********************************************************


	printf("\n\n*******************************************************\n\n");
	printf("\t\t** Reading ITC/ISOL bitmap  \n");
	
		
// Read some bitmaps into buffers while allocating memory for temp bitmaps 

	printf("\n\nReading ITC bitmap and reserving memory for two temp bitmaps\n");
	
	//isolbitbuffer = alloc_read_bmp(idb_fp, xsize, ysize, isolbit);  //PCI style
	
	isolbitbuffer = read_bitmap(file_ITC, 1);			// GDAL version
	
	//andbuffer = alloc_read_bmp(idb_fp, xsize, ysize, 0);		// PCI Style
	//ext_mask = alloc_read_bmp(idb_fp, xsize, ysize, 0);

	andbuffer = (PixVal *) CPLMalloc(bmsize);
	check_mem(andbuffer);

	ext_mask = (PixVal *) CPLMalloc(bmsize);
	check_mem(ext_mask);

// **********************	

	
	printf("\n\n*******************************************************\n\n");
	printf("\t** Reading test areas bitmaps(1-bit tif) OR layer 1 in shape files \n");
	
	//small_ima = 0 ;			// to test	big image mode
	
	// In small image mode, read ALL class bitmaps and test areas bitmaps or shape file in memory
	
	if (small_ima)
	{	
		//printf("\n\n\t\t** Reading all test area bitmaps OR shape files ... \n\n");
		
		for (j = 0; j < nclass; j++)
		  {
		  if(TA_segtype[j] == SEG_BIT) testbitbuf[j] = read_bitmap(file_TAS[j], 1);	
		
		  if(TA_segtype[j] == SEG_VEC) testbitbuf[j] = vector2bitmap(file_TAS[j], 1);	
		  
		  if ( (TA_segtype[j] != SEG_BIT) && (TA_segtype[j] != SEG_VEC) ) 
					{ printf(" *** ERROR*** with test area %d \n\n", j); exit(-1); };
				
		  //printf("\n\n\t\t ** DONE with test area %d \n\n", j); 
		  }		

		  
		//printf("\n###  OK to continue(y/n): ");  scanf("%s",answer);		// to check memory usage
  
  
		printf("\n\n*************\n");
		printf("\n\t\t** Reading all class bitmaps ... \n\n");
		
		for (j = 0; j < nclass; j++) classbitbuf[j] = read_bitmap(file_CLASS[j], 1);			

	}
	
		//printf("\n###  OK to continue(y/n): ");  scanf("%s",answer);
  
  
		//exit(-1);		// for TESTING		

	
// If EXT mask is needed, read it in and AND it with isolation bitmap

/*
	if (strcmp(boundtype, "POINTS") == 0)
	{
	if (argcnt[4] == 1)
	  {
	  fprintf(stdout,"\nGetting bitmap of pointers (POSBIT):");
	  ext_mask = alloc_read_bmp(idb_fp, xsize, ysize, extmask);
	  for (iii = 0; iii <bmsize; iii++) *(ext_mask + iii) &= (*(isolbitbuffer + iii));
	  pointmode = 1;
	  } 
	else
	  {
	  fprintf(stdout,"\n*** ERROR: A crown pointers bitmap( POSBIT)\n");
	  fprintf(stdout,"\t\t is needed to use BITBOUND=POINTS.\n");
	  exit(-1);
	  }

	}
	if (argcnt[4] == 0) extmask = 0;

// If EXT mask is not needed but present as input parameter, give warning 

	if ( (strcmp(boundtype, "POINTS") != 0) && (argcnt[4] == 1) )
	  fprintf(stdout,"\n*** WARNING: Position bitmap(POSBIT) is set, but will be disregarded in this mode.\n");
*/



// Create UNCLASSIFIED BITMAP from others 

	if(small_ima)
		fprintf(stdout,"\n\nUsing all class bitmaps to create the unclassified bitmap ...\n\n");
	else
		fprintf(stdout,"\n\nReading all class BMs from disk (big_ima mode) to create the unclassified bitmap ...\n\n");

	
	/* Allocate memory (zeroed) for unclassified bitmap (last class) */

	//unclassbuf = alloc_read_bmp(idb_fp, xsize, ysize, 0);		// my PCI routine	
	unclassbuf = (PixVal *) CPLMalloc(bmsize);
	check_mem(unclassbuf);

	
	// put all class bitmaps into this unclassified bitmap 
	
	for (j = 0; j < nclass; j++)
	{

		if (small_ima)		/* they are in memory already */
			for (iii = 0; iii <bmsize ; iii++)  *(unclassbuf+iii) |= *(classbitbuf[j]+iii);
			
		else			// BIG IMAGE mode : you have to read them in one-by-one using a temp buffer 
			{		
			//classbuffer = alloc_read_bmp(idb_fp, xsize, ysize, classbit[j]);	// my PCI routine			
			classbitbuffer =  read_bitmap(file_CLASS[j], 1);
			for (iii = 0; iii <bmsize ; iii++)  *(unclassbuf+iii) |= *(classbuffer+iii);
			CPLFree(classbitbuffer);
			}
	}
	
	// XOR with ITC bitmap

	for (iii = 0; iii <bmsize ; iii++) *(unclassbuf+iii) = (*(isolbitbuffer+iii)) ^ (*(unclassbuf+iii)); 

	
	
// Make sure confusion matrix is initialized to zeros 

	for (i = 0; i <= nclass; i++)
		for (j = 0; j < nclass; j++)
			confusion_matrix[i][j] = 0;
		

  //printf("\n###  OK to continue(y/n): ");  scanf("%s",answer);
  
	//	exit(-1);		// for TESTING		


/*************************************************************/

/* MAIN PROCESSING (for small images) */

/*************************************************************/

if (small_ima)			/* for small images when all is done in memory */
  {
	//IMPTime(timedate,4);
	//printf("\nMain processing - Making confusion matrix (%s). Please wait...\n",timedate);

	printf("\n\n***********************************************\n\n");	
	time (&rawtime);  timeinfo = localtime (&rawtime);
	printf("\tMain processing started - Time is: %s \n",asctime(timeinfo));	
	printf("\tMain processing - Making confusion matrix. Please wait...\n");	
	//printf("For %d classes \n", nclass);
	
	
	for (mask1 = 0; mask1 <= nclass; mask1++)			// for each classes + unclassified
	{
	if(mask1 != nclass)	classbuffer =  classbitbuf[mask1];		// for all real classes 
	if(mask1 == nclass) classbuffer = unclassbuf;				// last but not least for unclassified ITCs 

	for (mask2 = 0; mask2 < nclass; mask2++) 		 // for each test area (or set of test crowns) 
	  {

	  /* create mask of the test area (or test crown set) and class bitmap */

	  for (iii = 0; iii <bmsize ; iii++)
	    *(andbuffer + iii) = (*(classbuffer + iii)) & (*(testbitbuf[mask2]+ iii));

	  /* Count trees and record in matrix */
		
	  scan_for_tree(classbuffer, andbuffer, mask1, mask2, boundtype, xsize, ysize);

	  //IMPCounter( (float) (mask1 * nclass + mask2 + 1) / (float) (nclass * (nclass + 1)) );
	  
	  //printf("\nDoing comparison class %d vs test area %d \n", mask1, mask2);

	  }
	}


	time (&rawtime);  timeinfo = localtime (&rawtime);
	printf("\n\tConfusion matrix done - %s\n", asctime(timeinfo));
	
	
  }			/*end of for small Image*/
  	
  
	//exit(-1);		// for TESTING		
	

/*************************************************************/

/* MAIN PROCESSING (for big images) */

/*************************************************************/

if ( ! small_ima)			
  {
	//IMPTime(timedate,4);
	//fprintf(stdout,"\n\nReading all class and test bitmaps from disk to do confusion matrix (%s) ...\n\n",timedate);

	printf("\n\n*******************************************************\n\n");	
	time (&rawtime);  timeinfo = localtime (&rawtime);
	printf("Main processing started - Time is: %s \n",asctime(timeinfo));	
	printf("Main processing - Making confusion matrix. Please wait...\n");	

	for (mask1 = 0; mask1 <= nclass; mask1++) /* for each classes + unclassified */
	{

	//if(mask1 != nclass) classbuffer = alloc_read_bmp(idb_fp, xsize, ysize, classbit[mask1]);
	
	if(mask1 != nclass)	classbuffer =  read_bitmap(file_CLASS[mask1], 1);
	
	if(mask1 == nclass) classbuffer = unclassbuf;	/* last but not least for unclassified ITCs */
	

	for (mask2 = 0; mask2 < nclass; mask2++)  /* for each test area (or set of test crowns) */
	  {
	  //read_testseg(mask2);			// read TA bitmap or vector
	  
	  if(TA_segtype[j] == SEG_BIT) testbitbuf[j] = read_bitmap(file_TAS[mask2], 1);	
		
	  if(TA_segtype[j] == SEG_VEC) testbitbuf[j] = vector2bitmap(file_TAS[mask2], 1);	  
	  

	  for (iii = 0; iii <bmsize ; iii++)
	    *(andbuffer + iii) = (*(classbuffer + iii)) & (*(testbuffer + iii));

	  /* Count trees and record in matrix */
		
	  scan_for_tree(classbuffer, andbuffer, mask1, mask2, boundtype, xsize, ysize);

	  //IMPCounter( (float) (mask1 * nclass + mask2 + 1) / (float) (nclass * (nclass + 1)) );
	  free(testbuffer);
	  }

	free(classbuffer);
	}
  }					/* end of for big images */

/*****************************************************************************/

/* Finishing touches */

/*************************************************************/

	printf("\n\tFinishing touches and display confusion matrix \n");
	
/* Calculate sums and percentages, and display confusion matrix, 
	average and overall accuracies, kappas, and crown areas of good trees */

	process_matrix();
	
	printf("\n*******************************************************\n");
	
	
	view_matrix(extmask, boundtype);

	
//	Also create a plain text file for future reference	

	strcpy(report,basefilename);
	strcat(report,"_ITCCA_Results.txt");
	//printf("\nOutput file name for plain text file : %s \n", report);	
	Report =  fopen(report,"w");	
	
	printf("\n\tAlso creating a plain text file of that Confusion Matrix : %s \n", report);
	
	view_matrix(extmask, boundtype);
	
// Add additional info about this run
	fprintf(Report,"\nProduced using main image file: %s \n", argv[1]);	
	fprintf(Report,"\nProduced from classes %s using testing areas %s \n", argv[4], argv[3]);
	fprintf(Report,"\n\tThis Confusion Matrix file is : %s \n", report);
	
/* Close files and return properly */

	time (&rawtime);  timeinfo = localtime (&rawtime);
	fprintf(stdout,"\n\n_______________________________\n");
	fprintf(stdout,"\n%s (%s) finished at %s\n\n", PROG_NAME, VERSION, asctime(timeinfo));

	fprintf(Report,"\n%s (%s) finished at %s\n\n", PROG_NAME, VERSION, asctime(timeinfo));
	
// For people using this program via ArcGIS, give then some time to examine the results (before disappearing)

if  (EQUALN("ArcGIS ",argv[argc-1],3) )
	{
	fprintf(stdout,"\n\n######\n");
	printf("\n Type anything to make this detailed window disappear and terminate %s ",PROG_NAME);
	answer[0] = getc(stdin); 		// gets any answer or <CR>
    }
	
	
	exit(0);				// exit properly 


}			// End of main 


/*****************************************************************************/

/* FUNCTIONS */

/*****************************************************************************/

/*
	Function to read a "test" bitmap or paint polygonal shapes into such bitmap
	depending on the nature of the segment pointed to by testseg[classn].
*/

#ifdef PARTIAL_GDAL

void	read_testseg(int classn)
	{ 
	ProjInfo_t	pProj;
	GDBLayer 	player;

	  fprintf(stdout,"\nReading test area bitmap/vector segment (%d)\n",testseg[classn]);
	  
	  IDBSegInfoIO(idb_fp, testseg[classn], IDB_READ, &segflag, &segtype, segname, &start, &length);  
	  
	  
	  if (segtype == SEG_BIT) testbuffer = alloc_read_bmp(idb_fp, Pixels, Lines, testseg[classn]);
	  
	  
	  if (segtype == SEG_VEC)
	    {
	    player = GDBGetLayer(idb_fp, testseg[classn]);
	    if (player == NULL) 
		  {
		  fprintf(stdout,"\n *** ERROR opening vector layer %d \n", testseg[classn]);
  		  exit(-1);
		  }

	    GDBGetProjectionInfo(player, &pProj);
	    fprintf(stdout,"\nVector Projection Units: %s \n", pProj.Units);
	    if( ! EQUALN(pProj.Units,geosys,5) )
	      {
	      fprintf(stdout,"\n\n ### ERROR ### \n");
	      fprintf(stdout,"\n Geographic projection of the vector layer not the same as that of the image.\n\n");
	      fprintf(stdout,"\n Program ITCCA will abort ... \n");
	      exit(-1);
	      }
	
	    //testbuffer = alloc_read_bmp(idb_fp, Pixels, Lines, 0);  
		//fprintf(stdout,"Memory for bitmap allocated, calling paint_plot()\n");
	    //paint_plot(player, testbuffer, Pixels);  
		
		testbuffer = (PixVal *) CPLMalloc(bmsize);
		fprintf(stdout,"Memory for bitmap allocated, calling vector2bitmap()\n");
		vector2bitmap(filename, classn);
	    }
	}	

	#endif
	
	
/**************************************************************/
/* 
   This function 'fills' a tree shape, gathering information on the tree size and
   REMOVING it from the mask bitmap during processing
*/

void fill(int x, int y, int xsize, unsigned char *mask_data, int *count)
  {
  int64 bitnum;
  bitnum = (int64)xsize*(y-1) + x-1; 	/* bitnum starts at zero, (x,y) at (1,1) */
  (*count)++; 			    	/* increase count to get crown area */
  clearbit(mask_data,bitnum);		/* turn off bit */
  if (testbit(ext_mask,bitnum)) PointMet++;	/* pointer(s) encountered in POINTS mode */

  /* Fill recursively starting at current position */

  if (testbit(mask_data,bitnum+1))	fill(x+1, y, xsize, mask_data, count);
  if (testbit(mask_data,bitnum-xsize))	fill(x, y-1, xsize, mask_data, count);
  if (testbit(mask_data,bitnum-1))	fill(x-1, y, xsize, mask_data, count);
  if (testbit(mask_data,bitnum+xsize))	fill(x, y+1, xsize, mask_data, count);
  }


/**************************************************************/

/* This function 'fills' a tree crown, gathering information on the crown size
 and center of gravity and removing it from the bitmap while processing
*/

void fill_cg(int x, int y, int xsize, unsigned char *crown_data, int *count)
  {
  int64 bitnum;

  bitnum = (int64)xsize*(y - 1) + x-1;   	 /*bitnum starting at zero */
  (*count)++; 				/* increase count to get crown area */

  sum_x = sum_x + x;
  sum_y = sum_y + y;

  /* turn off bit & fill recursively starting at current position */

  clearbit(crown_data,bitnum);
  if (testbit(crown_data,bitnum+1))	fill_cg(x+1, y, xsize, crown_data, count);
  if (testbit(crown_data,bitnum-xsize))	fill_cg(x, y-1, xsize, crown_data, count);
  if (testbit(crown_data,bitnum-1))	fill_cg(x-1, y, xsize, crown_data, count);
  if (testbit(crown_data,bitnum+xsize))	fill_cg(x, y+1, xsize, crown_data, count);
  }

/*********************************************************************************/


/* This function determines the appropriate scanning function
   depending on the BITBOUND parameters
*/

void scan_for_tree(unsigned char *full_bitmap, unsigned char *mask_data, 
				int mask1, int mask2, char *boundtype, int xsize, int ysize)
{	
	if (strcmp(boundtype, "INC") == 0)
	  scan_for_tree_inc(full_bitmap, mask_data, mask1, mask2, xsize, ysize);
	if (strcmp(boundtype, "EXC") == 0)
	  scan_for_tree_exc(full_bitmap, mask_data, mask1, mask2, xsize, ysize);
	if (strcmp(boundtype, "AUTO") == 0)
	  scan_for_tree_auto(full_bitmap, mask_data, mask1, mask2, xsize, ysize);
	if (strcmp(boundtype, "CGRAV") == 0) 
	  scan_for_tree_cgrav(full_bitmap, mask_data, mask1, mask2, xsize, ysize);
	if (strcmp(boundtype, "POINTS") == 0)
	  scan_for_tree_points(full_bitmap, mask_data, mask1, mask2, xsize, ysize);
}
 
/*****************************************************************************/

/*
   This function scans the image to find in the masked area (at this point, it 
   is the ANDed version of "a" training area and "an" ITC class bitmap) a minimum  
   2x2 area corresponding to a tree. When found, the ITC is filled (thus erased)
   in that bitmap and in the fuller ITC class bitmap. 
   The tree is then counted in the confusion matrix at proper slot ([xmat][ymat]).
*/

void scan_for_tree_inc(unsigned char *full_bitmap, unsigned char *mask_data, int xmat, int ymat, int xsize, int ysize)
{
  int x, y, count1, count2;
  int64 bitnum;

  for (y = 2; y < ysize; y++)
  for (x = 2; x < xsize; x++) 
    {
    bitnum = (int64)xsize*(y-1) + x-1;  	/*bitnum starting at zero, (x,y) at (1,1) */

    /* check if 2x2 window is 'filled' */
    if ( testbit(mask_data,bitnum) && testbit(mask_data,bitnum+1) &&
           testbit(mask_data,bitnum+xsize) && testbit(mask_data,bitnum+xsize+1)
			   && testbit(full_bitmap,bitnum) )   		// test if ITC not used already (i.e., erased)
	{
	count1 = count2 = 0;
	fill(x, y, xsize, full_bitmap, &count1);
	fill(x, y, xsize, mask_data, &count2);
	confusion_matrix[xmat][ymat]++;
	if (xmat == ymat) pix_count[xmat] += count1;	/* for crown area of OK ITC */
	}
    }
}
 
/*****************************************************************************/

/*
   This function scans the image to find in the masked area (at this point, it 
   is the ANDed version of "a" training area and "an" ITC class bitmap) a minimum  
   2x2 area corresponding to a tree. When found, the ITC is filled (thus erased)
   in that bitmap and in the fuller ITC class bitmap. 
   The tree is then counted in the confusion matrix at proper slot ([xmat][ymat])
   only if more than 90% inside the test area.
*/

void scan_for_tree_exc(unsigned char *full_bitmap, unsigned char *mask_data, int xmat, int ymat, int xsize, int ysize)
{
  int x, y, count1, count2;
  int64 bitnum;

  for (y = 2; y < ysize; y++)
  for (x = 2; x < xsize; x++) 
    {
    bitnum = (int64)xsize*(y-1) + x-1;  	/*bitnum starting at zero, (x,y) at (1,1) */

    /* check if 2x2 window is 'filled' */
    if ( testbit(mask_data,bitnum) && testbit(mask_data,bitnum+1) &&
           testbit(mask_data,bitnum+xsize) && testbit(mask_data,bitnum+xsize+1) )
	{
	count1 = count2 = 0;
	fill(x, y, xsize, full_bitmap, &count1);
	fill(x, y, xsize, mask_data, &count2);
	if( count2 >= 0.9*count1 )		/* then crown is considered inside */
	  {
	  confusion_matrix[xmat][ymat]++;
	  if (xmat == ymat) pix_count[xmat] += count1;	/* for crown area of OK ITC */
	  }
	}
    }
}
 
/*****************************************************************************/

/*
   This function scans the image to find in the masked area (at this point, it 
   is the ANDed version of "a" training area and "an" ITC class bitmap) a minimum  
   2x2 area corresponding to a tree. When found, the ITC is filled (thus erased)
   in that bitmap and in the fuller ITC class bitmap. 
   The tree is then counted in the confusion matrix at proper slot ([xmat][ymat])
   only if more than 50% inside the test area.
*/

void scan_for_tree_auto(unsigned char *full_bitmap, unsigned char *mask_data, int xmat, int ymat, int xsize, int ysize)
{
  int x, y, count1, count2;
  int64 bitnum;

  for (y = 2; y < ysize; y++)
  for (x = 2; x < xsize; x++) 
    {
    bitnum = (int64)xsize*(y-1) + x-1;  	/*bitnum starting at zero, (x,y) at (1,1) */

    /* check if 2x2 window is 'filled' */
    if ( testbit(mask_data,bitnum) && testbit(mask_data,bitnum+1) &&
           testbit(mask_data,bitnum+xsize) && testbit(mask_data,bitnum+xsize+1) )
	{
	count1 = count2 = 0;
	fill(x, y, xsize, full_bitmap, &count1);
	fill(x, y, xsize, mask_data, &count2);
	if( count2 >= 0.5*count1 )		/* then crown is considered inside */
	  {
	  confusion_matrix[xmat][ymat]++;
	  if (xmat == ymat) pix_count[xmat] += count1;	/* for crown area of OK ITC */
	  }
	}
    }
}

/*****************************************************************************/

/*
   This function scans the image to find in the masked area (at this point, it 
   is the ANDed version of "a" training area and "an" ITC class bitmap) a minimum  
   2x2 area corresponding to a tree. When found, the ITC is filled (thus erased)
   in that bitmap and in the fuller ITC class bitmap. 
   The tree is then counted in the confusion matrix at proper slot ([xmat][ymat])
   only if its center of gravity is inside the test area.
*/

void scan_for_tree_cgrav(unsigned char *full_bitmap, unsigned char *mask_data, int xmat, int ymat, int xsize, int ysize)
{
  int x, y, count1, count2, a_x, a_y;
  int64 bitnum;

  for (y = 2; y < ysize; y++)
  for (x = 2; x < xsize; x++) 
    {
    bitnum = (int64)xsize*(y-1) + x-1;  	/*bitnum starting at zero, (x,y) at (1,1) */

    /* check if 2x2 window is 'filled' */
    if ( testbit(mask_data,bitnum) && testbit(mask_data,bitnum+1) &&
           testbit(mask_data,bitnum+xsize) && testbit(mask_data,bitnum+xsize+1)
			   && testbit(full_bitmap,bitnum) )   		// test if ITC not used already (i.e., erased)
	{
	count1 = count2 = sum_x = sum_y =0;
	fill_cg(x, y, xsize, full_bitmap, &count1); 
	a_x = sum_x / count1;
	a_y = sum_y / count1;
	bitnum = xsize*(a_y - 1) + a_x - 1;

	if( testbit(mask_data,bitnum) )		/* if center of gravity is inside */
	  {					/* then crown is judged inside */
	  confusion_matrix[xmat][ymat]++;
	  if (xmat == ymat) pix_count[xmat] += count1;	/* for crown area of OK ITC */
	  }
	fill(x, y, xsize, mask_data, &count2);	/* fill to erase the blob */
	}
    }
}

/*****************************************************************************/

/*
   This function scans the image to find in the masked area (at this point, it 
   is the ANDed version of "a" training area and "an" ITC class bitmap) a minimum  
   2x2 area corresponding to a tree. When found, the ITC is filled (thus erased)
   in that bitmap and in the fuller ITC class bitmap. 
   The tree is then counted in the confusion matrix at proper slot ([xmat][ymat])
   only if there is a pointer in the POSBIT bitmap pointing to it.
*/

void scan_for_tree_points(unsigned char *full_bitmap, unsigned char *mask_data, int xmat, int ymat, int xsize, int ysize)
{
  int x, y, count1, count2;
  int64 bitnum;

  for (y = 2; y < ysize; y++)
  for (x = 2; x < xsize; x++) 
    {
    bitnum = (int64)xsize*(y-1) + x-1;  	/*bitnum starting at zero, (x,y) at (1,1) */

    /* check if 2x2 window is 'filled' */
    if ( testbit(mask_data,bitnum) && testbit(mask_data,bitnum+1) &&
           testbit(mask_data,bitnum+xsize) && testbit(mask_data,bitnum+xsize+1) )
	{
	count1 = count2 = 0;
	PointMet = 0;
	fill(x, y, xsize, full_bitmap, &count1);
	fill(x, y, xsize, mask_data, &count2);
	if ( PointMet )			/* then crown is considered */
	  {
	  confusion_matrix[xmat][ymat]++;
	  if (xmat == ymat) pix_count[xmat] += count1;	/* for crown area of OK ITC */
	  }
	}
    }
}
 
/*****************************************************************************/

/* This function processes the confusion sums and generates the confusion matrix with
   percentages.  Also generate the Kappa Coefficient and Kappa Variance.
*/

void process_matrix(void)
{
	int             i, j;
	float          sum_rows[BITMAPS], totavg, totdiag, totrowcol;
	float          t1, t2, t3, t4;

	totsum = totavg = totdiag = totrowcol = 0.0;
	t1 = t2 = t3 = t4 = 0.0;
	/*
	 * Form sums for rows, cols, main diagonal, and grand sum, not
	 * including unclassified
	 */
	for (j = 0; j < nclass; j++) {
		sum_rows[j] = 0.0;
		sum_cols[j] = 0.0;
		totdiag += (float) confusion_matrix[j][j];
		for (i = 0; i < nclass; i++) {
			sum_rows[j] += (float) confusion_matrix[j][i];
			sum_cols[j] += (float) confusion_matrix[i][j];
			totsum += (float) confusion_matrix[j][i];
		}
	}

	/* Generate intermediate values for kappa */
	for (i = 0; i < nclass; i++) {
		totrowcol += (sum_rows[i] * sum_cols[i]);
		t3 += ((float) confusion_matrix[i][i] * (sum_cols[i] + sum_rows[i]));
		for (j = 0; j < nclass; j++)
			t4 += (confusion_matrix[i][j] * pow((sum_cols[j] + sum_rows[i]), 2.0));
	}

	/* Calculate kappa coefficient and kappa variance */
	t1 = totdiag / totsum;
	t2 = totrowcol / (totsum * totsum);
	t3 /= (totsum * totsum);
	t4 /= pow(totsum, 3.0);
	kappa = (t1 - t2) / (1.0 - t2);
	varkappa = (1.0 / totsum) * (((t1 * (1.0 - t1)) / pow((1.0 - t2), 2.0)) +
	((2.0 * (1.0 - t1) * (2.0 * t1 * t2 - t3)) / pow((1.0 - t2), 3.0)) +
				     ((pow((1.0 - t1), 2.0) * (t4 - 4.0 * t2 * t2)) / pow((1.0 - t2), 4.0)));

	/* Update grand total, column totals to include unclassified */
	for (i = 0; i < nclass; i++) {
		totsum += (float) confusion_matrix[nclass][i];
		sum_cols[i] += (float) confusion_matrix[nclass][i];
		totavg += ((float) confusion_matrix[i][i] / sum_cols[i]);
	}

	/* Calculate average accuracy and overall accuracy */
	avgacc = 100.0 * totavg / nclass;
	overacc = 100.0 * totdiag / totsum;
}


/*****************************************************************************/

/* This function displays the values contained in the confusion matrix, along with
   the accuracy percentages.
*/

//void view_matrix(FILE * idb_fp, int extmask, char * boundtype)

void view_matrix( int extmask, char * boundtype)
{
	int             i, j;
	//float           xpixsz, ypixsz;
	char            pxunit[10], units[10];

	// Get pixel information from file 
	
	// These are global vars now
/*	
	IDBPixelSize(idb_fp, IDB_READ, &xpixsz, &ypixsz, pxunit);
	strncpy(units, pxunit, 5);
	units[5] = '\0';
*/
	ypixsz = ABS(ypixsz);
	strncpy(units, "Metre", 5);
	
	/* Display actual matrix */

	fprintf(Report, "\nConfusion Matrix from ITCCA    (Criteria = %s)", boundtype);

	if (pointmode) fprintf(Report, "\t N.B.: Crown pointers were used. They are from BM:%4d", extmask);
	fprintf(Report, "\n\n");

	for (i = 0; i < nclass; i++) fprintf(Report,"%8d    ",testseg[i]);
	fprintf(Report, "Test / Class bitmaps\n");
	for (i = 0; i < 12 * (nclass + 1); i++) fprintf(Report, "-");
	fprintf(Report, "\n");
	for (i = 0; i <= nclass; i++) {
	  for (j = 0; j < nclass; j++)
	    fprintf(Report,"%4d (%4.1f%%)", confusion_matrix[i][j],
			      confusion_matrix[i][j] * 100.0 / sum_cols[j]);
	  fprintf(Report,"    | %4d \n", classbit[i]);
	}

	/* Display the other values */

	for (i = 0; i < 12 * (nclass + 1); i++)  fprintf(Report, "-");		// line with well calculated length
	fprintf(Report, "\n");
	for (i = 0; i < nclass; i++)
		fprintf(Report, "%4d        ", (int) sum_cols[i]);
	fprintf(Report, "     %5d\n", (int) totsum);

	fprintf(Report, "\nAverage Accuracy: %5.1f%% %15s", avgacc," ");
	fprintf(Report, "Kappa Coefficient: %8.6f\n", kappa);
	fprintf(Report, "Overall Accuracy: %5.1f%% %15s", overacc," ");
	fprintf(Report, "Kappa Variance:    %8.6f\n", varkappa);

	fprintf(Report, "\nAverage Crown Area (of correctly classified crowns)\n\n");
	for (i = 0; i < nclass; i++)
	  fprintf(Report, " %7.2f    ", (float) pix_count[i] / (float) confusion_matrix[i][i]);
	fprintf(Report, " (Pixels)\n");

	for (i = 0; i < nclass; i++)
	  fprintf(Report, " %7.2f    ",((float)pix_count[i] * xpixsz * ypixsz )
										 / (float) confusion_matrix[i][i]);
	fprintf(Report, " (Sq %5s)\n", units);

	fprintf(Report,"\nPixel size is %g x %g %s \n", xpixsz,ypixsz,pixunit);

}

/*****************************************************************************/


/* This function converts a string to upper case characters */

void upper_case(char *c)
{
	while (*c != '\0') {
		if (*c >= 'a' && *c <= 'z')
			*c += ('A' - 'a');
		c++;
	}
}

/*****************************************************************************/

/*
   This function checks that the input parameters set in EASI/PACE by
   the user are valid.  Invalid parameters will produce an error
   message and cause a program exit.  */

void check_parameters(char *boundtype) 
  {
  upper_case(boundtype);

  if ( (strncmp(boundtype,"INC",3) != 0) && (strncmp(boundtype,"EXC",3) != 0)
		&& (strncmp(boundtype,"AUTO",4) != 0) && (strncmp(boundtype,"CGRAV",5) != 0) 
		&& (strncmp(boundtype,"POINTS",6) != 0) )
	{
	fprintf(stderr, "\n*** Invalid BITBOUND value was used.\n");
	fprintf(stderr, "\nPlease use INC or EXC or AUTO or CGRAV or POINTS.\n");
	exit(-1);
	}
  }

/**************************************************************/

/* tell whether the first value (a) is between the other two (b,c) */
/*
int between(float a, float b, float c)
{
  if( (c > b) && (a<c) && (a>=b) ) return(TRUE);
  if( (b > c) && (a<b) && (a>=c) ) return(TRUE);
  return(FALSE);
}

*/
         
/*********************************************************************************/

/* This function expand parameter vector that contain ranges (ala PCI: 10,-13 not 10-13)

	in_count	number of item in input list
	in_vect		input segment(channel) list possibly including ranges
	out_vect	output expanded list of segments (channels)
	out_count	number of item in output list
*/
void param_expand(int in_count, int *in_vect,  int *out_vect, int *out_count)
{
	int ii, jj, kk;
	
	for(ii=0; ii<BITMAPS; ii++) out_vect[ii]=0;		// zero vector for good measure 
	
	if(in_count == 0)  { *out_count = 0; return; }

	if(in_vect[0] < 0)
	  	{ fprintf(stderr,"\n##### ERROR - A range (neg.#) can not be first item.\n"); exit(-1); }
	
	kk=0;
	for (ii = 0; ii < in_count; ii++)
	  {
	  if(in_vect[ii] == 0) 
	  	{ fprintf(stderr,"\n##### ERROR - Segment number can not be zero \n"); exit(-1); }
	  if(in_vect[ii] > 0) 
	  	{ out_vect[kk] = in_vect[ii]; kk++; }
	  if( (in_vect[ii] < 0) && (abs(in_vect[ii]) <= in_vect[ii-1]) )
	  	{ fprintf(stderr,"\n##### ERROR - A range appears to be unacceptable.\n"); exit(-1); }
	  if(in_vect[ii] < 0) 
	    {
	    if ( (abs(in_vect[ii]+in_vect[ii-1]) + kk) > BITMAPS )
	  	{fprintf(stderr,"\n##### ERROR - Expanded list limited to %d segments.\n",BITMAPS); exit(-1); }
	    for(jj=0; jj<(abs(in_vect[ii]+in_vect[ii-1])); jj++) 
	    		{ out_vect[kk] = out_vect[kk-1] + 1; kk++; }
	    }
	  }
	*out_count = kk;

}	/* end of function */

/*********************************************************************************/
/****************************************************************************/
