/*
Program name: 	itcmg_g.cpp (for GDAL)
Author: 	Francois A. Gougeon
Date:		March-April 2020 (COVID-19 version)

**********************************
C+
C	ITCMG.cpp    (ITC Mask Generator)
c
c 	ITC Mask Generator - Generates LIT/SHADED/TT masks
C
C	This is a program for the PCI EASI/PACE Image Analysis System that takes the
C	bitmap generated by ITCISOL and the same illumination channel to generate a bitmap
C	assumed representative of the lit side, shaded side, or top of tree crowns (i.e., MAX).  
c	This bitmap may be used as "extra bitmap" mask (EXTBIT) in ITCSSG and ITCSC
c	to create signatures and classify trees using only that "purer" part of the crown.
c
c	Optionally (for research purposes), the bitmap of automatically delineated 
c	crowns (ISOLBIT) can be replaced by a vector layer of manually delineated crowns.
C
C
C1	PARAMETERS
C
C
C	ITCMG is controlled by the following global parameters:
C
C	Name		Prompt						Count	Type
C
C	FILE		PCI File Name					132	Char
C	ILLUMCH		Illumination Channel				1	Int
C	ISOLBIT		Bitmap from ITCISOL				1	Int
C	EXTBIT		Extra bitmap mask to be created			1	Int
C	MASKTYPE	Mask Type:  LIT/SHADE/TOP			64	Char
C
C
C2	FILE
C
C	Specifies the name of the PCIDSK file containing the input images.
C
C	EASI>FILE="filename"
C
C2      ILLUMCH
C
C       Specifies which channel is the illumination channel.  
C	This is the channel which is used by the Mask Generator program in order 
c	to generate the bitmap mask and should be the same used with ITCVFOL.
C
C	EASI>ILLUMCH=n		Only one channel is allowed
C
C2	ISOLBIT
C
C	Specifies a bitmap produced by the ITCISOL (Individual Tree Crown
C	Isolation) program to be used as a mask of the image.  This bitmap
C	is scanned to determine the locations of the individual trees, and
C	thereby build up the specified mask type.
c
c	Optionnaly, for RESEARCH PURPOSES, the bitmap of automatically  
c	delineated crowns (ISOLBIT) can be replaced by a vector layer of
c	manually delineated crowns (as in TREETYPE="MANVEC in ITCDUMP)
c
c	EASI>ISOLBIT=n
C
C2	EXTBIT		Extra Bitmap
C
C	Specifies a segment to which the generated bitmap mask will be written to.
C	If a segment is not specified, or if a segment is not valid, a new segment
C	will be created to contain the information.
C
C	EASI>EXTBIT=n
C
C2	MASKTYPE
C
C	Specifies which type of mask should be generated.  Possible values
C	are:  LIT/SHADE/TOP.
C
C	EASI>MASKTYPE="type"
C
C	LIT creates a mask of the "lit" side of a tree.  That is, parts of the tree
C	crown which have values in the illumination channel above the average value for
c	that crown (typically, on the lit side of a conifer tree or toward the
c	center of crown for hardwood (flatter) trees). Theoretically, this will permit
c	the creation of "purer" spectral signatures devoided of shade pixels.
C
C	SHADE creates a mask of the "dark" side of the tree.  That is, parts of the
C	tree which have values in the illumination channel below the average of that
C	channel.
C
C	TOP creates a mask of what may be consider the tree top (highest point in the tree).
C	The most brilliant pixel in the illumination channel (for each tree) is used
C	to mark the location of the tree top.
C
C
C1	DETAILS
C
C       ITCMG
C
C       This is a program that takes the bitmap from ITCISOL (ISOLBIT) and the
C       illumination channel, and generates a bitmap mask, of the lit side, shaded
C       side, or top of the trees.  This bitmap may be used as input in ITCSSG and
C       ITCSC.
C
C
C	The following general process is followed by ITCMG:
C
C	The user-specified illumination channel (ILLUMCH) and isolation bitmap (ISOLBIT) are
C	checked and then read from the PCIDSK file.  Space for the output bitmap mask is
C	allocated as well.  The program then begins scanning the isolation bitmap until a
C	tree has been found.  From then on, building of the mask depends on the type of
C	mask that the user has specified to be generated.  Once a tree has been processed,
C	the program continues searching for and processing another tree until all the trees
C	in the isolation bitmap have been checked.  The resulting output bitmap mask
C	is then written to the user-specified segment, or a newly created segment.
C
C
C2	BITMAP MASK GENERATION
C
C	If the user specifies the LIT mask type, the following process is used to generate
C	the bitmap mask:
C
C	For each pixel in the tree, the system scans the data at the same location
C	in the illumination channel and builds up the sum of all the illumination values.  The
C	average value of the illumination channel for that particular tree is then calculated.
C	The tree is then scanned a second time, and any pixel that is encountered with a value
C	in the illumination channel above the average for the channel is kept and written (in
C	the same location) onto the output bitmap mask.
C
C	If the user specifies the SHADE mask type, the following process is used:
C	For each pixel in the tree, the system scans the data at the same location
C	in the illumination channel and builds up the sum of all the illumination values.  The
C	average value of the illumination channel for that particular tree is then calculated.
C	The tree is then scanned a second time, and any pixel that is encountered with a value
C	in the illumination channel below the average for the channel is kept and written
C	(in the same location) onto the output bitmap mask.
C
C	If the user specifies the TOP mask type, the following process is used:
C	For each pixel in the tree, the system checks the value in the illumination channel at
C	the same location and compares it to the largest illumination value it has found so
C	far in the tree.  If the value it has just checked is less than the largest found so
C	far, the value is disposed of and the system gets the next pixel in the tree.  If
C	the value is greater than the largest found, the largest is replaced with the new
C	value and the position of the pixel in the tree is recorded.  The process then continues
C	with the next pixel.  Once all pixels in the tree have been checked, the pixel that
C	has the largest value is plotted onto the output bitmap mask.
C
C
C2	MASK TYPES
C
C	Three different masks can be generated by ITCMG.  These include LIT,
C	SHADE, or TOP.
C
C       LIT creates a mask of the "lit" side of a tree.  That is, parts of the tree
C       which have values in the illumination channel above the average of that
C       channel.
C
C       SHADE creates a mask of the "dark" side of the tree.  That is, parts of the
C       tree which have values in the illumination channel below the average of that
C       channel.
C
C       TOP creates a mask of what may be the tree top (highest point in the tree).
C       The most brilliant pixel in the illumination channel (for each tree) is used
C       to mark the location of the tree top.
C
c	
C1	REVISION HISTORY
C
c	François A. Gougeon, Ph.D.
c	Remote Sensing Research
c	
C	(©)Natural Resources Canada
c	Canadian Forest Service 
c	Pacific Forestry Centre
c	506 West Burnside Rd.
c	Victoria, British Columbia, 
c	Canada, V8Z 1M5
c	
c
c
c	Ron Petrick  Version 1.0 November 1994	
c
c		-Creation, ANSI C Version, PCI V5.3
c
c	Simon Alexander Version 1.1 December  1996
c
c			- Convert to handle 16bit images,  clean up memory handling, 
c			starting integration to the ITC Suite. )
c
c	Francois Gougeon  Version 1.2	May 97	
c
c			- To speed up by using macros instead of functions
c			for bit operations and 2x2 detection of minimun crowns
c
c	Francois Gougeon  Version 1.3	Aug. 97
c
c				- Various clean-ups
c
c	Francois Gougeon  Version 1.4	July 98
c
c				- Various clean-ups
c
c	Francois Gougeon  Version	2.0	June 99		
c
c					- Modified to allow masks to be generated for
c					  manual tree crowns from a vector layer (polygons).
c					  Lots of classification tests are performed with
c					  manually delineated tree crowns.
c					- Replaced parameter DBOS by EXTBIT to improve flow 
c					  of programs when using the ITC suite
c
c	Francois Gougeon  Version	2.1	Sep. 99	
c
c					- Removed requirements of minimum of 2x2 block for
c					  manual (vector) tree crowns.
c					- Maintained requirement that center of gravity
c					  must be inside the tree crown for manual crowns.
c					- Counting and reporting on tree crowns that are
c					  not meeting the above criteria with "unusedITC".
c
c Geoff Savinkoff  V2.2	Oct. 2001	
c
c					- Added global Lines, Pixels (to compile with itc_io)
C
c v2.21	Nov. 2001	François A. Gougeon
c
c					- Updated help file with linking information and EASI prompts
c					- Replaced most IDB functions with GDB functions (not IDBPixelSize or ISBSegInfoIO
c					  as there are no equivelant GDB functions)
c					- Defined xsize, ysize, channels as local variables to pass to functions to be
c					  consistent with other programs.
c					- Changed segment description to make more generic.
c					- Now uses safety_zone function from itc_io.
c					- Updated to display time at start and end of program
c					- eliminated unreferenced variables (so PC compiler does not complain)
c
c
c v2.3	April 2007	François Gougeon
c
c				- Minor adaptations for PCI v10 and its new PRM.PRM file 
c				  Most PCI routines are in PCI1000.dll, but not all.
c				  For example, IMPTime() and IMPReturn() are now in Core1000.dll
c				  and IMPCounter() in Counter1000.dll
c				  Since I dont have PCISDK or PCIProSDK, I had to create LIBs 
c				  from their DLLs to compile my progs.
c				  - Also, problem with the REPORT (*Report) Variable
c
c
c v2.4	Sept. 2007	François Gougeon
C
c				- Updated to be more flexible with number of vertices per polygon
c				  (previous version was limited to 150 vertices of storage)
c				- Fix a problem with the convertion from georeferenced vectors to
c				  image coordinates (i.e., remove two fabs() in equations), mostly
c				  so that Northing diminishes with increasing Y image positions.
c				  (i.e.,  transformY should always be a negative number)
c
c
c v2.5	Jan 2008	François Gougeon
c
c				- Link adaptations for PCI v10.n and its new incompatible PRM.PRM file 
c				  and use of compiler (VS*8) wanting to produce more secure code.
c				  Most PCI routines are in PCI1000.dll, but not all.
c				  For example, IMPTime() and IMPReturn() are now in Core1000.dll
c				  and IMPCounter() in Counter1000.dll
c				  Since I dont have PCISDK or PCI/ProSDK, I had to create LIBs 
c				  from their DLLs to compile my progs (same for PCI 10.1)
c
c				 - Problems with the REPORT (*Report) Variable in Core1000.dll
c				   First use of report makes program crash (i.e., after the start message)
c				   So declared set global var			 FILE *Report;
c				   and do immediately after call to IMPSTATUS()		
c					if(EQUALN(report,"TERM",4)) {Report=stdout;}else{Report = fopen(report, "w");}
c
c
c v2.6	 July 2009	François Gougeon	
c
c				- Modified to handle bigger images (bigger than available memory)
c				by reading and analysing them by sections.
c
c v2.7	 Sept. 2009	François Gougeon
c
c				- Modified to handle bigger images (bigger than available memory)
c				by reading and analysing them by sections IN A SEAMLESS WAY
c				- The above is not available for manually delineated crowns in a 
c				vector layer (a research-oriented option). That case only works
c				when the full image can get into memory.
c
c v2.8	 Jan. 2012	François Gougeon
c
c				- Modified to handle bitmaps bigger than 2G positions by reading them
c				in two sections (i.e., the old PCI functions that I have access to
c				are not up to par yet). Itc_io.c was modified to take care of that.
c				- Bitops.c was also modified to use int64 vars to use with pointers 
c				for operations on bitmaps. Calls to setbit(), testbit(), etc.
c				have to be modified to use an (int64) pointer, typically by casting.
c				- Thus, "bitnum" need to be declared "int64 bitnum" everywhere
c				- Be careful of parenthesis as they may prevent "auto casting" to int64
c				from working (i.e., calculation gets done in int32, then cast to int64
c				with bad results. For exemple:
c				"bitnum = (int64) ((y-1)*Pixels) + x-1;" 
c				should be: "bitnum = (y-1)*(int64)Pixels + x-1;"
c				- Capable of dealing with FILENAME (thus path) up to 132 chr long. as per 
c				new standards (PCI > v10.n)
c
c v2.9	 June 2013	François Gougeon
c
c				- Modified as above, but for manual trees in vector format
c				- NOTE: 
c					Manual trees must be of reasonable tree size (a few trees at most), not  
c					training areas. TAs that are too big will just crash the recursive fill()
c
c
c v3.0	 June 2013	François Gougeon
c
c				- Major mods for manual trees in vector format. 
c				The image is read as needed for each individual tree.
C					CANCELLED !!!!
c
c v4.0	 Jan.  2014	François Gougeon
c
c				- Manual trees in vector format are just burned in one shot
c				into the internal bitmap of ISOLs
c 
c
c v4.1	 Feb.  2015	François Gougeon
c
c				- Manual trees in vector format are NOW burned *one by one* and lit side
c				  is extracted for one tree at a time, leading to "correct" lit sides, 
c				  specially if trees (manual trees) are touching (done via loop_for_mantree() )
c				  (or within one pixel) or overlapping
c				- Fixed image_sum and image_avg sometimes considered (int32) sometimes (float)
c
c v4.2	 March  2015	François Gougeon
c
c				- Fixed to work by image sections for big images (rarely needed, because only 
c				a single channel is needed for ITCMG) even for polygon trees in a vector layer
c				- Fixed for polygon trees that have their centre of gravity outside their crown
c				- Changed to better vec2rast() from ITCSSG (pre-convertion to image coordinates)
c				because much faster
c
c
c v5.0	March 2016	François Gougeon
c
c			- Changed to a C++ program to deal with versions of PCI > v10.2
c				int main (), ".cpp" name, and extern "C" around .h include files
c			- mod to some call to fit new library definitions (as per .def demangling)
c			  which also means mods to corresponding declaration .h files (e.g., gdb.h)
c			  (Since I dont have PCISDK or PCI/ProSDK, I have to create LIB and DEF from
c			  from their DLLs (via DUMPBIN and LIB) in order to compile my progs
c			- modules in files like gdb.h need to be declared 'extern "C++" to link
c			  with proper name mangling (MSVC++ mangling)
c			- ***WORKED**  for PCI 10.3 that migrate its LIB to c++, 
c
c			- HOWEVER, more stuff is needed for PCI 2015 (64bit)
c			- PCI LIB need to be /MACHINE:x64 
c			  and prog compile with 64b version (i.e., vcvarsall amd64)
c			  cause all the call to lib are now with 64bit pointers 
c			- IMPStatus()  uses "char const *", so mod. that in ccltask.h (no mod in prog.)
c
c
c v6.0	Sept 2016	François Gougeon
c
c			- Program was dealing with bitmaps > "2G positions", but had not been
c			  adjusted for bitmap > 2G Bytes (i.e., (int64)bmsize, (int64)iii)
c			- Also, there was issues reading pixel values in image sections > 2GB
c			  as (int64) had not been used everywhere.
c
c
c v7.0a	March 2020	François Gougeon
c
c	- Modified program for the GDAL environment and variables on command line
c	from ITCMG.cpp v6.0 coded for the PCI environment
c
c	- Easely done for image and bitmap. More difficult for manual trees (polygons)
c
c	- Removed excess bagage (i.e., the purely PCI related stuff)
c
c	- ????Removed possibilties of working by image sections as most modern computers 
c	  have lots of memory
c
c	- Toyed with the idea of using single very complete program to deal both 
c	with PCI OR GDAL using conditional compiling
c
c
c v7.1a	April2020	François Gougeon
c
c	- Created generic input/output functions to be used by other GDAL program 
c	in the ITC Suite, like image_in(), bitmap_in(), ... later moved to itc_ic_g.cpp
c	as read_image(), read_bitmap(), write_bitmap(),... to be used by all Suite prog.
c
c	- Org. to work with 16 bit images
c
c
c v7.2	July 2020	François Gougeon
c
c	- Org. to deal with a varietty of input parameter (variable) syntax
c	like:	SECTEUR_FG.pix,5 rather then user Q/A
c
c  v7.3	April 2023	François Gougeon
c
c			- Not to assume that all files are in the default directory from which the program is run
c				Previously, everything was assumed in same directory and run from a cmd window from there.
c				NOW, the path used with the main input file is used when creating the default output files
c				This was necessary for ArcGIS Toolkit integration.
c
c
c  v7.4	Nov. 2024	François Gougeon
c 
c			- Some minor cleanup
c
c
c********************************************************************************
c
c	PROGRAM USAGE EXAMPLE
c
c
c	itcmg_g SECTEUR_FG_Sub_CH5.tif SECTEUR_FG_Sub_BM7.tif LIT
c
c	Using PCI Variable Notation:
c		itcmg_g   ILLUMCH  ISOLBIT  MASKTYPE
c
c	Program will create "ITCMG_BM.tif" that you can rename later
c
c	> itcmg_g SECTEUR_FG_CH5.tif ISOL_BM.tif LIT	(most typical)
c
c	IF some input files are PCI files OR other multi-feature files
c	an additional question will be asked about channel or bitmap 
c	number to use (in GDAL, bitmap numbers are sequential # after last 
c	channel number, if 5 channel, first bitmap is Ch6; and vector layers
c	are independent, starting at 1)
c	Please use "gdalinfo" and "ogrinfo" on files to find out numbering scheme)
c
c	Usuage with manual trees and other notations:

	> itcmg_g SECTEUR_FG_CH5.tif SECTEUR_FG_VEC2.shp LIT

	> itcmg_g SECTEUR_FG.pix SECTEUR_FG_VEC2.shp LIT

	> itcmg_g SECTEUR_FG.pix SECTEUR_FG.pix LIT	
	NOTE: 2nd file will ask which bitmap or vector layer to use

	> itcmg_g SECTEUR_FG.pix,5 SECTEUR_FG.pix,2 LIT	
	NOTE:	Will use CH5 (as ILLUMCH) and segment 2 (bitmap or vector)
			as ISOLBIT (vecttors for manual trees)
	

*************************************************************************8

*** To compile with Visual Studio (VS14)  (see VS14_GDAL_compile.txt)

call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

set INCLUDE=C:\gdal-2.1.1_v2\include;C:\libtiff-4.0.6_64b\tiff-4.0.6\libtiff;%INCLUDE%
set LIB=C:\gdal-2.1.1_v2\lib;C:\libtiff-4.0.6_64b\tiff-4.0.6\libtiff;%LIB%

set LINK=gdal_i.lib  libtiff_i.lib User32.lib

set CL= /MD

CL xxxxxxxxx.cpp /EHsc

***********************************************

NOTE: Newest GDAL library have included "libtiff" no need to have it anymore

set INCLUDE=D:\GDAL_3.0.0\include;%INCLUDE%
set LIB=D:\GDAL_3.0.0\lib;%LIB%
set LINK=gdal_i.lib  libtiff_i.lib User32.lib
set CL= /MD
CL xxxxxxxxx.cpp /EHsc

set path=D:\GDAL_3.0.0;%PATH%		// to run programs

***  GDAL v3.0.0 has problem getting to its projection library, so do:

set PROJ_LIB=D:\GDAL_3.0.0\projlib



*********************
Ackowlegment to GDAL:

GDAL - Geospatial Data Abstraction Library: Version 2.1.1 (July2016, 64bit), 
GDAL - Geospatial Data Abstraction Library: Version 3.0.0 (Dec. 2019, 64bit),
Open Source Geospatial Foundation, 
Thanks Frank (Warmerdam)


*******************************************************************************************
******************************************************************************************

*/

#define VERSION "v7.4a"
#define FILENAME    132
#define PROG_NAME "ITCMG_G"
#define MASKTYPES   3
#define LIT_MASK    0
#define SHADE_MASK  1
#define TOP_MASK    2
#define ILLUM_AVG   10
#define BORDER 3
#define MAX_INTERCEPT 100

#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>     /* malloc, free, rand */
#include <string.h>
#include <math.h>
#include <limits.h>
#include <time.h>       // time_t, struct tm, time, localtime

/*
extern "C" {
#include "pci.h"		// soon, will not be needed
#include "itc_io.h"
#include "error.h"
#include "bitops.h"	
	}
*/


#include "gdal_priv.h"		// For GDAL library
#include "ogrsf_frmts.h"	// For OGR
#include "ogr_core.h"		// Necessary ??
#include "ogr_api.h"		// Necessary ??

#include "itc_io_g.h"		// my newest GDAL image/bitmap input/output

#include "bitops.h"	// bit operations on bitmaps (mostly macros to be faster)


//typedef unsigned char  PixVal;		// should all be in itc_io.h
//typedef long           int64;
//typedef unsigned long  uint64;


/* structure definition for tree node */

typedef struct tree 
	{
	int	count;			/* # of pixel in crown */
	int	image_sum;		/* accumulates pixel values to get average of crown */
	int 	image_avg;		/* stores average of crown illumination*/
	int	crown_max;		/* to store ongoing and final crown maxima for TT assesment */
	int64	tt_pos;			/*  to store ongoing and final TT position (a bit number) */
	struct tree    *next_tree;
	} tree_node;


/* function declarations */

void            check_parameters(char *);
void            fill(int, int, int, unsigned char *, tree_node *, int);
void            fill_vs(int, int, int, unsigned char *, tree_node *, int);
void            process_image_data(int64, int64, tree_node *, int);
tree_node      *new_tree_node(void);
void            add_to_tree_list(tree_node *, tree_node *);
void            scan_for_tree(int, int, unsigned char *, int);

void 		loop_for_mantree_g(char *,int, int, unsigned char *, int, int);

void            write_segment(FILE *, int, int, int, char *);
void            upper_case(char *);
char           *itostr(int *, int);
void 		vect2rast_g(int, GDBVertex2D *, unsigned char *, int, int, int);
int  		between(float a, float b, float c);
//void		poly2bitmap(int , int , unsigned char *, int , GDBLayer );



//void 		check_mem(void *);
//void 		safety_zone(unsigned char *);

//PixVal 	*image_in(char *);	// replaced by read_image() in itc_io_g, etc
//PixVal	*bitmap_in(char *);
//PixVal 	*image_out(char *);
//void 		bitmap_out(PixVal*, char *);

PixVal 		*vector2bitmap(char *);

//int32 	get_u8(void * , int64 );

/* Global declarations */

//typedef unsigned char  PixVal;	// should all be in itc_io.h
//typedef long               int64;
//typedef unsigned long      uint64;



/* Global vars */

static char	*MaskType[MASKTYPES] = {"LIT", "SHADE", "TOP"};

//PIX_FUN_PTR	get_pix_val = get_u8;

extern PIX_FUN_PTR get_pix_val;		// will get it from itc_io_g when image gets checked

//PixVal 	*illum_ima;
void 		*illum_ima;

PixVal   	*maskbitbuf, *isolbitbuf;
PixVal		*tempbitbuf;
int			Pixels, Lines, Channels;

int			by_lines=0, by_image=1;			// default is to read/write by image (faster)
int			bylines_flag = 0;		// by default proceed by full images (not by lines)

char 		description[128];		// for PCI
char 		Description[128];		// for GDAL via itc_io_g.cpp

char 		Extension[10]="";

float		xpixsz, ypixsz;
int         blocks, option;
int64 		bmsize;		// size of bitmap in bytes 

char		pixunit[40];
int			xcg, ycg;		// center of gravity (aprox.) of current man tree 
int 		unusedITC=0, usedITC=0;
int			sect_no=1,	dbiw[4], imaoffset=0;
int			retposx=0, retposy=0, next_sect=0;
int64		minpos, maxpos;
int			ixmin, ixmax, iymin, iymax;
int			iiii;

FILE        *idb_fp;
FILE 		*Report;
int         illumch;

time_t rawtime;
struct tm * timeinfo;

GDALRasterBand	*piBand,*piBand2,*poBand;
char 		illumin_fname[132];
PixVal		*pafScanline;
char 		*Proj, *Proj2, *Datum, *Datum2, *Temp, *token;
double		adfGeoTransform[6], adfGeoTransform2[6];


char	*filename, *filename1, file_out[132];
char	fullfilename[132], extension[10], extension2[10];
char 	basefname[132];
char	*pch;		// generic dummy pointer to chr array

GDALDataset	*ima_in, *bmp_in, *bmp_out, *seg_in;
GDALDataset	*vfol_bmp, *nf_bmp;


char **papszOptions = NULL;

/* additional Global Variables to deal with input vector layer */

int 		vmode = 0;  	/* vector mode flag - if set, polygons of manual tree crowns are being used */
//GDBLayer 	hlayer, tlayer;
double 		topleftX, transformX, topleftY, transformY; 	 /* for geographic mapping */
//ProjInfo_t	sProj;
char 		geosys[17];
int		segtype;
char		segflag, segname[9], segdepinfo[224];
long 		start, length;
const char 	*FieldFormat;
//GDBField	sField, *pField;
//int		iField;

;
int		sect_overlap;
int 		ch_in=1, ch_out=0, in_ch[1], segm_in=1, in_segm[1];

OGRLayer  	*piLayer, *poLayer;
OGRFeature 	*piFeature, *poFeature;
OGRFeatureDefn	*piFDefn, *poFDefn;
OGRFieldDefn	*piFieldDefn, *poFieldDefn;
OGRSpatialReference *piSRSIn,  *poSRSIn;
OGRGeometry 	*piGeometry, *poGeometry;

int 		iFeat, iField, layer_count, feat_count, field_count, last_feat, last_field;
int			oFeat, oField;
char 		*piFieldName;
//char 		**papszOptions;

int 		imaFile_opened = 0;		//image file not opened, need to be open by read_ima()
int			data_type;			// 8bit or 16bit image (gets set when image is being open by itcio_g.cpp)

//***************************************************************************

// Main program 

//***************************************************************************
	
int main(int argc, char *argv[])
{

// local var list 

	int		channels;
	char	timedate[17];
	char	file_ima[FILENAME], temp[FILENAME], file_seg[FILENAME], file_short[FILENAME]; 
	char	*temp1, *temp2, *temp3, *temp4;
	
	
	int		xsize, ysize;	// Local equivalent of Pixels and Lines

	int             isolbit;
	int             extbit;
	char            masktype[64];
	int64		mem_needed, mem_needed_BM, mem_needed_IMA=0, mem_needed_TOT, 
				mem_avail_IMA, mem_avail_SYS;
	float		numbuf[1];
	int		actval, sect_siz=0;
	int		no_8bCHs=0, no_16bCHs=0;

	int 		i,j,ii,jj;
	int64 		bitnum,count;
	char          report[FILENAME];

	int		no_of_sections = 1;
	int64		image_siz;
	
	char 		 answer[10];

	int 		PCI_File = 0;			// initial flags for image file type
	int 		TIF_File = 0;
	int			no_items, ch_no;
	char		* input_items[10];
	char		*p;

//*****************************************************************

/*
	void           *args[6];
	int             argcnt[6];

// For PCI environment assign parameter pointers to argumnets 

	args[0] = (void *) file;
	args[1] = (void *) &illumch;
	args[2] = (void *) &isolbit;
	args[3] = (void *) &extbit;
	args[4] = (void *) masktype;
	args[5] = (void *) report;

// setup standard interface for PCI environment 

	IMPStatus("FILE, ILLUMCH, ISOLBIT, EXTBIT, MASKTYPE, REPORT;",
		  "C,    I,       I,       I,      C,        C;",
		  "132,  1,       1,       1,      64,       132;",
		  "1,    1,       1,       0,      1,        1;",
		  "ITCMG.", "FORCE", argcnt, args, argc, argv);

*/

//*****************************************************************************

//	Check input parameters and open files

//*****************************************************************************

// Print Program Header 

	time (&rawtime);  timeinfo = localtime (&rawtime);
	printf("\n\t\tStarting %s (%s) at %s\n", PROG_NAME, VERSION, asctime(timeinfo));

// Registers for all types of files with GDAL

	GDALAllRegister(); 	

// ***************

// Check *First argument* on command line

	if (argc < 3) 
	  {
	  printf("\n\t *** PROBLEM with INPUTS parameters \n");
	  printf("Have an image as first argument on the command line\n");
	  printf("Typically, the same channel (e.g.,smoothed nIR) used to create the ITCs \n\n");
	  printf("USAGE: itcmg_g ILLUMCH ISOLBIT  MASKTYPE ... Output will be ITCMG_BM.tif\n");
	  exit(1);
	  }   

	//printf("1st argument - Illumination image full entry : %s \n\n", argv[1]);

// Check if a channel number is attached to file name

	ch_no = 1;		// default value, if nothing changes
	strcpy(temp, argv[1]);  p = strtok(temp, " ,"); no_items = 0;
	//printf(" Temp :  %s \n", temp);
	strcpy(file_ima, temp);	
	//printf(" Filename :  %s \n", file);
	p = strtok(NULL, " ,");			// next item
	if(p != NULL) ch_no = strtol(p,NULL, 10);	

	printf("Full IMA Filename :  %s \n", file_ima);
	printf(" Channel no. : %d \n", ch_no);	


// Open input file(PCI or TIF) via GDAL and read image (asking for channel # as needed)
	
	ima_in = open_imaFile(file_ima);
	
	illum_ima = read_image(file_ima,ch_no);		// READ INPUT IMAGE via itc_io_g.ccp, (pointer to image data)

	xsize = Pixels; ysize = Lines;

	//printf("\nMain File Extension : %s \n", Extension);
		
// Extension is a global parameter set by Open_imaFile()
	
	if (EQUALN(Extension,"pix",3)) PCI_File = 1;	// everything is in the PCI file
	if (EQUALN(Extension,"tif",3)) TIF_File = 1;	// everything is in directory, mostly as tif files

	if (! ( PCI_File || TIF_File))
	  {
	  printf("\n\n**ERROR** Program not able to deal with image file of type %s\n\n", Extension);
	  exit(-1);
      }
	
	
//***********************************************
	
// Check *Second argument* on command line  ISOLBIT  

	if (argv[2] == NULL) 
	  {
	  printf("\n\t ### ERROR ### A second argument is needed \n");
	  printf("\nSecond argument should be the ISOL bitmap.\n");
	  printf("\nSecond argument could be a vector layer of manual trees.\n");
	  exit(1);
	  }	  
	printf("\n**Checking ISOL bitmap (or manual tree layer) as per : %s \n\n", argv[2]);
 
  
// Checking that file extension to see if pix, tif, or shp file
		
// Get 2nd filename and Check if a Segment number is attached to file name

	segm_in = 0;		// default value, if nothing changes
	strcpy(temp, argv[2]);  
	
	strtok(temp, " ,");
	strcpy(file_seg, temp);		
	//printf("  2nd Filename : %s \n", file_seg); 

	strcpy(temp, argv[2]);	
	strtok(temp, ".");
	strcpy(file_short, temp);		
	//printf("  2nd File short name :  %s \n", file_short); 
	
	temp1 = strtok(NULL," ,");
	strcpy(extension2, temp1);	
	//printf("  2nd File extension:  %s \n", extension2);
	
	if ( strncmp(extension2,"pix",3) != 0 )	goto NOT_PCI;
	
	temp2 = strtok(NULL," ");
	//printf(" temp2 :  %s \n", temp2);
	if( (temp2 == NULL) && (strcmp(extension2,"pix")== 0) ) printf("\nA segment may be needed here ...????.\n");
	if( (temp2 == NULL) && (strcmp(extension2,"pix")== 0) )  goto PCI_Ask;


// Is there a "V" in there  (i.e., vector mode)

	temp3 = strtok(temp2, "vV"); 			
	//printf(" temp3 :  %s \n", temp3);

	if ( !(strcmp(temp2,temp3) == 0)) {vmode = 1; printf("***Vector mode \n");}

	if(temp3 != NULL) segm_in = strtol(temp3,NULL, 10);	

	//printf("  Filename :  %s \n", file_seg);
	printf("  Segment no. : %d \n", segm_in);	  
 
	//exit(1);
	


// If PCI file (and segment not yet define), ask user for layer number (within bitmap/vector layers)

PCI_Ask:		//  NOT WORKING PROPERLY !!!!

	if ( (strncmp(extension2,"pix",3) == 0) && (segm_in == 0) )
	  {
	  printf("\nMore than one bitmap/vector layer in that PCI file. Which one to use? ");
	  scanf("%d", in_segm);	
	  segm_in = in_segm[0];	

	 
// Need to check IF bitmap or vector layer (mostly for manual trees)

	//seg_in = ima_in;		// for the moment assuming NOT DEALING with two distinct PCI files

	seg_in = open_imaFile(file_seg);		// that works (could be separate pix file), but more verbose



CHECK_VEC:
	
	// Check if  VECTOR layer (are there any?)

	layer_count = seg_in->GetLayerCount();
	if(layer_count == NULL) 
			{ printf("\n\t*There are no vector layer in this file \n"); goto CHECK_BM;}
	printf("\n\t*Number of vector layers in PCI input file is %d \n\n", layer_count);


//exit(1);


	piLayer = seg_in->GetLayer(segm_in-1);	// Layer numbers start at zero
	if(piLayer == NULL)  
		{ printf("\n*TA layer specified (%d) may not be of polygons. Checking if bitmap\n",segm_in); 
		goto CHECK_BM; }

	// Trainig area is a Vector layer 
	
	//if( i > 0 && first_type != SEG_VEC) // check that previous was also a vector layer
	//	{printf("\n\n**** ERROR - All Training Areas must be same type (here vector layers)\n\n"); exit(-1);}
		
	piFDefn = piLayer->GetLayerDefn();
	feat_count = piLayer->GetFeatureCount();
	field_count = piFDefn->GetFieldCount();
	
	printf("\n**Current layer %d of current file has %d features (shapes) with %d fields each\n\n", 
				segm_in, feat_count, field_count);

	// User given info points to a vector layer 

	  vmode = 1; 		// vector mode (not bitmap)
	  goto Arg3;

CHECK_BM:


	// Check that incoming channel is a bitmap (i.e/, not an image)

	piBand = ima_in->GetRasterBand(segm_in);		// Access bitmap channel (i.e, segment)
	if(piBand == NULL)  
		{ printf("\n\t*Unable to get bitmap layer as specified\n\n"); exit(-1);}

	printf("\n**Opening input bitmap channel (layer) %d of Type = %s \n ",
						segm_in, GDALGetDataTypeName(piBand->GetRasterDataType()) );
	printf("Metadata item (NBITS): %s \n", piBand->GetMetadataItem("NBITS","IMAGE_STRUCTURE") );	

	if ( piBand->GetMetadataItem("NBITS","IMAGE_STRUCTURE") == NULL)
	  {
	  printf("\n\t*** Specified channel (%d) for training area is not a bitmap\n",segm_in);
	  printf("\nImage : %s Type = %s \n", ima_in->GetDescription(), GDALGetDataTypeName(piBand->GetRasterDataType()));
	  printf("Channel Description: %s \n", piBand->GetDescription() );
	  printf("Please double check (Hint: use \"gdalinfo\" on the file).... Exiting\n");
	  exit(1);
	  }
	
	// User given info points to a bitmap training area

	  vmode = 0; 		// non-vector mode (bitmap)
	
	}	  		// endof if PCI file and segment poorly defined
	  
	
NOT_PCI:	

// If tif file then dealing with ITC bitmap (often ISOL_BM.tif from itcisol_g)

	if (strncmp(extension2,"tif",3) == 0) 
	  {
	  vmode = 0; 		// not vector mode (bitmap mode)
	  segm_in = 1;		// assuming single segment cause tif file
	  printf("Assuming we are dealing with ITC bitmap (since tif file)\n");
	  }

// If shape file then dealing with "manual trees", assuming single layer

	if (strncmp(extension2,"shp",3) == 0) 
	  {
	  vmode = 1; 		// vector mode
	  segm_in = 1;		// assuming single segment cause shp file
	  printf("\n\t **Assuming we are dealing with polygons of manual trees \n");
	  }


	  
//**********

// Check *Third argument* on command line

Arg3:
	  
	 //exit(-1);		// For debugging  
	    
	if (argv[3] == NULL) 
	  {
	  printf("\n\t ### ERROR ### A third argument is needed \n");
	  printf("\n Third argument should be the TYPE of mask to create (LIT/SHADE/TOP).\n");
	  exit(1);
	  }

// check that parameter is valid 

	strncpy(masktype,argv[3],3);
 	masktype[3] = '\0';		// manually add a null to make it a string (only 3 chrs)
	//printf("\n MASKTYPE: %s \n", masktype);
	check_parameters(masktype);

/* determine type of mask to generate */

	for (i = 0; i < MASKTYPES; i++)
		if (strncmp(masktype, MaskType[i],3) == 0)  option = i;

	fprintf(stdout, "\n\t*** Type of mask being generated is %s ***\n\n" , MaskType[option]);

// Check *Fourth argument* on command line (if bylines) ** MUST BE FIRST

	if( (argc == 5) && (EQUALN(argv[4],"BYLINES",4)) )
	  {
	  bylines_flag = 1; 
	  printf("\n* As requested: Will read/write images/bitmaps by lines to save memory\n\n");
	  }
  	
	
	//exit(-1);		// for debugging

// If manual trees as "shp file" OR "vector layer" skip bitmap section

	if(vmode) goto MANTREES;

//********************************************************************

// GDAL - Read ITC bitmap from which to create the mask bitmap (e.g., LIT) 

//***************************************************************

BITMAP: 

	isolbitbuf = read_bitmap(file_seg, segm_in);	//was isolbitbuf = bitmap_in(argv[2]);
	
	safety_zone(isolbitbuf);

//**********************************************************************************

// For INITIALTESTING, just copy input bitmap to output bitmap and out

// ##################################3
/* 
	printf("\n\n**FOR TESTING** Moving ISOL bitmap to MASK bitmap (for quick in/out test)\n");

	maskbitbuf = (PixVal *) CPLMalloc(bmsize);
	check_mem(maskbitbuf);	
	memcpy(maskbitbuf, isolbitbuf, bmsize);		// internal real 1-bit bitmaps
	goto WRITE;
 */
 
//**********************************************************************************

// 	Doing processing in one shot (i.e., full image and bitmaps)

//**********************************************************************************

	printf("\nDoing ITCMG processing in one shot (not by sections)\n");

// Reserve memory for output bitmap and create a secondary isol bitmap

	tempbitbuf = (PixVal *) CPLMalloc(bmsize);	// prep memory for an intermediate bitmap used by scan_for_tree()
	check_mem(tempbitbuf);
	memcpy(tempbitbuf, isolbitbuf, bmsize);		// Make another ISOL bitmaps getting destroy by 2nd fill

	maskbitbuf = (PixVal *) CPLMalloc(bmsize);	// prep memory for output bitmap
	check_mem(maskbitbuf);

	no_of_sections = 1;				// working on full image (not by section)

// Process image and gather info, and form bitmaps 

	printf("\n\tGenerating mask.  Please wait ...\n\n");


// Doing whole image in one shot

	minpos = 0;			
	maxpos = Pixels*(int64)Lines;		// full image position in Pixels (or bytes)

	//maxpos= 25000;			// sub-area for testing
	//printf("\n Maxposition: %I64d \n",maxpos);


//  #################  For Debuging bypass operation

	scan_for_tree(xsize, ysize, isolbitbuf, option);	// full image scan for ISOLs

	//printf("\n Return line position: %d at pixel %d\n", retposy, retposx); 

	goto WRITE;


//**************************************************************

MANTREES:

	printf("\nDoing ITCMG processing for Manual Trees ...\n");

// Doing processing in one shot (i.e., full image and bitmaps)

	minpos = 0;			
	maxpos = Pixels*(int64)Lines;		// full image position in Pixels (or bytes)


//	Loop trought manually delineated trees (polygons) and generate needed mask

	isolbitbuf = (PixVal *) CPLMalloc(bmsize);	// input ITC(ISOL) bitmap
	check_mem(isolbitbuf);
	tempbitbuf = (PixVal *) CPLMalloc(bmsize);	// prep memory for an intermediate bitmap 
	check_mem(tempbitbuf);
	maskbitbuf = (PixVal *) CPLMalloc(bmsize);	// prep output bitmap
	check_mem(maskbitbuf);


	//isolbitbuf = vector2bitmap(argv[2]);

	loop_for_mantree_g(file_seg,xsize, ysize, isolbitbuf, option, segm_in);



//***********************************

	//printf("\n####  Manual trees not fully implemented yet - Existing \n\n");  exit(-1);

	goto WRITE;


/*************************************************************

	Create output mask bitmap (a 1bit tif)

******************************************************************/

WRITE:

// Time to check memory usage with task manager
/* 
	  printf("\nCheck memory use. OK to continue(y/n): ");
	  scanf("%s",answer);			// gets any answer
	  if(answer[0] == 'n') exit(-1);
*/

// Presently, a fixed file name is used. Less parameters to put on command line
// The user can always change the name immediatly after the run if needed (or in a script)
	//file_out = "ITCMG.tif";


// Deal with possible PATH in front of filename

	strcpy(fullfilename,argv[1]);			// main input filename (and possibly its dir)
//	printf("Full Filename:  %s \n", fullfilename);
//	printf("Full Filename Length:  %zd \n",  strlen(fullfilename));

	int basef_len;		
	for (i=0; i < strlen(fullfilename); i++)
	  {
	  j = strlen(fullfilename) - i;
	  //printf("Count back: %d",j);
	  //if(fullfilename[j] == '_') {basef_len = j;	break;}		// find last underscore in full file name
	  if(fullfilename[j] == '.') {basef_len = j;	break;}		  // find dot in full file name
	  }
//	printf("\nBase Filename Length:  %d \n", basef_len);
	
	strncpy(basefname, fullfilename, basef_len);
	basefname[basef_len] = '\0';   					/* null character manually added */
	
//	printf("Full Filename:  %s \n", fullfilename);
//	printf("\nBasefname ::  %s \n", basefname);
	
//	Concatenate base file name (path+file name beginning) with VFOL.tif

	//pch = strncat(basefname,"_MG",3); 	
	strncat(basefname,"_",1);	
	strncat(basefname,argv[3],3);
	strcpy(file_out, basefname);		
		
	//file_out = strncat(basefname,"_MG",3); 	
	//strncpy(file_out, pch, strlen(basefname));	
	
 	strncat(file_out,".tif",4);
	//printf("File_out  :  %s \n", file_out); 
	//printf("\n Output Filename Length:  %zd \n", strlen(file_out));



  	snprintf(Description, 120, "%s mask from %s and %s",argv[3], argv[1], argv[2]);
	  
	//printf("\nDescription: %s \n\n", Description );


// Write bitmap to output file
	
	write_bitmap(maskbitbuf, file_out);		//was bitmap_out(maskbitbuf, file_out);
	 
// Time to check memory usage with task manager
/* 
	  printf("\nCheck memory use. OK to continue(y/n): ");
	  scanf("%s",answer);			// gets any answer
	  if(answer[0] == 'n') exit(-1);
*/
// Close input and output images

DONE:	printf("\n*Closing all image files and exiting program. \n");


	if(vmode) GDALClose(seg_in);



// Program finishing info

time (&rawtime);
timeinfo = localtime (&rawtime);
fprintf(stdout,"\n\n_______________________________\n");
fprintf(stdout,"\n %s (%s) finished at %s\n\n", PROG_NAME, VERSION,  asctime(timeinfo));

// For people using this program via ArcGIS, give then some time to examine the results (before disappearing)

if ((strncmp("ArcGIS ",argv[argc-1],3) == 0) )		// if last argument is ArcGIS or ArcMap
	{
	fprintf(stdout,"\n\n######\n");
	printf("\n Type anything to make this detailed window disappear and terminate %s ",PROG_NAME);
	answer[0] = getc(stdin); 		// gets any answer or <CR>
    }
	
	
exit(0);				// exit properly 

} 		// end of MAIN PROGRAM



/**********************************************************************************/

/* FUNCTIONS */

/**********************************************************************************/


/* This function scans the given bitmap to find trees.  A 2x2 window moves across, starting
   in the upper left and working across, then down to the lower right.  If all bits in the
   2x2 window are 'filled' then a tree has been found and fill() is called to gather the
   information needed to generate the mask type.  This information is stored in
   a tree node for that tree.
*/

void scan_for_tree(int xsize, int ysize, PixVal * bitmap, int option)
  {
	int             x, y;
	int64		bitnum;
	tree_node      *new_tree;

	printf("\nScan_for_tree() started ... \n\n");
	//printf("\n xsize, ysize, option : %d %d %d \n",xsize, ysize, option);
	//printf("\n minpos, maxpos : %I64d %I64d  \n", minpos, maxpos );

	for (y = 2; y < ysize-1; y++)
	{
	for (x = 2; x < xsize-1; x++)
	  {
	  bitnum = (y-1)*(int64)xsize + x-1;		// position in image in pixels (bits or bytes)

	  if (bitnum < minpos) continue;		// skip irrelevant image parts (when by sections) 

	  if (bitnum+xsize+1 > maxpos)			// if at max pos in that section
		{
		printf("\nStopping scan at position: %I64d \n", maxpos);
		retposy=y; retposx=x;
		next_sect = 1;			// call for next section
		return;
		}


          /* detect an ITC -- check if 2x2 window is 'filled' */

	  if ( testbit(bitmap,bitnum) && testbit(bitmap,bitnum+1) &&
		testbit(bitmap,bitnum+xsize) && testbit(bitmap,bitnum+xsize+1) )
	    {
	        //printf("\n\nBlob found at %d %d \n", x,y);

	        new_tree = new_tree_node();

		fill(x, y, xsize, bitmap, new_tree, ILLUM_AVG);		// First fill() to get ITC average greylevel and count 
       		//printf("\nITC Count=%d\n",  new_tree->count);	

		if(next_sect) { retposy=y; retposx=x; return; }		// fill() may have returned a flag to go next section
		
		 /* If we have a tree */
		
		 if (new_tree->count != 0) 
			  {
			  new_tree->image_avg = new_tree->image_sum / new_tree->count;		/* calculate its average grey level from sum */
			  new_tree->count = 0;						/* reset some value for next fill() */
			  new_tree->image_sum = 0;
			  }
	        //printf("\n\n2nd fill() at %d %d \n", x,y);

		fill(x, y, xsize, tempbitbuf, new_tree, option);		/* 2nd fill() to do operation like LIT */

	        //fprintf(stdout,"Lit/Shade/Top Count=%d\n",  new_tree->count);

		if ((option == TOP_MASK) && (new_tree->count != 0)) setbit(maskbitbuf,new_tree->tt_pos); 

		free(new_tree);

	    } 	/* End of if */

	  }	// end of "for x"

 		printf("%d lines done\r", y);

	  if ( (y/100)*100 == y)  printf("%d lines done\r", y);

   	}	/* End of main loop */

	printf("%d lines done\n\n", y);
	retposy=y;  retposx=x;
	next_sect = 0;

	//printf("\nScan_for_tree() Done \n");
  }




/**********************************************************************************/

/* This function 'fills' a tree shape, gathering information for processing.
	NOTE:	The ITC gets removed from the  bitmap while processing
*/

void fill(int x, int y, int xsize, unsigned char *bitmap, tree_node *tree_info, int option)

  {
  int64 bitnum, bytenum;

  bitnum = (y-1)*(int64)xsize + x-1;			/* position in full bitmap */
  bytenum = ((y-1) - imaoffset)*(int64)xsize + x-1; 	 /* position in image section */

  //fprintf(stdout,"bitnum, bytenum, option : %I64d %I64d %d\t",bitnum, bytenum, option);
  //fprintf(stdout,"minpos, maxpos: %I64d %I64d\t",minpos, maxpos);

  /* if one pixel is outside image section --> abort the fill & grab other image section*/

  if  (bitnum > maxpos)  { next_sect=1; return; }

  if  (bitnum > minpos)  
	process_image_data(bytenum, bitnum, tree_info, option);

  /* turn off bit & fill recursively starting at current position */

  clearbit(bitmap,bitnum);

  if (testbit(bitmap,bitnum+1))
		fill(x + 1, y, xsize, bitmap, tree_info, option);
  if (testbit(bitmap,bitnum-xsize))
		fill(x, y - 1, xsize, bitmap, tree_info, option);
  if (testbit(bitmap,bitnum-1))
		fill(x - 1, y, xsize, bitmap, tree_info, option);
  if (testbit(bitmap,bitnum+xsize))
		fill(x, y + 1, xsize, bitmap, tree_info, option);	

  }
/**********************************************************************************/

/* This function 'fills' a tree shape, gathering information for processing BUT
	from a small image chip at the proper location (i.e., not the full image)
	NOTE:	The ITC gets removed from the  bitmap while processing
*/

void fill_vs(int x, int y, int xsize, unsigned char *bitmap, tree_node *tree_info, int option)

  {
  int64 bitnum, bytenum;

  bitnum = (y-1)*(int64)xsize + x-1;						/* position in full bitmap */
  bytenum = ((y-1) - iymin)*(int64)(ixmax-ixmin) + (x-ixmin-1); 		 /* position in very small image chip */

 /*fprintf(stdout,"bitnum,bytenum = %I64d %I64d\t",bitnum,bytenum); */
  /*fprintf(stdout,"%d ",iiii++); */

  process_image_data(bytenum, bitnum, tree_info, option);

  /* turn off bit & fill recursively starting at current position */
  clearbit(bitmap,bitnum);

  if (testbit(bitmap,bitnum+1))
		fill_vs(x + 1, y, xsize, bitmap, tree_info, option);
  if (testbit(bitmap,bitnum-xsize))
		fill_vs(x, y - 1, xsize, bitmap, tree_info, option);
  if (testbit(bitmap,bitnum-1))
		fill_vs(x - 1, y, xsize, bitmap, tree_info, option);
  if (testbit(bitmap,bitnum+xsize))
		fill_vs(x, y + 1, xsize, bitmap, tree_info, option);	

  }
/**********************************************************************************/


/* This function performs the appropriate processing operation, depending on the
   type of mask specified (given by option).
*/

void process_image_data(int64 bytenum, int64 bitnum, tree_node *tree_info, int option)
{
	int32 pix_val;		// to get pixel grey-level from image

	//printf("\nGOT IN process_image_data()\n");

	pix_val = (*get_pix_val) (illum_ima, bytenum);	//works with get_pix_val = get_u8 or get_pix_val = get_u16
							// works with setting in itc_io_g & define in itc_io_g.h
	//pix_val = (*get_u8) (illum_ima, bytenum);		// works "as is" for 8b images
	//pix_val =  get_u8(illum_ima, bytenum);		// works if function get_u8() is in program

	//printf("\n Pixel value : %d \n", pix_val );

	switch (option) 
	{
		case LIT_MASK:
			if (pix_val > tree_info->image_avg) { setbit(maskbitbuf, bitnum);(tree_info->count)++; }
		break;
		case SHADE_MASK:
			if (pix_val <= tree_info->image_avg) { setbit(maskbitbuf,bitnum); (tree_info->count)++; }	
		break;
		case TOP_MASK:
			(tree_info->count)++;
			if (tree_info->crown_max <= pix_val) 
					{tree_info->crown_max = pix_val; tree_info->tt_pos = bitnum;}
		break;
		case ILLUM_AVG:
			(tree_info->count)++;
			tree_info->image_sum += pix_val;
		break;

		default:
			(tree_info->count)++;
			if (tree_info->crown_max <= pix_val) 
				{tree_info->crown_max = pix_val; tree_info->tt_pos = bitnum;}
		break;
	}
}



/**********************************************************************************/
/**********************************************************************************/

/* This function allocates memory for a new tree node and initializes the node */

tree_node      *new_tree_node(void)
{
	int             i;
	tree_node      *tree_list;

	//tree_list = (tree_node *) emalloc(sizeof(tree_node));
	tree_list = (tree_node *) CPLMalloc(sizeof(tree_node));

	/* Initialize fields to zero */

	tree_list->count = 0;
	tree_list->crown_max = 0;
	tree_list->image_sum = 0;
	tree_list->image_avg = 0;
	tree_list->next_tree = NULL;

	return (tree_list);
}

/**********************************************************************************/

/* This function adds the tree node tree to the tree list.  Insertion is at head of list
   A dummy node is contained as the first node in the list.  The count field of it is
   used to keep track of the number of nodes (not including itself) in the list
*/

void add_to_tree_list(tree_node *tree_list, tree_node *tree)
{
	tree->next_tree = tree_list->next_tree;
	tree_list->next_tree = tree;
	(tree_list->count)++;

}
/**********************************************************************************/

/* This function converts a string to upper case characters */

void upper_case(char *c)
{
	while (*c != '\0') {
		if (*c >= 'a' && *c <= 'z')
			*c += ('A' - 'a');
		c++;
	}
}

/**********************************************************************************/

/* This function converts an array of integers to a string.  Note that the maximum length
   of the integer is 4 digits.
*/

char *itostr(int *nums, int size)
{
	int i, offset;
	char *string;

	string = (char *) malloc(size * 5);

	offset = 0;
	for (i = 0; i < size; i++) {
		sprintf((string + offset), "%d ", nums[i]);
		offset = (int) strlen(string);
	}
	sprintf((string + offset), "\0");

	return (string);
}




/**********************************************************************************/

/* This function checks that the input parameters set in EASI/PACE by the user
   are valid.  Invalid parameters will produce an error message and cause a program
   exit.
*/

void check_parameters(char *masktype)
{
	int             i, j;

	upper_case(masktype);
	//printf("\n MASKTYPE: %s \n", masktype);

	/* Check MASKTYPE */
	j = 0;
	for (i = 0; i < MASKTYPES; i++)
		{ if (strncmp(masktype, MaskType[i],3 ) == 0)  j++; }

	if (j != 1) 	// one and only one match (out of three)
	  {
	  fprintf(stderr, "Invalid MASKTYPE.  Enter one of LIT/SHADE/TOP.\n");
	  exit(-1);
	  }
}

/**********************************************************************************/


// functions to read 8bit image data (now, with int64 position) 
// should be in itc_io_g.cpp and .h
 
/*
int32 get_u8(void * image, int64 pos)
  {
  return *((PixVal *)image + pos);
  }
*/

/******************************************************************/
/**********************************************************************************/

/**********************************************************************************/

/* This function loops through the shapes of the input layer (manual tree crown as polygons),
   paints a *single tree crown* into the ITC bitmap and then fills it to gather the
   information needed to generate the mask of a given type (e.g., LIT). 

	**** This the version for GDAL-based analyses
*/


void loop_for_mantree_g(char * filename, int xsize, int ysize, unsigned char *bitmap, int option, int segment)
  {
  
  int64		bitnum;
  tree_node      *new_tree;

  int		nVertex,kk;
  int		tdbiw[4];

  GDBVertex2D	*pasVertices;				//#####
 
// Getting polygon vertices

  OGRPoint ptTemp;
  int NumberOfExteriorRingVertices;
  int NumberOfInnerRings; 

// reserve space for 250 vertices (for the moment)
			
	pasVertices = (GDBVertex2D *) CPLMalloc(4000);

// Open for reading vector file (shp or PCI vector layer)

/*
	//seg_in = ima_in;		// in PCI files, everything is in the same file

    const char *pszDriverName = "ESRI Shapefile";
    GDALDriver *poDriver;

    GDALAllRegister();

    poDriver = GetGDALDriverManager()->GetDriverByName(pszDriverName );
    if( poDriver == NULL )
    {
        printf( "%s driver not available.\n", pszDriverName );
        exit( 1 );
    }

*/

	seg_in = (GDALDataset*) GDALOpenEx(filename, GDAL_OF_VECTOR, NULL, NULL, NULL );

	//seg_in = (GDALDataset*) GDALOpen(filename, GA_ReadOnly);
	//seg_in = (GDALDataset*) GDALOpenEx(filename, GDAL_OF_VECTOR, NULL, NULL, NULL );	
	//seg_in = static_cast<GDALDataset*> ( GDALOpenEx(filename, GDAL_OF_VECTOR, NULL, NULL, NULL) );
	//seg_in = ima_in;		// for test
	
	
	if( seg_in == NULL )
	{
	    printf( "Failed to open input file.\n" );
	    exit( 1 );
	}

	printf("\n\t**File '%s' was opened for reading a vector layer\n\n", filename);


// Open layer pointed to by user via argv[2]

	//fprintf(stdout,"\n\t*Number of rasters in that file is %d \n", seg_in->GetRasterCount() );	
	//fprintf(stdout,"\n\t*Number of layers in that file is %d \n", seg_in->GetLayerCount() );
	
	layer_count = seg_in->GetLayerCount();	//#### GDAL 3.2.2 version often Blows up here 
	if(layer_count == NULL) { printf("\n\t*There are no vector layer in this file \n"); exit(-1);}
	fprintf(stdout,"\n\t*Number of layers in vector file is %d \n",layer_count);
	
	// OPening that vector layer

	//fprintf(stdout,"\n\tAddressing layer %d \n", segment);	
	
	piLayer = seg_in->GetLayer(segment-1);		// Layer numbers start at zero	
	if(piLayer == NULL) { printf("\n\t*UNABLE to access this vector layer  \n"); exit(-1);}	
	//fprintf(stdout,"\n\tAccessing layer %d \n", segment);


	piLayer->ResetReading();	//#### GDAL 3.2.2 version often Blows up her
	//fprintf(stdout,"\n\tResetting layer %d \n", segment);
	
// Number of features (i.e., polygons) in that layer AND number of fields in that layer

	piFDefn = piLayer->GetLayerDefn();
	//fprintf(stdout,"\n\tGot here \n");	
	
	feat_count = piLayer->GetFeatureCount();
	field_count = piFDefn->GetFieldCount();
	fprintf(stdout,"\n**Layer %d of current file has %d features(shapes) with %d fields each\n\n", 
				segment, feat_count, field_count);


// LOOP through all the individual shapes (trees, polygons)


  for (iFeat=0; iFeat<feat_count; iFeat++)
  //for (iFeat=0; iFeat<1; iFeat++)		// Only a few manual trees (feat,polygon) for testing
    {    
    piFeature = piLayer->GetNextFeature();
    piGeometry = piFeature->GetGeometryRef();
    //printf("\n For feature %d \t Geometry is : %d \n", iFeat, piGeometry->getGeometryType());

    if ( piGeometry != NULL && wkbFlatten(piGeometry->getGeometryType()) == wkbPolygon )
	{
	OGRPolygon *piPolygon = ( OGRPolygon * )piGeometry;

	NumberOfInnerRings = piPolygon->getNumInteriorRings();	
	//printf("Number of inner rings = %d \n", NumberOfInnerRings);

	if(NumberOfInnerRings > 0)
	  {
	  printf("Number of inner rings = %d \n", NumberOfInnerRings);
	  printf("\t *** CAN NOT DEAL with InnerRings in trees - EXIT \n");
	  exit(-1);
	  }

	OGRLinearRing *piExteriorRing = piPolygon->getExteriorRing();

	NumberOfExteriorRingVertices = piExteriorRing->getNumPoints();
	//printf("NumberOfExteriorRingVertices = %d \n", NumberOfExteriorRingVertices);

// Convert geographic coordinates to image coordinates

	for ( int k = 0; k < NumberOfExteriorRingVertices; k++ )
	  {
	   piExteriorRing->getPoint(k,&ptTemp);

		//if (k < 10) printf( "%.2f  %.2f\t", ptTemp.getX(), ptTemp.getY() );	// Print some UTM vertices

// Convert geographic coordinates to image coordinates

		pasVertices[k].x = ( ptTemp.getX()- topleftX ) / transformX;
		pasVertices[k].y = ( ptTemp.getY() - topleftY ) / transformY;
		
		//if (k < 10) printf( "\tIma:  %.1f  %.1f\n", pasVertices[k].x, pasVertices[k].y); 	// PRINT some IMA vertices

// Check if outside the image
		if( (pasVertices[k].x < 0) || (pasVertices[k].y < 0) || (pasVertices[k].x > Pixels) || (pasVertices[k].y > Lines))
		  {
		   printf("\nShape %d in MANVEC layer appears outside the image and will be skipped\n",iFeat);
		   goto NEXT_FEAT;
		  }

        }		// end of loop for vertices to convert


	    }	// end of IF Polygon

	//printf("NumberOfExteriorRingVertices = %d \n", NumberOfExteriorRingVertices);

	nVertex = NumberOfExteriorRingVertices;

	 
 /* Paint tree crown in both bitmaps  */

	vect2rast_g(nVertex, pasVertices, bitmap, xsize, iFeat, segment);	// for full crown analysis

	//vect2rast_g(nVertex, pasVertices, tempbitbuf, xsize, iFeat, segment);	 // for LIT/SHADE/TT crown analysis

	memcpy(tempbitbuf, bitmap, bmsize);		// why do it twice when you can just copy

	//printf("\nTo be used Tree (shape=%d) at xcg = %d ycg = %d \n", iFeat, xcg, ycg); 

/* CHECK that the center of gravity is in the painted crown */
/* if ill-formed (cg not in crown) CHECK other places, if not ok,  dont use it */

	  bitnum = (ycg-1)*(int64)xsize + xcg-1;	  
	  if (! testbit(bitmap,bitnum) )  
		{ 

	        if (testbit(bitmap,bitnum+1)) {xcg=xcg+1; goto DO_IT;}
	        if (testbit(bitmap,bitnum-1)) {xcg=xcg-1; goto DO_IT;}
	        if (testbit(bitmap,bitnum+3)) {xcg=xcg+3; goto DO_IT;}
	        if (testbit(bitmap,bitnum-3)) {xcg=xcg-3; goto DO_IT;}

		printf("\nUnused Tree (shape=%d) at xcg = %d ycg = %d \n", iFeat, xcg, ycg); 
	        printf("ixmin ixmax, iymin, iymax : %d %d %d %d \n", ixmin, ixmax, iymin, iymax);
		unusedITC++; 
		continue;
		}


// DO THE WORK - fill full crown to get average grey level, then do LIT/SHASE/TT

	  
DO_IT:	  new_tree = new_tree_node();		// create tree object

	  printf("\nTree to be used (shape=%d) at xcg = %d ycg = %d \n", iFeat, xcg, ycg); 	// Print
	    
	  if (option == LIT_MASK || option == SHADE_MASK) 
	    {
	    fill(xcg, ycg, xsize, bitmap, new_tree, ILLUM_AVG);		 // First fill to get crown illumin average 

	    printf("\nFor shape: %d Full ITC Pixel Count = %d\n", iFeat, new_tree->count); 

	    /* If we have a tree */
		
	    if (new_tree->count != 0) 
		  {
		  new_tree->image_avg = new_tree->image_sum / new_tree->count;		 /* crown average grey-level */
		  new_tree->count = 0;						/* reset some value for next fill() */
		  new_tree->image_sum = 0;
		  }

	    //fprintf(stdout,"For shape: %d ITC grey-level average = %d   \n", iFeat, new_tree->image_avg); 
	    }


	  //printf("\nFor shape: %d Second fill for option %d ...\n", iFeat, option); 

	  fill(xcg, ycg, xsize, tempbitbuf, new_tree, option);	 	 // 2nd fill() to do operation like LIT

	  usedITC++;

	  if(option < 2) printf("For shape: %d Lit/Shade Count = %d \n\n", iFeat, new_tree->count); 

	  if ((option == TOP_MASK) && (new_tree->count != 0)) 
	    { 
	    setbit(maskbitbuf, new_tree->tt_pos); 
	    printf("For shape: %d Tree Top position=%I64d\n", iFeat, new_tree->tt_pos);
	    }

	  free(new_tree);  
	 // a polygon was skipped cause outside the image
	 
	NEXT_FEAT:	    printf("\n");

	 }	// end of feature loop all manual tree polygon done

	  /* HFree(pasVertices); */

  }		//end of function



//******************************************************************************



