/* 

Program name: 	itcsfil_g.cpp

Author: 		François A. Gougeon

Date:			Nov 2023

Description:	Individual Tree Crown Size Filter (itcsfil_g.cpp)

	From a bitmap showing individual tree crowns (ITCs)
	(such as the one generated by program ITCISOL),
	this program generates a bitmap containing only the crowns
	within a certain range of crown sizes (using lower and upper 
	thresholds (in pixels)), or a certain range of diameters 
	(using lower and upper thresholds (in meters) of crown diameters).
	It can also filter for crown "good shape" based on crown
	excentricity (ratio of one diameter vs the other).

	
	
	François A. Gougeon, Ph.D.
	Remote Sensing Research	
	(©)Natural Resources Canada
	Canadian Forest Service 
	Pacific Forestry Centre
	506 West Burnside Rd.
	Victoria, British Columbia, 
	Canada, V8Z 1M5	


********************************************
	PCI Version PARAMETERS


C	ITCSFIL is controlled by the following global parameters:
C
C	Name		Prompt					Count	Type
C
C	FILE		Database File Name			128	Char
C	ISOLBIT		Bitmap of individual tree crown		1	Int	
C	DBOB		Bitmap of crowns of certain sizes	1	Int
C	AREATHR		Min & Max Area in Pixels to include     1-2	Int
C	DIAMTHR		Min & Max Diameter in Metres to include	1-2	Real
C	EXCENT		Max. excentricity to be tolerated	1	Real
C	REPORT		Reporting device			128	Char
C



*****************************************


v1.0a		Nov. 2023	François Gougeon	(itcsfil_g.cpp)

			- Created from thickbit_g.cpp who deals with input and output bitmaps
				and original PCI based ITCSFIL


Run as (for examples):

	> itcsfil_g xxxx_ISOL.tif  Out_Bitmap.tif AREATHR DIAMTHR EXCENT

	> itcsfil_g xxxx_ISOL.tif  - 50,150 - 2.0
	
*/

//*****************************************	
	
#define VERSION	"v1.0a"
#define PROG_NAME "ITCSFIL"
#define FILENAME  250


#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <limits.h>
#include <time.h>       // time_t, struct tm, time, localtime


#include "gdal_priv.h"		// For GDAL library
#include "ogrsf_frmts.h"	// For OGR

#include "ITC-Suite_g.h"	// define lots of vars for the Suite
#include "bitops.h"		// defines bitmap operations (mostly via macros)
#include "itc_io_g.h"		// my newest GDAL image/bitmap input/output



/* structure - list of tree crown encountered and parameters */

typedef struct crown_info 
	{
	int area;			/* crown area */
	int xmin;			/* diam in both directions*/
	int xmax;
	int ymin;
	int ymax;
	struct crown_info *link;
	} crown;

/* function declarations */

void 	fill(int, int, crown *);
void 	erase(int, int, crown *);
void 	init_rec(crown *);
	
	
// Global declarations - Tons are needed to use with "itc_io_g.cpp"

int		Pixels, Lines, Channels;	// pixel and line starting at 1,1
int		xsize, ysize;			// pixel and line starting at 0,0
int 	data_type;

int64 	bmsize;		// size of bitmap in bytes 

int		bylines_flag = 0;		// by default proceed by full images (not by lines)
int		area_flag = 0, exc_flag = 0;	// flags about which mode we are in to help erasing properly

float		xpixsz, ypixsz;
char 		*Proj, *Proj2, *Datum, *Datum2, *Temp,*token;

double 		topleftX, transformX, topleftY, transformY; 	 /* for geographic mapping */

int 		ch_in, ch_out, in_ch[10], segm_in, in_segm[], segm_out;

GDALDataset	*ima_in, *ima_out;
GDALDriver 	*piDriver, *poDriver;
GDALRasterBand	*piBand, *poBand;
GDALDataset	 *seg_in, *seg_out;
double		adfGeoTransform[6], adfGeoTransform2[6];
char 		**papszMetadata;
char	 **papszOptions;
int imaFile_opened;

char 	Description[80];
char 	Extension[10]; 		// global variable for other prog.
int	xcg, ycg;	

unsigned char  *isolbitbuf, *outbitbuf;
	
/***************************** main prog. *******************************/


int main(int argc, char *argv[])
{

// Local vars list

 
int i, j, k, ii, jj, kk;
int icount;
int xsize, ysize;
int blocks,segnum;

int byte, bit, efactor, ofs;
int64 bitnum;
int 	ch_out=1, ch_in=1, no_ch=1, dbic[10], ch_no;

char seg_history[81], seg_desc[81], timedate[17];
int segtype;
char segflag, segname[9];
long int start, length;

int	 argcount;		
int commaFlag = 0;

time_t rawtime;
struct tm * timeinfo;

//char	*basefname;						// ** just a pointer **
char	basefname[130];
int		basef_len;	
char	fullfileout[130];
char  	*cptr, *cptr2;	// generic pointer to char


char 	Proj[250], ans[80], answer[10];
char	fullfilename[FILENAME], file_in[FILENAME];		// for input file
char 	*filename, *extension, temp[FILENAME],extens[5];			// for output file
char	ima_description[128];						// for output file
char 	*tstring, *p, ach_in[5];
char	file_out[FILENAME];


crown Crown, *p1; 	/* structure and its pointer are defined */
p1 = &Crown;		/* to use when not creating a list of crowns and 
					doing it all in one temporary storage crown structure */
					
int 	t_crown, e_crown, s_crown, j_count;

t_crown = 0; e_crown = 0; s_crown = 0; j_count = 0;

float	xdiam, ydiam, crown_excent;
float low_area, high_area;
int	lsizthr=0, hsizthr=0;
int areathr[3];				// only two needed, tree if for safety check
float diamthr[3];
float excent=1.0;
float pi=3.14159;


//***************************


/* Print Program Header and time */

	time (&rawtime);
	timeinfo = localtime (&rawtime);

	fprintf(stdout,"\n\t\tStarting %s (%s) at %s\n", PROG_NAME, VERSION, asctime(timeinfo));
	
// Registers for all types of files with GDAL

	GDALAllRegister(); 	
	
//***************************
 
// Check input parameters on command line (i.e., agrv[*])

//***************************

// Check *First argument* on command line (input image BITMAP)

	argcount = 1;

	if (argv[argcount]== NULL) 
	  {
	  printf("\n\t **PROBLEM** with input image %s \n",argv[argcount]);
	  printf("Have an INPUT bitmap as first argument on command line \n\n");  
	  printf("\nUSAGE:  itcsfil_g In_ISOL.tif  Out_Bitmap.tif AREATHR DIAMTHR EXCENT \n");	    
	  exit(-1);
	  }  
	  	  
	  strcpy(file_in, argv[argcount]);		// if filename by itself (probably a tiff bitmap)	  
	  segm_in = ch_no = 1;	dbic[0]=dbic[1]=1;	 // default value, if nothing changes


// Get CLEAN file name and extension

	strcpy(temp, argv[argcount]);  
	cptr = strtok(temp, ", "); 				// go to comma (or space) and put a null there
	//printf(" Temp :  %s \n", temp);
	strcpy(file_in, temp);	
	//printf(" Filename :  %s \n", file_in);
	
	strcpy(temp, argv[argcount]); 		// reload temp
	//printf(" Temp :  %s \n", temp);		
	cptr = strtok(temp,"."); 			// goto DOT 
	//printf(" Temp :  %s \n", temp);	
	cptr = strtok(NULL,", ");			// goto comma or space
	strncpy(extens, cptr, 3);
	//printf(" Extension : %s\n", extens);
	
//	exit(-1);
	
// check if segment number(s)is connected to file name by a comma

	segm_in = 1;						// default 
	strcpy(temp, argv[argcount]);  
	//printf(" Temp :  %s \n", temp);
	cptr = strtok(temp, ", "); 			// check for comma after extension
	cptr = strtok(NULL, ", ");			// got after the comma	
	//printf(" Temp :  %s \n", temp);
	//printf(" cptr :  %s \n", cptr);
	
	if(cptr != NULL)					// comma after extension
	{
	commaFlag = 1;	
	ch_no = strtol(cptr,NULL, 10);			// change to integer
	//printf(" After comma : %d\n", ch_no);	

	segm_in = dbic[0] = ch_in = ch_no ;				// for PCI code coompatibility
	printf(" Segment to use : %d \n", dbic[0]);

// Some programs may have a second comma and a second item	

	cptr = strtok(NULL, ", ");			// check for another channel 
	if(cptr != NULL) {ch_no = strtol(cptr,NULL, 10); dbic[1]= ch_no; no_ch = 2;}					
	if(no_ch == 2) printf(" Secondary bitmap to use : %d \n", dbic[1]);

	if ( no_ch > 1) 
	  {
	  fprintf(stdout,"\n\t##### ERROR - No. of input bitmap to use  must be one #####\n");
	  exit(-1);
	  }

	}
	
// Channel numbers may be as a separate parameter on the cmd line (OR NADA)
	
	if(!commaFlag)		
	  { 
	  argcount++;					 // get next argument	  
	  //printf("Argument %d: %s \n", argcount, argv[argcount]);
	  strcpy(temp, argv[argcount]);	  
	  ch_no = strtol(temp,NULL, 10);			// change to integer  
	  if(ch_no == NULL) { ch_no = 1; argcount--; }		// next argument was probably a file name 	(decrease  argcount)  
	  //printf(" Segment to use : %d \n", ch_no);
	  
	  }	

//	exit(-1);				// for debugging
	

// OPEN image file so we have all its info

	
 	ima_in = open_imaFile(file_in);			// uses itc_io_g function to open image file (a GDALDataset pointer)
	
	xsize = Pixels; ysize = Lines;

	ypixsz = abs(ypixsz);					// GDAL tif files have "y direction: as minus in Northern hemisphere
	
	

//*******************

// Check if output file name given for output bitmap (if not, default filename will be used)

	argcount++;			// next argument
	//printf("Argument %d: %s \n\n", argcount, argv[argcount]);

// IF this  argument is ArcGIS or ArcMap, need to create an output file name

//	if ((strncmp("ArcGIS ",argv[argc-1],3) == 0) )  goto OUT_NAME; // create one, using base file name
	
	//upper_case(argv[argc-1]);
	//if ((strncmp(argv[argc-1],"ARCGIS ",3) == 0) )  goto OUT_NAME; // create one, using base file name	
	
	if (argv[argcount]== NULL) 
	  {
	  printf("\n\t **PROBLEM** with second input bitmap %s \n",argv[argcount]);
	  printf("\t Have an OUTPUT bitmap as second argument on command line or '#'\n\n");  
	  printf("\nUSAGE:  itcsfil_g In_ISOL.tif  Out_Bitmap.tif AREATHR DIAMTHR EXCENT \n");	   
	  exit(-1);
	  }  
	   
	
	if (EQUALN(argv[argcount],"-",1) || EQUALN(argv[argcount],"#",1) ) goto OUT_NAME; // create one, using base file name
	
	strcpy(file_out, argv[argcount]);
	//printf(" File_out  :  %s \n", file_out); 
	
	goto NEXT_PARAM;
	
//	exit(-1);				// for debugging




//*******************

// Create base file name : to create output file name (if defaulted)
	
// Need to get "basefilename" when full path is involved
// Basefile name has path + head of file name (typically correspond to "named area" of study e.g. PRF)
// Area name is assumed separated from rest of file name by an underscore
// However, be careful as there could be underscores in the path

OUT_NAME:

	printf("\n\t **CREATING File_out name ... \n");

	strcpy(fullfilename,argv[1]);			// main input filename (and possibly its dir)
	
	cptr = strtok(fullfilename, ","); 	 		// get rid of comma and item (channel) after comma

	for (ii=0; ii < strlen(fullfilename); ii++)		// search for last underscore position
	  {
	  jj = strlen(fullfilename) - ii;				// start from the end
	  //printf("Count back: %d",j);
	  if(fullfilename[jj] == '_') {basef_len = jj;	break;}	// find last underscore in full file name
	  }
	//printf("\nBase Filename Length:  %d \n", basef_len);
  	
	strncpy(basefname, fullfilename,  basef_len);		// get that part of  the full file name
	basefname[basef_len] = '\0';   					// make it a string to be safe
	
	printf("Base file name ::  %s \n", basefname);	
	
//	Create default OUTPUT file name, concatenate TTs to base file name (path + file name beginning)	

	strncat(basefname,"_ITCs",5);
 	strncat(basefname,".tif",4);
	strcpy(file_out, basefname);
	
	printf("File_out  :  %s \n", file_out); 
	//printf("\n Output Filename Length:  %zd \n", strlen(file_out));


//*******************

NEXT_PARAM:

// Check next input parameter

	argcount++;			// next argument
	//printf("\nArgument %d: %s \n", argcount, argv[argcount]);

// Check AREATHR

	if (argv[argcount] == NULL) 
	  {
	  printf("\n\t ### ERROR ### A third argument is needed \n");
	  printf("\nThe third parameter is the \"Area Threshold\" (min,max) to use\n");
	  printf("\nIf filtering by Diameters(fourth param.) have at least \"-\" as third param.\n");  
	  exit(1);
	  }
	  
	if (EQUALN(argv[argcount],"-",1) || EQUALN(argv[argcount],"#",1) )	   goto DIAMTHR;
	  
	//printf("\n Area Threshold (min,max) as entered : %s\n", argv[argcount]);

	strncpy(temp, argv[argcount], 10);
	ii = icount = 0;
	p = strtok(temp, ",");
	while(p != NULL) 
	  {
 	  //printf("%s\n", p); 
	  areathr[ii++] = strtol(p,NULL, 10);
	  icount = ii;
	  p = strtok(NULL, ", ");
	  }

// Check for human error 

 	  if(icount == 3)
	     {printf("\n\t ### ERROR ### A third element here is unacceptable \n"); exit(-1); }
	 
	 
	if ( icount == 2 ) 
	{	
	lsizthr = areathr[0];		// lower size threshold
	hsizthr = areathr[1];		// higher size threshold
	}
	if ( icount == 1 ) 
	{	
	lsizthr = areathr[0];		// lower size threshold
	hsizthr = 200;			// higher size threshold
	}	
	
	if ( icount == 0 ) 			// use defaults
	{	
	lsizthr = 4;		// lower size threshold
	hsizthr = 200;			// higher size threshold
	}	
	
	printf("\n\tAs per user, area thresholds will be (min,max) : %d,%d \n", lsizthr, hsizthr );
	
	area_flag = 1 ;			// signal area based threshold mode
		
//	exit(-1);				// for debugging


DIAMTHR:


	argcount++;			// next argument
//	printf("\nArgument %d: %s \n", argcount, argv[argcount]);
	
	if ( (argv[argcount] == NULL) && (lsizthr != 0) ) goto BM_IN;  // OK to have just AREATHR and nothing else

	if (EQUALN(argv[argcount],"-",1) || EQUALN(argv[argcount],"#",1) )	   goto EXCENT;
	
	
	if ( (argv[argcount] != NULL) && (lsizthr != 0) ) 
	  {
	  printf("\n\t **PROBLEM**  with input parameters AREATHR and DIAMTHR \n");
	  printf("\t You can not have both AREA or DIAMETER thresholds \n\n");  
	  printf("\nUSAGE: itcsfil_g In_ISOL.tif Out_Bitmap.tif AREATHR DIAMTHR EXCENT \n");	   
	  exit(-1);
	  }  

	

/* 	if ( (EQUALN(argv[argcount],"-",1) || EQUALN(argv[argcount],"#",1) )
			&& (EQUALN(argv[argcount-1],"-",1) || EQUALN(argv[argcount-1],"#",1) ) )
	  {
	  printf("\n\t **PROBLEM**  with input parameters AREATHR and DIAMTHR \n");
	  printf("\t Have at least an AREA or a DIAMETER thresholds \n\n");  
	  printf("\nUSAGE:  itcsfil_g In_ISOL.tif  Out_Bitmap.tif AREATHR DIAMTHR EXCENT \n");	   
	  exit(-1);
	  }  

 */





	printf("\n\tAs per user, diameter thresholds will be (min,max) : %s \n",  argv[argcount]);
	
	strcpy(temp, argv[argcount]);
	ii = 0;
	p = strtok(temp, ",");
	while(p != NULL) 
	  {
 	  //printf("%s\n", p); 
	  diamthr[ii++] = strtof(p,NULL);
	  icount = ii;
	  p = strtok(NULL, ", ");
	  }
	  //printf("\n icount is %d \n", icount);		// number of items

// Check for human error 

 	  if(icount == 3)
	     {printf("\n\t ### ERROR ### A third element here is unacceptable \n"); exit(-1); }	
	  
	if(icount == 1) diamthr[1]= 6.0;			// a default 
	
	//printf("\n Diameter Thresholds (min,max) will be %5.2f , %5.2f \n", diamthr[0], diamthr[1] );
	

	//if (argcnt[4] == 1) diamthr[1] = 10;				// Default max diameter value if none entered 

	low_area = (pi*diamthr[0]*diamthr[0]) / 4;				// Calculate area in meters 
	lsizthr = (int) (low_area / (xpixsz*ypixsz) + 0.5);			// Calculate area in pixels 
	high_area = (pi*diamthr[1]*diamthr[1]) / 4;
	hsizthr = (int) (high_area / (xpixsz*ypixsz) + 0.5);
	
	//printf("\n\tDiameter between %5.2f and %5.2f metres\n", diamthr[0],diamthr[1]);
	
	printf("\n\tFrom diameters, crown areas will be between %5.2f and %5.2f m2 (%d and %d in pixels)\n",
		xpixsz*ypixsz*lsizthr, xpixsz*ypixsz*hsizthr, lsizthr, hsizthr);

	area_flag = 1 ;			// signal area based threshold mode

//	exit(-1);				// for debugging



EXCENT:

	argcount++;			// next argument
	
//	printf("\nArgument %d: %s \n", argcount, argv[argcount]);

	if (argv[argcount] != NULL) excent = strtof(argv[argcount],NULL); 
	
	printf("\n\tAs per user, Excentricity threshold will be %.1f \n",  excent);	


	exc_flag = 1 ;			// signal excentricity  mode
	
//	exit(-1);				// for debugging

// *************************************************	


BM_IN:

//	exit(-1);				// for debugging
	
	printf("\nReading input (ITC) bitmap.\n");
 

	if(segm_in == 0) segm_in = 1;
	isolbitbuf = read_bitmap(file_in, segm_in);			// always one for tiff  file bitmap 
	safety_zone(isolbitbuf);

// allocate memory for output bitmap buffer

	printf("\n\nAllocating memory for output bitmap buffer\n\n");

	outbitbuf = (PixVal *) CPLMalloc(bmsize);	// prep memory for an intermediate bitmap 
	check_mem(outbitbuf);

// Copy full ITC bitmap to output bitmap so you can erase undesirable crowns

	memcpy(outbitbuf, isolbitbuf, bmsize);  	/* copy full ITC bitmap */


//	exit(-1);				// for debugging


//**********************************************************************

//	Filling-in crowns and getting parameters from each crown and
//	erasing undesirable crowns from the output bitmap

//**********************************************************************

printf("\n___________________________________________________________\n");

printf("\n\n\t ** Doing the clean-up of undesirable ITCs\n\n");

p1 = (crown *) malloc(sizeof(crown));		//using same crown structure for all crowns (just need to refresh it)

/* Scanning input bitmap */

for ( i = 1 ; i <= (ysize-1) ; i++ )		/* image starts at (1,1) */
for ( j = 1 ; j <= (xsize-1) ; j++ ) 

  {
  bitnum = (i-1)*(int64)Pixels + j-1 ;			/* bitnum starts at zero */

  /* Find initial 2x2 area of crown material */
  /* Fill that crown and record parameters */

  if (   testbit(isolbitbuf, bitnum)
	&& testbit(isolbitbuf,bitnum+1)
	&& testbit(isolbitbuf,bitnum+xsize) 
	&& testbit(isolbitbuf,bitnum+xsize+1) ) 	 
	{

// Create a list of crowns (IF I was working with a list)
// Presently all done with one crown structure (much faster, less memory)

/*	p1 = (crown *) malloc(sizeof(crown));

    	p1->link = List;
	List = p1;	*/

	
	init_rec(p1);
	fill(j,i,p1);			// get info about crown
	t_crown = t_crown + 1 ;
	
	xdiam = (p1->xmax - p1->xmin);
	ydiam = (p1->ymax - p1->ymin);
	crown_excent = xdiam/ydiam;
	if (crown_excent < 1.0 ) crown_excent=1.0/crown_excent;		// same as ydiam/xdiam
	

// REMOVE tree crowns with inappropriate crown SIZE from output bimap 

	if ( area_flag && ((p1->area < lsizthr) || (p1->area > hsizthr)) )  
	  {
	  erase(j,i,p1); 
	  e_crown = e_crown + 1 ;
	  }

// REMOVE tree crowns with inappropriate crown SHAPE from output bimap 

	else if (exc_flag && (crown_excent > excent)  )
	  {
	  erase(j,i,p1); 
	  e_crown = e_crown + 1 ;
	  }
 
	}	/* end of 2x2 area IF  */


  if ( (j == Pixels) && (i == (i/100)*100 ) )
  fprintf(stdout,"%d lines done \r",i);

  }	/* end of main loop */
 
   fprintf(stdout,"%d lines done \n", Lines);
   

	printf("\n\t**Erased %d of %d total crown found\n\n", e_crown, t_crown);


//**********************************************************

//	clean up of junk tree crowns (small and ill-formed)
//************************************************************


	printf("\nCleaning up small and ill-formed crowns (< 2x2 pixels)\n");

	for ( i = 1 ; i <= ysize ; i++ )
	for ( j = 1 ; j <= xsize ; j++ ) 

	  {
	  bitnum = (i-1)*(int64)Pixels + j-1 ;
	  if ( testbit(isolbitbuf, bitnum) ) 
		{
		clearbit(outbitbuf, bitnum);
		j_count = j_count + 1;
		}
	  }

	printf("\t %d junk pixels removed \n", j_count);
	 

//*********************************************************************
  
 // Writing output  bitmap 
 

	printf("\n\t **Writing output bitmap into: %s \n", file_out);

//	sprintf(Description,"Selected ITCs between %d and %d m2 from %s", lsizthr, hsizthr, file_in);
//	sprintf(Description,"Removed ITCs with excentricities greater than %.1f  from %s", excent, file_in);
	
	sprintf(Description,"Selected ITCs between %d and %d m2 (EXC=%.1f) from %s", lsizthr,hsizthr,excent,file_in);
	
	write_bitmap(outbitbuf, file_out);


// Close input and output images

Exit:	printf("\nClosing both image files and exiting program. \n");

//	GDALClose(file_in);
//	GDALClose(file_out);

time (&rawtime);
timeinfo = localtime (&rawtime);
fprintf(stdout,"\n\n_______________________________\n");
fprintf(stdout,"\n %s (%s) finished at %s\n\n", PROG_NAME, VERSION,  asctime(timeinfo));


// For people using this program via ArcGIS, give then some time to examine the results (before disappearing)

if ((strncmp("ArcGIS ",argv[argc-1],3) == 0) )		// if last argument is ArcGIS or ArcMap
	{
	fprintf(stdout,"\n\n######\n");
	printf("\n Type anything to make this detailed window disappear and terminate %s ",PROG_NAME);
	answer[0] = getc(stdin); 		// gets any answer or <CR>
    }
	
	
exit(0);				// exit properly 

} 		// end of main function


/**************************************************************************/

		/* FUNCTIONS */

/**************************************************************************/

/* function to initialize crown records */

void init_rec(crown *p )

{
	 p->area = 0;		/* crown area */
	 p->xmin = Pixels;	/* diam in both directions*/
	 p->xmax = 0;
	 p->ymin = Lines;
	 p->ymax = 0;
}

/********************************************/

/* This function is a recursive fill routine for a crown in a bitmap.
   It is destructive of the crown in that bitmap (i.e.: clears bit).
   X goes in pixel direction. Y goes in line direction.   
   It accumulates crown area and min&max in both direction 
   to get x&y  diameters and thus, excentricity factor (shape)*/

void fill(int x, int y, crown *pb)

{
	int64 bitnum;
	bitnum = (y-1)*(int64)Pixels + x-1 ;
	clearbit(isolbitbuf, bitnum);

	pb->area = pb->area + 1 ;
	if( x > pb->xmax ) pb->xmax = x;
	if( y < pb->ymin ) pb->ymin = y;
	if( y > pb->ymax ) pb->ymax = y;
	if( x < pb->xmin ) pb->xmin = x;

	if ( testbit(isolbitbuf, bitnum+Pixels) ) 	fill(x,y+1,pb);
	if ( testbit(isolbitbuf, bitnum-1) ) 		fill(x-1,y,pb);
	if ( testbit(isolbitbuf, bitnum-Pixels) ) 	fill(x,y-1,pb);
	if ( testbit(isolbitbuf, bitnum+1) ) 		fill(x+1,y,pb);
}

/********************************************/

/* This function is a recursively erases a crown from a bitmap.
   X goes in pixels direction. Y goes in line direction.   */

void erase(int x, int y, crown *pb)

{
	int64 bitnum;
	bitnum = (y-1)*(int64)Pixels + x-1 ;
	clearbit(outbitbuf, bitnum);
	
	if ( testbit(outbitbuf, bitnum+Pixels) ) 	erase(x,y+1,pb);
	if ( testbit(outbitbuf, bitnum-1) ) 		erase(x-1,y,pb);
	if ( testbit(outbitbuf, bitnum-Pixels) ) 	erase(x,y-1,pb);
	if ( testbit(outbitbuf, bitnum+1) ) 		erase(x+1,y,pb);	
	

}


/********************************************************/
