/*
C+
c	Now called itcvfol_g.cpp
c
c	First part of documentation is on how it was with PCI (and even on ARIES)
c
C       ITCVFOL	(Individual Tree Crown Valley Following)
c
c	Program that produces an output bitmap representing lines and
c	areas of shaded material between tree crowns. Done by following
c	valleys of shaded material (dark) between brighter tree crowns.
c
c
c1	PARAMETERS
c
c	ITCVFOL is controlled by the following global parameters:
c
c	Name	Prompt						Count	Type
c
c	FILE	Database File Name				1-64	Char
c	ILLUMCH	Input Illumination (control) B&W Channel	1	Int
c	NFMASK	Non-forested Area Input Bitmap (a mask)		1	Int
c	VFOLBIT	Resulting Bitmap				1	Int
c	THRESGEN Threshold generation (AUTO/MANUAL/PRESET)	1-64	Char
C	REPORT	Report Mode: TERM/OFF/filename			1-64	Char
c
c2	FILE
c
c	Specifies name of PCIDSK database file from which the image channel
c	is read and from/to which the bitmaps are read and written.
c
c	EASI>FILE="filename"
c
c2	ILLUMCH
c
c	Specifies the input illumination channel, typically a nIR band, or an
c	intensity channel (from IHS), or a vegetation index channel, ...
c	Generally, IT IS RECOMMENDED TO SMOOTH (PCI/FAV) THE INPUT IMAGE.
c	Note: A nIR image may not be ideal to fing snags.
c
c	EASI>ILLUMCH=n		Only one channel is allowed
c
c2	NFMASK
c
c	Specifies an optional input bitmap (non forested mask)
c	to be used as mask eliminating certain areas from processing.
c	For exemple: to eliminate roads, pastures, open areas, ...
c
c	EASI>NFMASK=n
c
c2	VFOLBIT
c
c	Specifies the output segment number for the output bitmap
c	contanning the results of the valley following.
c	If no segment number is given, a new segment will be created.
c
c	EASI>VFOLBIT=n
c
c
c2	THRESGEN 
c
c	The user can let ITCVFOL decide on three thresholds (AUTO)
c	or select to input them manually (MANUAL). Even in the automatic
c	mode, if ITCVFOL considers itself to have calculated bad thresholds,
c	it may ask the user for manual inputs. There is also a PRESET mode
c	for which the three thresholds are assumed to have been set in advance
c	of running ITCVFOL as EASI variables (a SEMI-AUTOMATIC mode convenient
c	for imposing user selected thresholds in a batch process (an EASI script).
c	The EASI variable for the three thresholds is VFOL_THR.
c
c	These thresholds are:
c	lower_thres ->	Pixels with values lower than this threshold will
c	(VFOL_THR[1])	be designated as shade (irrelevant of anything else)
c			This typically gets rids of large shaded areas.
c			Pickup a grey-level at the boundary between pure shade
c			and shaded crown material.
c	upper_thres ->	Pixels with values higher than this threshold will be
c	(VFOL_THR[2])	ignored by the valley following algorithm.
c			This is a crude way to prevent the algorithm from
c			climbing up and splitting big tree crowns (specially 
c			hardwoods) or to deal with sunny forest openings.
c			The prefered approach for the later is to mask these areas
c			using NFMASK. Such masks can be generated by a crude apriori
c			pixel-based unsupervised classification or with tools like
c			NONVEGMASK or AHOMOGEN.
c	plusminus  ->	acceptable range of pixel values for pixels to be considered
c	(VFOL_THR[3])	part of a "relatively" flat valley floor
c
c	NOTE:	The automatic threshold generation process is still not very reliable. 
c
c	EASI>THRESGEN="AUTO
c
c	EASI>THRESGEN="MANUAL
c
c	EASI>VFOL_THR=50,200,1
c	EASI>THRESGEN="PRESET
c
c
c2	REPORT
c
c	Specifies the file to append generated report to:
c
c	EASI> REPORT = "filename"
c
c	Note:  The following names have special meaning:
c
c	EASI> REPORT = "TERM"	| generates reports on your terminal
c	EASI> REPORT = "DISK"	| generates reports on file "IMPRPT.LST"
c	EASI> REPORT = "OFF"	| (may) switch off report generation
c
c
c1	DETAILS
c
c	The pixels are first set where local minima (POTHOLES) exist and then,
c	during various other passes through the image, valleys of low brightness
c	are followed (i.e.:shaded area separating tree crowns) from one pothole
c	to another. However, before all that, a simple parallellipiped
c	classification is performed to speed up the process by classify
c	pure open shaded areas.
c
c	GOAL:	To isolate individual tree crowns as much as possible using
c		shadowed and shaded material
c
c	NOTE:	Allowing for min plateau and "aeq" as opposed to absolute minimum in window
c	offers more opportunities to find potholes (and potholes are important).
c	On the other hand, it means that images should not contain duplicated pixels.
c	This occur when an image resolution is abitrary doubled or when holes are filled
c	by nearest neighbour resampling to correct for sudden plane movements.
c	Thus, IT IS RECOMMENDED TO ALWAYS SMOOTH (FAV) THE INPUT IMAGE (ILLUMCH).
c
C1	REVISION HISTORY
C
c	François A. Gougeon, Ph.D.
c	Remote Sensing Research
c	
C	(©)Natural Resources Canada
c	Canadian Forest Service 
C	
c
c Francois Gougeon	v1.0	Nov 90	On VAX/ARIES as POTHOLES.FOR
c			v1.1	Mar 91	As POTHOLES.FOR
c			v1.2	May 91	Renamed VALLEYFOL.FOR
c
c Carmen Arimescu	v2.0    Oct 93	
c				Moved from the VAX/ARIES environment
c				to the UNIX/PCI environment
c				(Different image files, and bitmaps
c				versus theme files)
c				Renamed VFOL.F, then ITCVFOL.F
c
c Francois Gougeon	v2.1	Oct 95	
c				For input bitmap (as mask) and to deal with
c				bigger images (plus various cleanup of items
c				left from ARIES step by step development)
c				Plus removal of miror buffer around image.
c
c Simon Alexander	v3.1	Sep 96	
c				As itcvfol.c, converted to C from FORTRAN
c				source {ITCVFOL.F}
c 				Note:	most structures/algorithms retained from
c					{monolithic} FORTRAN code
c
c Simon Alexander	v3.2	Oct 96	
c				Algorithm replaced with a similar, single 
c				pass algorithm, upper and lower thresholds
c				automated, bugfix, and
c				integration with other itc programs
c Simon Alexander	v3.3	Nov 96	
c				Clean up memory allocation, fix help, etc.
c				and add capability for 16 bit image
c
c Francois Gougeon	v4.0	Dec 97	
c				Various cleanups and changed I/O parameter
c				names (ILLUMCH,NFMASK,VFOLBIT) for faster
c				consecutive rerun of the whole ITC suite
c
c Francois Gougeon	v4.1	Aug. 98
c				Various cleanups & PCI6.2 adaptation
c
c Francois Gougeon	v4.2	Oct. 98
c				Various cleanups in vfolrules.c because of pothole prob.
c				on images doubled in size by plain pixel replications.
c				Solution: Recommend to always smooth the input image.
c				i.e., a lot of image corrections for plane movements
c				also create duplicated pixels to fill holes in dataset
c
c Francois Gougeon	v4.3	Dec. 98
c				- Adding list of references to help section
c				- Making prog. more robust to user input in MANUAL mode
c				- Modification of thresholds selection:
c					- high thres. recommendation: (histogram range - 10%)
c					- low threshold recommendations: 
c						in MANUAL mode: 10% of histogram range
c					 	in AUTO mode: attempts to remove first population
c							peak (shade) from histogram by using 1st
c							derivative of histogram
c					- also gives a "25% of histogram range" recommendations
c					so user will know it's not that simple and think about
c					doing it themselves if they want "crown area" precision
c					(only affects crown areas close to openings)
c				- Finally, disconnected AUTO mode for 16 bit images (always goes
c				  to MANUAL), leaving the user with 3 recommendations and a 
c				  decision to take.
c
c		NOTE:	Very hard to have a system that works well for 8 and 16 bit data.
c
c Francois Gougeon	v4.4	May 99
c				- Also gave user control over plusminus threshold, because threshold
c				was different whether using a full image or a sub-area (suggestions
c				are based on histogram of image)
c				- Also first trial of PCI6.3
c
c
c Francois Gougeon	v4.5	Aug 99
c
c				- Switched to percentage (of histogram range) based thresholds
c 				  in AUTOmatic mode (for 8-bit images). 
c				  Lower thres => 25% of histogram range
v				  High thres. => -10% of histogram range
c				  Still enforce MANUAL mode on 16-bit images.
c
c Francois Gougeon	v4.51	Oct. 2000
c				
c				- To display time at start and end of program
c
c
c Francois Gougeon	v4.6	Oct.-Nov. 2000
c
c				- Various cleanups to run on PCs (1st ever port to PC world)
c				- args, argcnt, report and some others can not be global vars.
c				  (i.e., just doing STATUS ITCISOL gives a memory access error)
c				- Problems with vars. that are global being also passed as
c				  parameters in functions calls.
c				  (i.e., same type of memory access error)
c				- Some image had PixVal(unsigned char) where it should be
c				  void pointers because images can be 16-bit, thus 32-bit 
c				  storage (e.g., mods in vfolrules.c)
c
c Francois Gougeon	v4.7	Nov. 2000
c
c				- Improved AUTOMATIC threshold decisions and histogram
c				analysis routines (hist.c). AUTO thres. are more conservative
c				and now take into account whether a NFMASK was used or not.
c				- Introduced the THRESGEN="PRESET" mode, a SEMI-AUTOMATIC  
c				mode convenient for imposing user selected thresholds in 
c				a batch process (an EASI script) via presetting the VFOL_THR 
c				EASI variable (parameter).
c
c
c Geoff Savinkoff	v4.8	Sept. 2001
c
c				- Updated to use IDBBitmapIO() instead of flacky IDBSegIO()
c				- Updated to use IDBSegInfoIO, IDBSegDescIO to change segment description
c				- Updated help file with library information
c				- Added global variables Pixels, Lines, Channels
c
c				Oct. 2001
c				
c				- Replaced most IDB functions with GDB functions (not IDBPixelSize or ISBSegInfoIO
c				  as there are no equivelant GDB functions)
c				- Added georeferencing information with GDBGeorefIO
c
c
c v4.9	April 2007 - Jan 2008	François Gougeon
c
c			- Link adaptations for PCI v10.n and its new incompatible PRM.PRM file 
c			  and use of compiler (VS*8) wanting to produce more secure code.
c			  Most PCI routines are in PCI1000.dll, but not all.
c			  For example, IMPTime() and IMPReturn() are now in Core1000.dll
c			  and IMPCounter() in Counter1000.dll
c			  Since I dont have PCISDK or PCI/ProSDK, I had to create LIBs 
c			  from their DLLs to compile my progs (same for PCI 10.1)
c
c			 - Problems with the REPORT (*Report) Variable in Core1000.dll
c			   First use of report makes program crash (i.e., after the start message)
c			   So declared set global var			 FILE *Report;
c			   and do immediately after call to IMPSTATUS()		
c				if(EQUALN(report,"TERM",4)) {Report=stdout;}else{Report = fopen(report, "w");}
c
c
c v5.0	 July 2009	François Gougeon
c
c			- Modified to handle bigger images (bigger than available memory)
c			by reading and analysing them by sections.
c
c v5.1	 Sept. 2009	François Gougeon
c
c			- Modified to handle bigger images (bigger than available memory)
c			by reading and analysing them by sections IN A SEAMLESS WAY
c			(i.e., image sections overlap by BORDER(3) pixels).
c			A line offset "bmoffset" is used to deal with the part of the bitmap
c			corresponding to the active image section.
c
c v5.2	 May 2011	François Gougeon
c
c			- Making better calculations to use images "by sections" by reading the
c			amount of memory that the computer actually has at its disposal.
c			- Capable of dealing with FILENAME (thus path) up to 132 chr long. as per 
c			new standards (PCI > v10.n)
c			- The user can now impose the quantity of total memory to use (within XP 
c			limits, at the moment) using the new ITC/PCI environment variable named
c			ITC_MEM (specified in GB, e.g.: ITC_MEM = 2.5). 
c			If not already by an old DEFITC.EAS, use the following line to define 
c			the new PCI env. vars. :
c			     define ITC_MEM=n,1.0,3.0,-1,"Memory to use (in GB) according to user"
c
c v5.3	 June 2011	François Gougeon
c
c			- Modified to handle bitmaps bigger than 2G positions by reading them
c			in two sections (i.e., the old PCI functions that I have access to
c			are not up to part yet). "Itc_io.c" was modified to take care of that.
c			"Bitops.c" was also modified to use int64 vars to use with pointers 
c			for operations on bitmaps. Outputting bitmaps did not have to be
c			modified as it is synchronized with our work by image sections.
c			"vfolrules.c" had to be modified for (int64) bitnum.
c
c
c v6.0	Feb 2016	François Gougeon
c
c			- Changed to a C++ program to deal with versions of PCI > v10.2
c			     int main (), ".cpp" name, and extern "C" around .h include files
c			- mod to some call to fit new library definitions (as per .def demangling)
c			  which also means mods to corresponding declaration .h files (e.g., gdb.h)
c			  (Since I dont have PCISDK or PCI/ProSDK, I have to create LIB and DEF from
c			  from their DLLs (via DUMPBIN and LIB) in order to compile my progs
c			- modules in files like gdb.h need to be declared 'extern "C++" to link
c			  with proper name mangling (MSVC++ mangling)
c			- ***WORKED**  for PCI 10.3 that migrate its LIB to c++, 
c
c			- HOWEVER, more stuff is needed for PCI 2015 (64bit)
c			- PCI LIB need to be /MACHINE:x64 
c			  and prog compile with 64b version (i.e., vcvarsall amd64)
c			  cause all the call to lib are now with 64bit pointers 
c			- IMPStatus()  uses "char const *"
c
c v6.1	Aug2016		François Gougeon
c
c			- Program was dealing with bitmaps > "2G positions", but had not been
c			  adjusted for bitmap > 2G Bytes (i.e., (int64)bmsize, (int64)iii)
c			- Also, there was issues reading pixel values in image sections > 2GB
c			  as (int64) had not been used in:
c
c				#define img(a,b) ((*get_pix_val)(image,(a)*(int64)pixels+(b)))
c				static int32 get_u8(void *image,int64 pos); etc..
c		
c			  since it was assumed that "long int" was the same as int64, which
c			  is true for Unix, but not true for Windows compilers.
c			
c			NOTE:	At some point in time, this program could operate on bitmap
c				in a "by section" mode to save even more memory.
c				However, this would only be marginally useful with HUGE image
c				on small computers.
c
c v6.2	Sept 2016	François Gougeon
c
c 			- Mod to write "full bitmap" data to segment in one OR two sections  
c			  as needed by its size (if > 2GB) using the new itc_io.cpp function
c			  	write_bmp(idb_fp, vfolbmp, vfolbit)
c
c
c v6.3	Dec. 2016	François Gougeon
c
c 			- For the sake of expediency, the AUTO and MANUAL mode had been unavailable
c			for a while (i.e., issues with get_thres() and threshold variables, ...)
c			Made "lower_thres, upper_thres, plusminus" gobal variables for easy access.
c			I reinstated these modes (only PRESET mode available in v6.2)
c
c
c		 ##### GDAL version (named itcvfol_g.cpp)
c
c v7.0	 Oct 2018	François Gougeon
c
c			- ##### GDAL version (named itcvfol_g.cpp)
c
c			- Input parameters are now picked up from the command line, as in:
c			  > "program" "input smmothed image" "input non forest bitmap" thresgen
c			  > itcvfol_g   Roads_2FAV_Green.tif  Roads_NFor.tif  AUTO
c			  > itcvfol_g   Roads_2FAV_Green.tif  Roads_NFor.tif  PRE 50,200,1
c
c 			- Presently, a fixed output file name is used: "VFOL_BM.tif"
c			  In order to have less parameters to put on command line
c 			  The user can always change the name immediatly after the run if needed (or in a script)
c
c			- Instead of a PCI file containning all, it is assumed that all will be in 
c			  a single "project" directory: images as tif files, bitmap as 1-bit tif files, 
c			  vector layers as shp files, etc., and, that ArcGIS will be used to view all these
c
c			-Does not do analysis by section anymore, but if not enough memory space for a full image 
c			 try the "do it by lines" option, which will save a bit of memory (but, use more time).
cc			  > itcvfol_g   Roads_2FAV_Green.tif  Roads_NFor.tif  AUTO BYLINES 
c			  > itcvfol_g   Roads_2FAV_Green.tif  Roads_NFor.tif  PRE 50,200,1 BYLINES
c			
c			- "Bylines" does not work as expected, it does not save much memory, as GDAL is
c			  wastefull with it internal buffers (does not clean-up or re-use its line buffer). 
c			  Also, writing out by lines does not work (it appears to work, but write an empty image)
c
c			- Note to programmers: As the first program in the ITC-Suite, itcvfol is always messy as
c			  I typical use it for all kinds of testing
c
c
c
c v7.1	 March 2020	François Gougeon
c
c			- Some cleanup and minor mods of GDAL version (now with GDAL v3.0.0)
c
c			- In the local environment, "set PROJ_LIB=D:\GDAL_3.0.0\projlib"  
c			  to avoid tons of projection error messages
c
c
c v8.0a	April 2020	François Gougeon
c		
c			- Re-fixed to deal with 16bit images under GDAL by using, as before,
c			PIX_FUN_PT get_pix_val = get_u8 OR get_16u
c
c			- Got "by lines" mode to work and saves memory
c
c v8.1  April 2021	François Gougeon
c		
c			- Made sure it is completely independent of PCI (for running & compiling)
c			- Introduced a DEBUG mode for me activating "OK to continue" everywhere
c			-
c
c			NOTE: This was my initial test program (for ITC & GDAL) and thus was created before 	
c					creating "itc_io_g.cpp". So it is not using it. In fact it was used to create it.
c
c
c v8.2	Sept 2021	 	François Gougeon
c
c			- Mods for new ana_hist() passing return info about histogram analysis via structure.
c
c
c v8.3	April 2023	François Gougeon
c
c			- Not to assume that all files are in the default directory from which the program is run
c				Previously, everything was assumed in same directory and run from a cmd window from there.
c				NOW, the path used with the main input file is used when creating the default output files
c				This was necessary for ArcGIS Toolkit integration.
c
c
c  v8.4	Nov. 2023	François Gougeon
c
c			- Some code clean-up 
c
c			- Introduced color table and description within output file
c
c
c
c v8.5	Nov. 2024	  François Gougeon 
c
c			- Allow user to specify an output file name (previously, was creating default name)
c
c		USAGE >   itcvfol_g PRF_NIR_Ave.tif  PRF_NonFor.tif PRF_NIR_VFOL_v2.tif auto
c
c		USAGE >   itcvfol_g PRF_NIR_Ave.tif  PRF_NonFor.tif - auto  (prog, will create output filename)
c
c		USAGE >   itcvfol_g PRF_NIR_Ave.tif  PRF_NonFor.tif PRF_NIR_VFOL_v2.tif - (AUTO assumed)
c
c		USAGE >   itcvfol_g PRF_NIR_Ave.pix 5,8 PRF_NIR_VFOL_v2.tif auto
c				** PCI file still accepted where Ch5 is main image and BM8 is non-forest bitmap
c				using gdal numbering scheme (not PCI)
cc
c v8.6	Aug. 2025	François Gougeon 
c
c		- To accept a FOREST mask instead of a non-forest mask by using ",-1" with the file name
c
c		- Fixed a bug preventing use of PRESET mode (i.e., argv[] out of sequence)
c
c
c1	REFERENCES
c
c	Main crown delineation references:
c
c	Gougeon, F.A. 1995. A crown-following approach to the automatic delineation of
c	individual tree crowns in high spatial resolution aerial images. Can. J. Rem.
c	Sens. 21(3):274-284.
c	
c	Gougeon, F.A. 1998. Automatic individual tree crown delineation using a
c	valley-following algorithm and rule-based system. Proc. Int'l Forum on
c	Automated Interpretation of High Spatial Resolution  Digital Imagery for
c	Forestry. February 10-12, Victoria, B.C., Canada.  12 p.

c	Gougeon, F.A.; Leckie, D.G. 2003. Forest information extraction from high spatial 
c	resolution images using an individual tree crown approach. PFC Information Report. 
c	BC-X-396. Natural Resources Canada, Canadian Forest Service, Victoria, B.C., 
c	Canada. 26 p.
c
c	Gougeon, F.A. 2010. The ITC Suite Manual : A Semi-Automatic Individual Tree Crown (ITC) 
c	Approach to Forest Inventories. Natural Resources Canada, Canadian Forest Service, 
c	Pacific Forestry Centre, Victoria, B.C. Canada. June 2010. 92  p. 
c	
c	Other ITC suite references:
c	
c	Leckie D.G. and F.A. Gougeon. 1998. An assessment of both visual and automated
c	tree counting and species identification with high spatial resolution
c	multispectral imagery. Proc. Int'l Forum on Automated Interpretation of High
c	Spatial Resolution Digital Imagery for Forestry. February 10-12, Victoria,
c	B.C., Canada.  12 p.
c	
c	Gougeon, F.A. 1997. Recognizing the forest from the trees: individual tree
c	crown delineation, classification and regrouping for inventory purposes. Pages
c	807-814 in Proc. Third Int. Airborne Rem. Sens. Conf. and Exh., Vol. II.
c	Copenhagen, Denmark, July 7-10, 1997
c	
c	Gougeon, F.A. 1996. Vers l'inventaire forestier automatisé: Reconnaître
c	l'arbre ou la forêt? In CD-ROM of Proc. 9ème Congrès de L'Association 
c	québécoise de télédétection, Québec, May.1-3, 1996. 10 p.
c	
c	Gougeon, F.A. 1995. A system for individual tree crown classification of
c	conifer stands at high spatial resolution. Pages 635-642 in Epp, H.; Taylor,
c	C., eds. Proc. 17th Can. Symp. Rem. Sens, Saskatoon, Saskatchewan, Canada,
c	June 13-15, 1995.
c	
c	Gougeon, F.A. 1993. Individual tree identification from high resolution MEIS
c	images. Pages 117-128 in Leckie, D.G.; Gillis, M.D., eds. Intl. Forum Airborne
c	Multispectral Scanning for Forestry and Mapping (with Emphasis on MEIS).
c	Val-Morin, Québec, Canada, April 13-16, 1992. Inf. Rep. PI-X-113, Forestry
c	Canada, Petawawa Natl. For. Inst.
c	
c	Gougeon, F.A.; Moore, T. 1989. Classification individuelle des arbres à partir
c	d'images à haute résolution spatiale. Pages 185-196 in Bernier, M., et al.,
c	eds. Télédétection et gestion des ressources Vol. VI - 6e congrès de
c	L'association québécoise de télédétection. Sherbrooke, Québec, Canada, May
c	4-6, 1988.
c	
c	
C-
c
C	Dependencies:
C	
C	This program runs under the PCI EASI/PACE Image Analysis System.
C	EASI/PACE is a copyright of 	PCI Inc., 50 West Wilmot St., 
C					Richmond Hill, Ontario, Canada
C	
C
C		Libraries:	pcilib.a	(PCI EASI/PACE lib)
C				libm.a		(Standard Math Library)
C		
C		Includes:	pci.h		(PCI EASI/PACE)
C				string.h	(Standard C string header file)
C				math.h		(Standard C math header file)
C				limits.h	(Standard C limit header file)			
C				itc_io.h	(ITC suite Main IO functions)
C				bitops.h	(ITC suite bit operation functions)
C				hist.h		(ITC suite Histogram functions)
C				vfolrules.h	(ITC suite Valley Following functions)
c
c
c	Linking information (or use the Makefile)
c
c	cc -c  -I/package/pci6.2/lib  -o itcvfol.o itcvfol.c
c	cc -c  -I/package/pci6.2/lib  -o vfolrules.o vfolrules.c
c	cc -c  -I/package/pci6.2/lib  -o hist.o hist.c
c	cc  -o ./exe/ITCVFOL.EXE itcvfol.o 
c			vfolrules.o error.o bitops.o itc_io.o 
c			hist.o /package/pci6.1/lib/pcilib.a -lm 
c
c
C********************************************************************
c
c	DEVELOPMENT HISTORY
c
C 	VALLEYFOL.FOR (AS ARIES/VAX TASK) - this progam produces an output theme
c                   image containing pixels set to theme=2 where local minima
c                   (POTHOLES)exist and, with various other passes through the
c		    image,that follows valleys (i.e.:shaded area separating
c		    trees)producing theme=3,4,5 and 6, but first
c		    it does a simple parallellipiped classifi-
C		    cation (THEME=1) to speed up the process by
C		    classify pure open shaded areas.
c		    GOAL:  to completely isolate individual trees
c
C	NOTE:		ASSUMES YOUR AT THE IMAGE DIRECTORY
C	LINK:		VALLEYFOL,AEQ,DIPIXLIB/LIB
c
c	VALLEYFOL.FOR version 1.0 Nov. 1990 (AS POTHOLES.FOR)
c		      version 1.1 March 1991 (AS POTHOLES.FOR)
c		      version 1.2 May 1991 (renamed VALLEYFOL.FOR)
c
c	by FRANCOIS A. GOUGEON
c	Canadian Forest Service
C	Natural Resources Canada
c	Petawawa National Forestry Institut
c	P.O. Box 2000,
c	Chalk River, Ontario, Canada
c	      KOJ 1JO
c
c	Version 2.0	Oct. 1993 VALLEYFOL.FOR (renamed VFOL.F, then ITCVFOL.F)
c 			FRANCOIS A. GOUGEON with CARMEN ARIMESCU
c
c	Initial Revision to modify software to operate under EASI/PACE v5.2(2)
c	1992, PCI Inc., 50 West Wilmot St., RICHMOND Hill, Ontario, Canada
c	These revisions also change the comenting style to be compatibile
c	with PCI's format so that in-code documentation can be extracted
c	for use in user manuals and for HELP files.
c	Also, a move from VAX/VMS to Unix Solaris
c
c	Version 2.1	Francois Gougeon (ITCVFOL.F) (Oct 95)
c
c			For input bitmap (as mask) and to deal with
c			bigger images (plus various cleanup of items
c			left from ARIES step by step development)
c			Plus removal of miror buffer around image.
c
c
c	Version 3.1 Simon Alexander (itcvfol.c) (SEPT 96)
c
c		Converted to c from FORTRAN source {ITCVFOL.F}
c
c	3.2 (OCT 96)
c
c		algorithm replaced with a similar, single pass algorithm.
c
c		upper lower_thress removed
c
c		lower bound lower_thres automated
c
c		bugfix and integration with other itc programs
c
c	3.3 (NOV 96)
c
c		clean up memory handling and add capability for 16 bit
c		images.
c
C********************************************************************

*** To compile with Visual Studio (VS14)  (see VS14_GDAL_compile.txt)

call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

set INCLUDE=C:\gdal-2.1.1_v2\include;C:\libtiff-4.0.6_64b\tiff-4.0.6\libtiff;%INCLUDE%
set LIB=C:\gdal-2.1.1_v2\lib;C:\libtiff-4.0.6_64b\tiff-4.0.6\libtiff;%LIB%

set LINK=gdal_i.lib  libtiff_i.lib User32.lib

set CL= /MD

CL xxxxxxxxxx.cpp /EHsc

C:\ITC-Suite_GDAL> cl vfolrules.c /c  /TP

C:\ITC-Suite_GDAL> CL itcvfol_g.cpp vfolrules.obj error.obj bitops.obj itc_io.obj hist.obj /EHsc

**********************************************************

NOTE: Newest GDAL library have included "libtiff" (as tiff.lib)so no need to have it anymore

set INCLUDE=D:\GDAL_3.0.0\include;%INCLUDE%
set LIB=D:\GDAL_3.0.0\lib;%LIB%
set LINK=gdal_i.lib  libtiff_i.lib User32.lib
set CL= /MD
CL xxxxxxxxx.cpp /EHsc

set path=D:\GDAL_3.0.0;%PATH%		// to run programs

rem  GDAL v3.0.0 has problem getting to its projection library

set PROJ_LIB=D:\GDAL_3.0.0\projlib

*********************
Ackowlegment to GDAL:

GDAL - Geospatial Data Abstraction Library: Version 2.1.1 (July2016, 64bit), 
GDAL - Geospatial Data Abstraction Library: Version 3.0.0 (Dec. 2019, 64bit),
Open Source Geospatial Foundation, 
Thanks Frank (Warmerdam)



********************************************************************************

	PROGRAM USAGE

	>   itcvfol_g  Roads_Green.tif  Roads_NFor.tif AUTO

	>  itcvfol_g SECTEUR_FG_CH5.tif SECTEUR_FG_BM_NonVeg.tif auto

	will create "VFOL_BM.tif" that you can rename later
	**NOW** extracts from the primary file a base filename and output : basefilename_VFOL.tif

   	was: IMPStatus  ("FILE,ILLUMCH,NFMASK,VFOLBIT,THRESGEN,REPORT;",



********************************************************************************
********************************************************************************

*/

/* 	Modern C (Visual Studio 8 (2005)) do not like us to use the std library (in order 
	to play more secure and to control buffer overruns used by viruses and hackers)
	and thus, it will complain lots unless these two are set 
	You can set them as compiling options as done in ITCSuiteREL_vxxxx.bat.
	
#define _CRT_SECURE_NO_DEPRECATE 1
#define _CRT_NONSTDC_NO_DEPRECATE 1
*/


//#define PARTIAL_GDAL	1	// when still in the process of converting thus some PCI lib 
							// mostly for itc_io vs itc_io_g					

//#define DEBUG_ME 1		// if defined, prog. will show more info for debugging

#define VERSION "v8.6"
#define PROG_NAME "ITCVFOL_G"
#define FILENAME 250
#define BORDER 3
#define sign(i) (i==0?0:(i>0?1:-1))

//#define EQUALN(a,b,n) (strncasecmp(a,b,n)==0)		// should now be in ITC-Suite_g.h

#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <limits.h>
#include <time.h>       // time_t, struct tm, time, localtime
#include <stdlib.h>
//#include <windows.h>		//for Module Handle


#include "ITC-Suite_g.h"	// define lots of vars for the Suite


//#include "pci.h"		// soon, will not be needed
//#include "gdb.h"		// soon, will not be needed
//#include "itc_io.h"


#include "vfolrules.h"
#include "itc_io_g.h"		// my newest GDAL image/bitmap input/output
#include "bitops.h"			// bit operations on bitmaps (mostly macros to be faster)
#include "hist_g.h"
#include "error.h"

// Now in ITC-Suite_g.h
//#include "gdal_priv.h"		// For GDAL library
//#include "ogrsf_frmts.h"		// For OGR


/* function declarations */

void	prep_bmp(PixVal *bmp, int xsize, int ysize);
void	get_thres( PixVal *, int ,int ,int);
void 	thres_manual();
void 	convert_bitnum(int64 bitnum, int64 *byte, int32 *bit);
void 	check_mem();
static 	int32 get_u8(void *image_8b, int64 pos);
static 	int32 get_u16(void *image_16b, int64 pos);

void valley_fol(void *, PixVal *bmp, int pixels, int lines, int lower_thres, int upper_thres, int plusminus); 

PIX_FUN_PTR	get_pix_val; 		 // pointer that allows us to deal with  many types of image (8,16u,16s) 

//PIX_FUN_PTR	get_pix_val = get_u8;		// for the moment deal with 8bit image only


/* Global declarations */

typedef unsigned char  PixVal;

int	first, last, data_type = CHN_8U;
int	Lines, Pixels, Channels;
int	sect=0,	dbiw[4];
int	bmoffset = 0;			/* offset in line to beginning of next image section (in by-section mode ) */
					/*Really an int32 vars, but made int64 cause it often used in calculation leading to an int64 results */
int64	bufoffset;			/* offset in byte in the bitmap buffer */
int	illumch, nfmaskflag=1, vfolbit;

int	lower_thres=1, upper_thres=255, plusminus=1;
char 		Extension[10]="";

	
hist_inf *ph; 		// pointer to structure to store info extracted from histogram by ana_hist()


FILE	*idb_fp;
FILE 	*Report;

time_t rawtime;
struct tm * timeinfo;

GDALRasterBand	*piiBand;
char 		illumin_fname[80];
PixVal		*pafScanline, *image_8b;
uint16		*pafScanline16, *image_16b;
int64 		bmsize;			// size of bitmap in bytes



int	by_lines=0, by_image=1;		// default is to read/write by image (faster), 
					// user can specify bylines (slower) if not enough memory to go by image

GDALDataset	*ima_in, *ima_out;
GDALDataset	*vfol_bmp, *nf_bmp;

PixVal  *nfmaskbuf;	// For bitmap buffers

GDALDriver *poDriver;

char **papszOptions = NULL;

GDALRasterBand	*piBand, *poBand;


char **papszMetadata;

double		adfGeoTransform[6], adfGeoTransform2[6];

int 		PCI_File = 0;			// initial flags for image file type
int 		TIF_File = 0;
char		*basefname;

//*******************************************************
// 		Main program 

//*******************************************************


int main(int argc, char *argv[])
{

/* local declarations */

PixVal         *vfolbmp, *nfbmp;
PixVal		*bitmap_in, *bitmap_out;		// use for input output of bitmaps

int             lines, pixels, channels;
float		xpixsz, ypixsz, apixsz;
char		pixunit[40];
char            chr[256], geosys[17];
char 		*timedate;
int          xoff = 0, yoff = 0;

uint64		mem_needed, mem_needed_BM, mem_needed_IMA=0, mem_needed_TOT, mem_avail_IMA, mem_avail_SYS;
int 		segtype, blocks;
char		segflag, segname[9], history[56], description[128];
long 		start, length;
double		topleftX,transformX,topleftY,transformY;

void           *args[6];
int             argcnt[6];
char            file[FILENAME];
char            thres_type[20];
char            report[FILENAME];
int 		actval, numbuf[3];
float		rnumbuf[1];
int		no_of_sections = 1;
int64		bmoffspos=0;
int		xsize, ysize, sect_size;
int		bit;
int64		byte, iii, tcount;
//TBool		*nada;
float 		imgarea;
int 		i,j;
int64 		bitnum;
float		pminus;

int64 		sum=0, sum0=0, count=0;
int 		input_ch[10];


int 	ch_in=1, ch_out, input_thres[20],  ii=0, ich=0;
int	in_ch[1];
int	input_bm[20], no_bm, ibm, jj=0;
char 	*Proj1, *Proj2, *Proj3;

int no_items;


char		filename[FILENAME], fullfilename[FILENAME], shortfilename[FILENAME];
char		basefname[FILENAME], mainfname[FILENAME], directory[FILENAME];
char		file_out[FILENAME], nfmaskfname[FILENAME],extension[10];
char 		*pch,*cptr;

int 		name_given = 0;		// flag output file name given(1) or not(0)

char 	*tstring, *p;
char 	ch_no[10], ext[4];
char 	bm_no[10], answer[10], temp[10], bigtemp[1000];


//*****************************************************************************


// Print Program Header 

	time (&rawtime);
	timeinfo = localtime (&rawtime);
	printf("\n\t\tStarting %s (%s) at %s\n", PROG_NAME, VERSION, asctime(timeinfo));

// Registers for all types of files with GDAL

	GDALAllRegister(); 	

// Check Arguments on command line

	if (argc < 3) 
	  {
	  printf("\n\t *** PROBLEM with arguments on the command line\n");
	  printf("\tThe following are the minimum compulsary parameters : \n");
	  printf("\tTypical:  itcvfol_g PRF_ADS_NIR_2FAV.tif PRF_ADS_NFmask.tif AUTO\n");
	  printf("\tOther: itcvfol_g xxxxxxx.tif yyyyyyyyy.tif PRE 50,200,1\n");
	  printf("\tPossible : itcvfol_g PRF_ADS_30x11.pix 5,9 AUTO\n");
	  exit(1);
	  }   
	  
// Open IMAGE FILE and get info (needed for input parameters checking)

// NEWER I/O form "itc_io_g", not used here yet, too many mods needed to global vars

/*
	strcpy(filename, argv[1]);
		  
	ima_in = open_imaFile(filename);			
	
	xsize = Pixels; ysize = Lines;		// use throughout program
	bmsize = (Pixels * (int64)Lines + 7) / 8; 
*/


	
// Check if tif file or PCI file. If PCI multi-channel,  ask channel numbers for raster and non-for

	strcpy(fullfilename, argv[1]);
	printf("Full Input Filename:  %s \n\n", fullfilename);
	
	pch = strtok(fullfilename,".");				// put a NULL where "." was
	strcpy(mainfname, fullfilename);	
	printf("Mainfname:  %s \n", mainfname);		
	pch = strtok(NULL," \0"); 			//continue search on original fullfilename 
	strncpy(extension, pch, 3);
	
	//printf("  Extension : %s\n", extension);	

	//	exit(0);		// for debugging
	
	strcpy(Extension, extension);		// global variable for some other prog.	

// Create SHORT file name (no dir) for display convenience and later, for output file description

	strcpy(shortfilename, argv[1]);
//	printf("Shortfilename :  %s \n", shortfilename);

	pch = strtok(shortfilename,"/");
	while(pch != NULL)
	  {
		//printf ("pch : %s\n",pch);
		strcpy(shortfilename, pch);
		pch = strtok(NULL, "/");
	  }		
	//printf("Shortfilename:  %s \n", shortfilename);

	
	
// Extension is a global parameter set by Open_imaFile()
	
	if (EQUALN(Extension,"pix",3)) PCI_File = 1;	// everything is in the PCI file
	if (EQUALN(Extension,"tif",3)) TIF_File = 1;	// everything is in directory, mostly as tif files
	if (! ( PCI_File || TIF_File))
	  {
	  printf("\n\n**ERROR** Program not able to deal with image file of type %s\n\n", Extension);
	  exit(-1);
      }
	
//If PCI multi-channel file,  ask channel numbers for image and non-forest	mask
// Check list of "CHANNELS to use" in argv[2]


	if (PCI_File)
	 {
	  printf("\nAs per user, input raster channel and mask to use: %s \n", argv[2]);

	  strcpy(temp, argv[2]);  p = strtok(temp, ","); ii = 0;

		while(p != NULL) 
		  {
		  //printf("%s\n", p); 
		  input_ch[ii++] = strtol(p,NULL, 10);
		  p = strtok(NULL, ",");
		  }
		no_items = ii;

	  //printf("Number of items : %d \n\n", no_items);
	  
	  if(no_items != 2)
	  {
	  printf("\n**ERROR** \tWith PCI file, 2nd argument must contain two numbers\n");	  
	  printf("\t\tOne pointing to a smoothed channel, the other to a NonForest mask\n");	 		  
	  printf("\t\tUsing GDAL nomenclature : BM# follow image# (i.e., not PCI #)\n");
	  exit(-1); 
	  }		  
	   
	 }		// endof if PCI file
		
	
// Check other arguments on command line : nfmask.tif  & outfile &threshold flag

	if (TIF_File)		// if main is a tif file, non-forest mask is also a tif file
	 {
	 if (argv[2] == NULL) 
	  {
	  printf("\n\n PROBLEM with NON FOREST MASK image %s \n",argv[2]);
	  printf("\tHave an input non-forest mask as 2nd argument on command line \n\n");
	  exit(1);
	  } 
	
	if ( EQUALN(argv[2],"-",1 ) || EQUALN(argv[2],"#",1 ) )
	  {
	  printf("\nArgument %d is \"-\" or \"#\", which implies no input NFMASK bitmap to \"consider\" \n",2); 
	  nfmaskflag = 0;
	  }
	
	
// Check for a comma cause ",-1" implies NFMASK is a FOREST mask
	
	strcpy(temp, argv[2]);  
	cptr = strtok(temp, " ,"); 				// go to comma (or space) and put a null there	
	strcpy(nfmaskfname, temp);		// save the file name (save a clean file name)
//	printf(" NFMASK Filename (no extra):  %s \n", nfmaskfname);	


	cptr = strtok(NULL, " ,");			// continue

	if(cptr != NULL) 
	  {
	nfmaskflag = strtol(cptr, NULL, 10);	// will set nfmaskflag to -1 if a -1 is there

//	printf(" nfmaskflag :  %d \n", nfmaskflag);
//	printf(" FOREST MASK Filename :  %s \n", nfmaskfname);

	if (nfmaskflag != -1) 
		  {
		  printf("\n\t **PROBLEM** with NFMASK bitmap %s \n",argv[2]);
		  printf("Only a -1 is acceptable here to signal a FORMASK instead of a NFMASK \n\n");  
		  
		  printf("\nUSAGE: lattops_g FILE,ILLUMCH NFMASK,-1 DIRMASK WINDSIZ THRSHADE SUNANG FORTYPE TTBITM\n");	  
		  printf("USAGE: lattops_g Main_File.ext,CH# bitmap bitmap windsiz thres1,thres2 SUNANG FORTYPE TT_fname\n");
		  exit(-1);
		  }  
		  
	  printf("\n Second tif file < %s > now considered a FOREST MASK due to a ',-1' \n", nfmaskfname);
	  }

	printf("\nAs per user, input non-forest mask to use: %s \n", nfmaskfname);

	} 			// end of if TIF -- file gets open later







//	Third argument
	  
 if ( EQUALN(argv[3],"-",1 ) || EQUALN(argv[3],"#",1 ) )
	  {
	  printf("\nThird argument is \"-\" or \"#\", which implies no output file given \n");
	  printf("A new output bitmap will be created based on \"base file name\" \n\n"); 
	  name_given = 0;
	  }	
 else
	{
	strcpy(file_out,argv[3]);
	name_given = 1;
	printf("\nAs per user, ouput file name to use: %s \n", argv[3]);
	}
 
//	Fourth argument
 
	 if (argv[4] == NULL) 
	  {
	  printf("\n\t ### ERROR ### a fourth argument is needed \n");
	  printf("\nFourth argument should be a threshold generation mode (AUTO/MANUAL/PRESET).\n");
	  exit(1);
	  }
	  
 if ( EQUALN(argv[4],"-",1 ) || EQUALN(argv[4],"#",1 ) )
	  {
	  printf("\nFourth argument is \"-\" or \"#\", which implies AUTOmatic thresholds selection is assumed \n");
	  strcpy(thres_type,"AUTO");
	  }	
 else{	  
	strncpy(thres_type,argv[4],10);		// bring-in argv[4] as thres_type  
	 }

	//exit(-1);		// for input testing


	if (  !EQUALN(thres_type,"AUTO",3) && ! EQUALN(thres_type,"MANUAL",3) && ! EQUALN(thres_type,"PRESET",3) )
	  {
	  printf("\nThird argument should be a threshold generation mode (AUTO/MANUAL/PRESET).\n");
	  exit(1);
	  }

	printf("\nAs per user, thres_type : %s \n\n",thres_type);

//	printf("argc : %d \n\n",argc);		// remember argv start at 0 (program), but argc=1 by them


	if( (EQUALN(thres_type,"PRE",3)) && (argc < 6) ) 
	  {
	  printf("\n\t ### ERROR ### In PRESET mode, other arguments are needed \n");
	  printf("\nFifth argument should have at least the lower threshold for shade areas.\n");
	  exit(1);
	  }
	  
	  
/* 
	if( (argc == 5) && (EQUALN(argv[4],"BYLINES",4)) || (argc == 6) && (EQUALN(argv[5],"BYLINES",4)) ) 
	//if( (argv[4] != NULL) && (EQUALN(argv[4],"BYLINES",4)) || (argv[5] != NULL) && (EQUALN(argv[5],"BYLINES",4)) ) 
	//if(  EQUALN(argv[3],"BYLINES",4) ||  EQUALN(argv[4],"BYLINES",4) ||  EQUALN(argv[5],"BYLINES",4) ) 
	  {
	  by_lines = 1; by_image = 0;
	  printf("\nAs requested: Will read/write images/bitmaps by lines to save memory\n\n");
	  }
 */

/*
	NOTES: 
	"by_lines" does not do as expected, not much saving
	Reading an image still take twice its size: your image buffer and GDAL internal buffer
	Reading a bitmap takes one image size and one bmsize (saved one image size)
	writing out a bitmap (at the end) takes two image size in image mode and one in line mode.

*/

	//exit(-1); 		// for debuggging input params

//******************************************************

// Open the ILLUMIN image and Read georeferencing

//******************************************************

// Open input ILLUMIN image  (PCI or TIF file) 

	//GDALAllRegister(); 	 		// registers for all types of image files

	Proj1 = (char *) CPLMalloc(1000);				// to store geo projection info
	strcpy(illumin_fname,argv[1]);

	ima_in = (GDALDataset *) GDALOpen( argv[1], GA_ReadOnly );		//pointer to file dataset 

	if (ima_in == NULL) 
	  {printf("\n\n PROBLEM opening image file %s \n\n",argv[1]); exit(1);}

  	strcpy(fullfilename,argv[1]);			// main filename as base
	
	fprintf(stdout,"\t*File '%s' was opened for reading\n\n",fullfilename);

	//goto FINISH;
		
// Print generic info of input file (driver used,... )

	printf( "Driver: %s/%s\n", ima_in->GetDriver()->GetDescription(),
 		ima_in->GetDriver()->GetMetadataItem( GDAL_DMD_LONGNAME ) );

	Pixels = xsize = ima_in->GetRasterXSize();
	Lines = ysize = ima_in->GetRasterYSize();
    Channels = channels = ima_in->GetRasterCount();

	printf( "Image size is %d x %d x %d CHs\n\n", Pixels, Lines, Channels );

	bmsize =  ((Pixels*(int64)Lines+ 7) / 8);    // size of bitmaps in byte
	//printf( "Internal bitmap  size will be %Ii \n\n",bmsize);

// Print geographic projection info of input file

	strncpy(Proj1, ima_in->GetProjectionRef(),1000);

	//if( ima_in->GetProjectionRef() != NULL)  printf( "Projection is '%s'\n\n", Proj1);
 

// Get Proper Geo projection of ILLUMIN image

	if( ima_in->GetProjectionRef() != NULL ) 
	  {
	  strncpy(bigtemp, ima_in->GetProjectionRef(),1000);
	  //printf("Bigtemp: %s \n", bigtemp);	  
	  strtok(bigtemp, "\"");			// go pass the double quotes
	  //printf("1st section : %s \n", bigtemp);  
 	  Proj1 = strtok(NULL, "\"");	// go to next  double quotes
	  printf("Projection: %s \n", Proj1 );
	  }	  
	  
	  
// Get GeoTransform of ILLUMIN image

	if( ima_in->GetGeoTransform( adfGeoTransform ) == CE_None )
	  {
 	  topleftX = adfGeoTransform[0];		
	  topleftY = abs(adfGeoTransform[3]);
	  xpixsz = transformX = adfGeoTransform[1];	
	  ypixsz = transformY = adfGeoTransform[5];

   	  printf( "Origin = (%.2f,%.2f)\n", adfGeoTransform[0], adfGeoTransform[3] );
    	  printf( "Pixel Size = (%.2f,%.2f)\n", adfGeoTransform[1], adfGeoTransform[5] );
	  }


	  //exit(1);		// for testing


// Using first (and only) channel in the image file
// IF more than one channel, ask user which one
/*
	if (channels > 1 )
	  {
	  printf("\nMore than one channel in image file. Which one to use? ");
	  scanf("%d",in_ch);	ch_in = in_ch[0];	
	  }

	piiBand = ima_in->GetRasterBand(ch_in);
*/


	if (TIF_File) 	piiBand = ima_in->GetRasterBand(1);
	
	if (PCI_File) 	piiBand = ima_in->GetRasterBand(input_ch[0]);	
	
	
// Check raster type (8 or 16 bit) and set flag PCI data Type CHN_8U=1 CHN_16U=3

	if(EQUALN(GDALGetDataTypeName(piiBand->GetRasterDataType()),"Byte",4)) data_type=CHN_8U;  	//PCI data types
	if(EQUALN(GDALGetDataTypeName(piiBand->GetRasterDataType()),"Uint16",6)) data_type=CHN_16U;


	if ( data_type==CHN_8U) get_pix_val = get_u8;
	if ( data_type==CHN_16U) get_pix_val = get_u16;

	printf("RasterDataType =%d, Type = %s, PCI data_type = %d \n",
			 piiBand->GetRasterDataType(), GDALGetDataTypeName(piiBand->GetRasterDataType()), data_type );

	 // exit(1);		// for testing


//  Read the ILLUMIN image (whole or by lines)

  	//printf("*Allocating memory to the image\n");

	if(data_type==CHN_8U) 
		{image_8b = (PixVal *) CPLMalloc(sizeof(PixVal)*Pixels*(int64)Lines); check_mem(image_8b);}
	if(data_type==CHN_16U) 
		{image_16b = (uint16 *) CPLMalloc(sizeof(uint16)*Pixels*(int64)Lines); check_mem(image_16b);}

	if(data_type==CHN_8U)
	  printf("\n Allocated memory (%I64d bytes) to the image. ",Pixels*(int64)Lines);
	if(data_type==CHN_16U)
	  printf("\n Allocated memory (%I64d bytes) to the image. ",2*Pixels*(int64)Lines);

// Time to check memory usage with task manager

#ifdef DEBUG_ME
	  printf("\n OK to continue(y/n)? ");
	  //scanf("%s",answer);			// gets any answer, but get one
	  answer[0] = getc(stdin); 		// gets any answer or <CR>
	  if(answer[0]=='n')  exit(1);
#endif

// Read the whole input image IN ONE SHOT 

	if(by_image)
	{
 	printf("\n\n\t* Reading FULL ILLUMINATION image into memory ... \n\n");

	if(data_type==CHN_8U) 
		piiBand->RasterIO(GF_Read, 0, 0, Pixels, Lines, image_8b, Pixels, Lines, GDT_Byte, 0, 0 );
	if(data_type==CHN_16U) 
		piiBand->RasterIO(GF_Read, 0, 0, Pixels, Lines, image_16b, Pixels, Lines, GDT_UInt16, 0, 0 );

	}		// end of if(by_image)

 
	//exit(-1);		// for testing


// Read the image line by line instead

	if(by_lines)
	{
 	printf("\n\n\t* Reading (by line) ILLUMINATION image into memory ... \n\n");

	if(data_type==CHN_8U) 
		{pafScanline = (PixVal *) CPLMalloc(sizeof(PixVal)*Pixels); check_mem(pafScanline); }	// create an 8-bit line buffer

	if(data_type==CHN_16U) 
		{pafScanline16 = (uint16 *) CPLMalloc(sizeof(uint16)*Pixels); check_mem(pafScanline16); }	// create a 16-bit line buffer

	for (i = 1; i <= Lines; i++)		// using  PCI notation image starting at (1,1)
	  {

	  if(data_type==CHN_8U) 
	    {
	    piiBand->RasterIO(GF_Read, 0, i-1, Pixels, 1, pafScanline, Pixels, 1, GDT_Byte, 0, 0);
	    for ( j = 1 ; j <= Pixels ; j++ ) { bitnum = (i-1)*(int64)Pixels + j-1 ; image_8b[bitnum] = pafScanline[j-1]; }
	    }

	  if(data_type==CHN_16U) 
	    {
	    piiBand->RasterIO(GF_Read, 0, i-1, Pixels, 1, pafScanline16, Pixels, 1, GDT_UInt16, 0, 0);
	    for ( j = 1 ; j <= Pixels ; j++ ) { bitnum = (i-1)*(int64)Pixels + j-1 ; image_16b[bitnum] = pafScanline16[j-1]; }
	    }

 	  if( (i/100)*100 == i ) printf("%d lines done\r", i);

	  }
	printf("\n");
	}		// endof if(by_lines)



// Check if image has something in it

/*
	sum = 0; sum0 = 0;

	for ( i = 1 ; i <= (ysize) ; i++ )	// PCI image starting at (1,1)
	  for ( j = 1 ; j <= (xsize) ; j++ ) 

	  {
	  bitnum = (i-1)*(int64)Pixels + j-1 ;
	  if ( (int)image_8b[bitnum] > 0)  sum++;
	  if ( (int)image_8b[bitnum] == 0)  sum0++;
	  }

	printf("\nQuantity of pixels with a grey level in the image: %Ii \n", sum);
	printf("Quantity of pixels at zero in the image: %Ii \n", sum0);
*/
 	//exit(1);  

// Time to check memory usage with task manager
#ifdef DEBUG_ME
	printf("\n Read ILLUMINATION image. OK to continue(y/n): ");
	answer[0] = getc(stdin); 		// gets any answer or <CR>
	if(answer[0] == 'n') exit(-1);

	//GDALClose(ima_in);

	  printf("\n After closing ima_in. OK to continue(y/n): ");
	  answer[0] = getc(stdin); 		// gets any answer or <CR>
	  if(answer[0] == 'n') exit(-1);
#endif


	 // exit(1);		// for testing
	 
	 
//************************************************

// Open and read file containning the NFMASK bitmap 

//************************************************

	printf("\n\t* Opening NON-FOREST MASK file ... \n\n");
	
		
	//exit(-1); 		// for debugging


	Proj2 = (char *) CPLMalloc(1000);

	if(TIF_File)
	  {
	  nf_bmp =  (GDALDataset *) GDALOpen( nfmaskfname, GA_ReadOnly );		// nf_bmp is pointer to GDAL file
	  if (nf_bmp == NULL) 
	     {printf("\n\n PROBLEM opening non-forest mask file %s \n\n",nfmaskfname); exit(1);}
	 
	  fprintf(stdout,"Bitmap (NFMASK) '%s'  opened for reading\n\n", nfmaskfname);

 
	  //printf("\nBand Description: %s \n", nf_bmp->GetDescription() ); 
  
  	  }
 

  
  
	if(PCI_File)
	  {
	  //nf_bmp =  (GDALDataset *) GDALOpen( input_ch[1], GA_ReadOnly );		// nf_bmp is pointer to file dataset  
	  nf_bmp = ima_in;
	  if (nf_bmp == NULL) 
	    {printf("\n\n PROBLEM opening image file %d \n\n", input_ch[1]); exit(1); }
	
	  fprintf(stdout,"\tBitmap (NFMASK) CH%d  opened for reading\n\n", input_ch[1]);
	  }

// Print generic info of input file (driver used,... )

	printf( "Driver: %s/%s\n",nf_bmp->GetDriver()->GetDescription(),nf_bmp->GetDriver()->GetMetadataItem( GDAL_DMD_LONGNAME ) );
	printf( "Image size is %d x %d x %d CH\n\n", nf_bmp->GetRasterXSize(), nf_bmp->GetRasterYSize(),nf_bmp->GetRasterCount() );


// Print geographic info of input file

	strncpy(Proj2, nf_bmp->GetProjectionRef(),1000);

	//if( nf_bmp->GetProjectionRef() != NULL)  printf( "Projection is '%s'\n\n", Proj2);


	if( nf_bmp->GetGeoTransform( adfGeoTransform2 ) == CE_None )
	  {
	  printf( "Origin = (%.2f,%.2f)\n", adfGeoTransform2[0], adfGeoTransform2[3] );
	  printf( "Pixel Size = (%.2f,%.2f)\n", adfGeoTransform2[1], adfGeoTransform2[5] );
	  }

// Check same image size
	
	if( (nf_bmp->GetRasterXSize() != Pixels) || (nf_bmp->GetRasterYSize() != Lines) )
		{printf("\n\n PROBLEM with image SIZE compatibilty of file %s \n\n",nfmaskfname); exit(1);}


//	if( adfGeoTransform2[0] != adfGeoTransform[0] || adfGeoTransform2[3]!= adfGeoTransform[3] ||
//		adfGeoTransform2[1]!= adfGeoTransform[1] || adfGeoTransform2[5]!= adfGeoTransform[5] )
		
	if( (abs(adfGeoTransform2[0]-adfGeoTransform[0]) > 0.005) ||
		(abs(adfGeoTransform2[3]-adfGeoTransform[3]) > 0.005) ||
		(abs(adfGeoTransform2[1]-adfGeoTransform[1]) > 0.005) || 
		(abs(adfGeoTransform2[5]-adfGeoTransform[5]) > 0.005) )		
			{printf("\n\n PROBLEM with image UTM compatibilty of files %s \n\n",nfmaskfname); exit(1);}


	printf("\n**Image sizes and UTM coordinates are compatible \n\n");

	//exit(-1); 		// for debugging

// Check same Geo projection as ILLUMIN

/* 

//	if( nf_bmp->GetProjectionRef() != NULL ) 
	if( nf_bmp->GetProjectionRef() != nullptr ) 	
	  {
	  strncpy(temp, nf_bmp->GetProjectionRef(),30);
	  strtok(temp, "\"");
	  printf("1st section : %s \n", temp);
 	  Proj2 = strtok(NULL, "\"");
	  printf("Projection: <<%s>> is %s \n", argv[2], Proj2 );
	  }
	  else 
		printf("\n\n NOTE: It appears that ''%s'' geo. projection is not available\n\n", argv[2]);

	if (strncmp(Proj2, Proj1, 20) == 0) 	printf("\n**Image geographic projections are compatible \n\n");
		
	if (strncmp(Proj2, Proj1, 20) != 0) 
		printf("\n\n NOTE: It appears that ''%s'' geo. projection is not the same as main image file\n\n", argv[2]);

 */
 
// Open NFMASK bitmap (1-bit tif) file and create internal bitmap

	if(TIF_File) printf("\n\t* Reading NON-FOREST MASK from %s \n\n", nfmaskfname);
	
	if(PCI_File) printf("\n\t* Reading NON-FOREST MASK from %d \n\n", input_ch[1]);
		
	nfmaskbuf = (PixVal *) CPLMalloc(bmsize);				// allocate memory for the bitmap
	//printf("\nAllocating %Ii bytes of memory for an internal  1bit bitmap\n",bmsize);

	if (TIF_File) piBand = nf_bmp->GetRasterBand(1);
	
	if (PCI_File) piBand = nf_bmp->GetRasterBand(input_ch[1]);
	
//	printf("RasterDataType = %d and Type = %s \n", 
//		piBand->GetRasterDataType(), GDALGetDataTypeName(piBand->GetRasterDataType()) );

		
// Check that incoming channel is a bitmap before doing anything (otherwise you'll get junk)

	//if ( strncmp(piBand->GetMetadataItem("NBITS","IMAGE_STRUCTURE"),"1",1 ) != 0)
	if ( piBand->GetMetadataItem("NBITS","IMAGE_STRUCTURE") == NULL)
	  {
	  printf("\n\t*** Apparently, the specified image//channel(NFMASK) is not a bitmap layer\n");
	  printf("\tPlease double check (Hint: use gdalinfo on the file).... Exiting\n\n");
	  exit(1);
	  }

	//printf("\nImage Description: %s \n", ima_in->GetDescription() );

	//printf("\nBand Description: %s \n", piBand->GetDescription() );		
		
	//printf("Before NFMASK in -- thres_type = %s \n", thres_type);	
		
// *******

// Read NFMASK bitmap (1bit tif) in one shot  (full image via an 8bit buffer)

	if(by_image)
	{
	//printf("\nAllocating %Ii bytes of memory to read 1bit tif as 8bit image\n",sizeof(PixVal)*Pixels*(int64)Lines);

	bitmap_in = (PixVal *) CPLMalloc(sizeof(PixVal)*Pixels*(int64)Lines); // allocate memory for Full 8bit image

	nfbmp = (PixVal *) calloc(bmsize,1);			// allocate memory for the bitmap
	
	
	piBand->RasterIO(GF_Read, 0, 0, Pixels, Lines, bitmap_in, Pixels, Lines, GDT_Byte, 0, 0 );


// Time to check memory usage with task manager

#ifdef DEBUG_ME
	printf("\n NFMASK was read (1bit tif as 8 bit). OK to continue(y/n): ");
	answer[0] = getc(stdin); 		// gets any answer or <CR>
	if(answer[0] == 'n') exit(-1);
#endif

// Test

	count = 0;
	for (ii=0; ii<Pixels*Lines; ii++) if (bitmap_in[ii] == 1) count++;
	printf("\n\tPixels set in input NFMASK 8bit bitmap = %Ii \n\n", count);


// Turn "8bit image" into a bitmap for further processing (i.e.,to be compatible with PCI version of main code)

	//printf("** Turning input tif (nbits=1, read as 8bit) into a bitmap in memory\n");

	for ( i = 1 ; i <= (ysize) ; i++ )		// For compatibility with PCI(x,y), I kept image coordinates start at (1,1)
	for ( j = 1 ; j <= (xsize) ; j++ ) 		// However, GDAL images start at zero (similar to bitmaps), so bytenum=bitnum

	  {
	  bitnum = (i-1)*(int64)Pixels + j-1 ;		// bitnum starts at zero, so does image, so bytenum=bitnum
	  if (bitmap_in[bitnum])  setbit(nfbmp, bitnum);	// if set in byte image, set in bitmap
	  if(nfmaskflag == -1)  flipbit(nfbmp, bitnum);		// if FOREST mask, flip whatever is there (also 0 to 1)
	  }

	} 		// endof if(by_image)


// *******

// Read NFMASK bitmap line by line (see if different) and create bitmap in that loop

/* 
	if(by_lines)
	{

	printf("\n\t* Reading non-forest mask (line by line) from ''%s'' \n\n", nfmaskfname);

	pafScanline = (PixVal *) CPLMalloc(sizeof(PixVal)*Pixels);	// create an 8-bit single line buffer

	for ( i = 1 ; i <= (ysize) ; i++ )		// For compatibility with PCI(x,y), I kept image coordinates start at (1,1)
	  {
	  piBand->RasterIO(GF_Read, 0, i-1, Pixels, 1, pafScanline, Pixels, 1, GDT_Byte, 0, 0 );

	for ( j = 1 ; j <= (xsize) ; j++ ) 

		if (pafScanline[j-1]==1) 
		{
		bitnum = (i-1)*(int64)Pixels + j-1 ; 
		setbit(nfbmp,bitnum);			// convert to bit
		}

 	  if( (i/100)*100 == i ) printf("%d lines done\r", i);
	  }
	printf("\n");

	}		// endof if(by_lines)

 */



// Check if NFMASK bitmap (bitmap_in) has something in it

	count = 0;
	for (ii=0; ii<bmsize*8; ii++) if (testbit(nfbmp, ii)) count++;
	if(nfmaskflag == 1)		printf("Pixels set in input NFMASK bitmap = %Ii \n\n", count);
	if(nfmaskflag == -1)	printf("Pixels set in input FOREST bitmap = %Ii \n\n", count);


// Time to check memory usage with task manager

#ifdef DEBUG_ME
	  printf("\nRed NFMASK bitmap. OK to continue(y/n): ");
	answer[0] = getc(stdin); 		// gets any answer or <CR>
	  if(answer[0] == 'n') exit(-1);
#endif

	GDALClose(nf_bmp);

// Time to check memory usage with task manager

#ifdef DEBUG_ME
	  printf("\nAfter closing nf_bmp. OK to continue(y/n): ");
	  answer[0] = getc(stdin); 		// gets any answer or <CR>
	  if(answer[0] == 'n') exit(-1);
#endif

	//goto DONE;		// for quick testing

	//exit(-1); 		// for debugging

//*****************************************************


// Allocate empty buffer for output VFOLBM 
// was vfolbmp = alloc_read_bmp(idb_fp, Pixels, Lines, 0);

	printf("\n\t * Allocating memory for output VFOL bitmap ...\n");

	vfolbmp = (PixVal *) CPLMalloc(bmsize);			// allocate memory for the bitmap
	for (iii=0; iii<bmsize; iii++) {*(vfolbmp+iii) = 0;}	// make sure it is all zeroed


/* The VFOL bitmap starts with the non-forest bitmap as its base */

	printf("\tBurning NFMASK bitmap to output VFOL bitmap (as a base)\n");
	memcpy(vfolbmp, nfbmp, bmsize);


/* Prep VFOL bitmap  - add a safety border not to fall off the image*/

	printf("\tAdding safety border all around the VFOL bitmap\n");
	prep_bmp(vfolbmp, Pixels, Lines);	// set a boundary of zeros around the bitmap


// Test
//	count = 0;
//	for (ii=0; ii<bmsize*8; ii++) if (testbit(vfolbmp, ii)) count++;
//	printf("\nOriginal pixels set in input VFOL bitmap = %Ii \n\n", count);


	//goto FINISH;			// for test purposes

	//exit(-1); 		// for debugging

/*********************************************************/

/* 	Get ITCVFOL three optional thresholds */

/*********************************************************/


	printf("\n\t * Dealing with ITCVFOL three optional thresholds\n\n"); 

// To compensate for a bug as "thres_type" disappeared
	  
	//strncpy(thres_type,argv[4],10);		// bring argv[3] as thres_type
	//printf("thres_type = %s \n", thres_type);
	
	//exit(-1); // for debugging 


// PRESET mode - User has preset the thresholds as next items on command line 


if( EQUALN(thres_type,"PRE",3) ) 	
  {
	//printf("\n\t Got here (PRESET) ...\n\n");  exit(-1); // for debugging 
	
	
// Check list of threholds to use 
	
  printf("\nPRESET thresholds were entered on the command line. They are:\n");
  printf("    Image thresholds to use (as per user preset): %s \n", argv[5]);
 
  ii=0;
  strcpy(temp, argv[5]);
  p = strtok(temp, ",");

  while(p != NULL) 
	  {
 	  //printf("Token as a string: %s\n", p); 
	  input_thres[ii++] = strtol(p,NULL, 10);
	  //printf("%d Token as an integer: %d\n", ii-1, input_thres[ii-1]);	
	  p = strtok(NULL, ",");
	  }

  if (ii-1 >= 0) lower_thres = input_thres[0];
  if (ii-1 >= 1) upper_thres = input_thres[1];
  if (ii-1 >= 2) plusminus =  input_thres[2];
  if (ii-1 > 3) {printf("\n\n**ERROR**   One threshold too many \n\n"); exit(1);}

  printf("\nAs per user - Lower threshold: %d, upper threshold: %d, plusminus: %d\n",lower_thres, upper_thres, plusminus);

  goto MAIN;			// no need of histogram analysis, goto program core
  //goto DONE;			//for TESTING
  }


// For AUTO (automatic) mode (and as recommendations with manual mode)
// Get the thresholds based on image greylevel range, by getting an image histogram 

get_thres(nfbmp, nfmaskflag, Pixels, Lines); 	// calculate histogram on full image (- nfmask)


 if (nfmaskflag == 0)		/* Only makes sense on full image with no NFmask */
  {
  printf("\n\tHistogram-based automatic threshold recommendations:\n");
  printf("\t(Assumes that shaded (&water) pixels form a distinct population)\n");
  printf("\tLowerT = %d, UpperT = %d, Plusminus = %d\n",lower_thres, upper_thres, plusminus);
  }
 
 
/* 
	Thresholds recommandations based on histogram range.
	Automatic recommendations are conservative (playing it safe).
	Even more conservative when non-forest mask absent, because it is 
	assumed that the user is doing "quick and dirty" work and that
	water and various roads and open area are present.
*/

if( (data_type == CHN_8U) || (data_type == CHN_16U) )
  {
  if (nfmaskflag) 
    {
    lower_thres = first + (0.1 * (last - first));
    upper_thres = last - 0.1 * (last - first);
    }
  if (nfmaskflag == 0) 		// more conservative

    {
    lower_thres = first + (0.2 * (last - first));
    upper_thres = last - 0.2 * (last - first);
    }
  pminus = 0.005 * (last - first); 
  plusminus =  (int) (pminus+0.5);
  }
 
  printf("\n\tRange-based automatic threshold recommendations:\n");
  printf("\t(Removes 10-20%% of histogram range at both end)\n"); 
  printf("\tLowerT = %d, UpperT = %d, Plusminus = %d\n", lower_thres, upper_thres, plusminus);
	
//****************

/* In MANUAL mode, get thresholds from the user, but have suggestions ready (max. range). 
Here, recommendations are less conservative because the user can modify them and
probably will modify them, otherwise, the user would not have selected this mode.
However, it does give the range one should preferably not get out of (although 
it is still possible) (i.e., user can type anything, although some checking done).
*/

	//printf("\n\t Got here (before MANUAL)\n\n");  
	//exit(-1); // for debugging 
	
if( EQUALN(thres_type,"MAN",3) ) 	
  {
  lower_thres = first; 		// default is full range, but no more 
  upper_thres = last;
  fprintf(stdout,"\nMANUAL INPUT MODE [with recommendations]:\n");
  thres_manual();
  }

// Second guess Automatic or Manual lower threshold 

if (lower_thres - first > 0.40 * (last - first)) 
	{
	fprintf(stderr,"\n\nWARNING: lower threshold (%d) is > 40%% of useful intensity range",lower_thres);
	fprintf(stderr,"\nThis threshold selection may not be appropriate for this image.\n");
la1:	fprintf(stdout,"\n\tDo you wish to change these thresholds (y/n)? ");
	fgets(chr,256,stdin);
	if ( (chr[0] != 'y')&&(chr[0] != 'Y')&&(chr[0] != 'N')&&(chr[0] != 'n') ) goto la1;

	if (chr[0] == 'y' || chr[0] == 'Y') thres_manual();
	}


// Time to check memory usage with task manager
#ifdef DEBUG_ME
	  printf("\n Check memory after histo analysis. OK to continue(y/n): ");
	answer[0] = getc(stdin); 		// gets any answer or <CR>
	  if(answer[0] == 'n') exit(-1);
#endif
/*******************************************************************************/

// 	MAIN PROCESSING PART 		

/*******************************************************************************/

MAIN:


// 	Doing the MAIN WORK


	printf("\n\n\t\t MAIN WORK  ... \n");
	
	//exit(-1);  		// for debugging 

	/*printf("\n\n image,vfolbmp,Pixels,Lines,lower_thres,upper_thres,plusminus: %Ii %Ii %d %d %d %d %d\n\n",
						image_8b,vfolbmp,Pixels,Lines,lower_thres, upper_thres,plusminus); 
	*/

	if (data_type == CHN_8U)
		valley_fol(image_8b, vfolbmp, Pixels, Lines, lower_thres, upper_thres, plusminus);
	if (data_type == CHN_16U)
		valley_fol(image_16b, vfolbmp, Pixels, Lines, lower_thres, upper_thres, plusminus);


// Time to check memory usage with task manager
#ifdef DEBUG_ME
	  printf("\n After main work: OK to continue(y/n): ");
	answer[0] = getc(stdin); 		// gets any answer or <CR>
	  if(answer[0] == 'n') exit(-1);
#endif

/*************************************************************

	Create output VFOL bitmap (a 1bit tif)

******************************************************************/

OUTPUT:
FINISH:
end:

	printf("\n\t\t OUTPUT TO A FILE  ... \n");

	//exit(-1); 		// for debugging

// Create filename
// Presently, a fixed file name is used. Less parameters to put on command line
// The user can always change the name immediatly after the run if needed (or in a script)
	//file_out="xxxx_VFOL.tif";
	//extension="tif";
	
// ALSO, originaly assumed everything is done in the same directory (input and output files)
// which is OK with running from a "cmd window" and OK with our philosophy of a single dir as DB,
// but NOT OK with "ArcGIS" you needs to know precisely where to put the output file (crashes otherwise)

	
/*
	strcpy(fullfilename,argv[1]);			// main filename as base
	basefname = strtok(fullfilename,".");
	//basefname = strtok(basefname,"/");
	if(TIF_File) basefname = strtok(basefname,"_");
	//printf("basefname  :  %s \n", basefname);	
	file_out = strncat(basefname,"_VFOL",5); 
	//printf("file_out  :  %s \n", file_out); 			  	  	
 	strncat(file_out,".tif",4);
	//printf("file_out  :  %s \n", file_out); 
	
	//fprintf(stdout,"\n\t*Opening file '%s' in which to write results.\n", file_out);	
*/

if(!name_given)		// if no name given, create an output file name
  {
	
// SO, deal with PATH in front of file

	strcpy(fullfilename,argv[1]);			// main input filename (and possibly its dir)
//	printf("Full Filename:  %s \n", fullfilename);
//	printf("Full Filename Length:  %zd \n",  strlen(fullfilename));

	int basef_len;		
	for (i=0; i < strlen(fullfilename); i++)
	  {
	  j = strlen(fullfilename) - i;
	  //printf("Count back: %d",j);
	  if(fullfilename[j] == '_') {basef_len = j;	break;}		// find LAST underscore in full file name
	  }
//	printf("\nBase Filename Length:  %d \n", basef_len);
	
	strncpy(basefname, fullfilename, basef_len);
	basefname[basef_len] = '\0';   					/* null character manually added */
//	printf("Basefname ::  %s \n", basefname);
	
//	Concatenate base file name (path+file name beginning) with VFOL.tif

	strncpy(file_out, basefname, strlen(basefname));
	file_out[basef_len] = '\0';   					/* null character manually added */
	strncat(file_out,"_VFOL",5); 
 	strncat(file_out,".tif",4);	
//	printf("File_out  :  %s \n", file_out); 
	
//	exit(-1);		// for debugging
	
  }	
	
// If output filename was given, its already in file_out
	
// Open output file
	
	printf("\n\t*Opening and//or creating file for VFOL ouput bitmap as a 1bit tif (yet byte),\n\t as \"%s\" \n\n", file_out);

	poDriver = GetGDALDriverManager()->GetDriverByName("GTiff");

	if(poDriver == NULL) 
	   {
	   printf("\n ###Cant find proper driver for this file type %s \n\n", "GTiff"); 
	   exit( 1 );
	   }
	   //printf("\n ### For this file type \"%s\" proper driver was FOUND  \n\n", "GTiff"); 


// First, check if output file already exist (ask to overwrite)

/* 
	ima_out = (GDALDataset *) GDALOpen( file_out, GA_Update );

	if (ima_out != NULL) 
	  {
	  printf("\n\n ### Image %s already exist \n", file_out); 
	  printf("\n ### Can we overwrite the image file (Y/N) ?? \n\n"); ;
	  answer[0] = getc(stdin); 		// gets any answer or <CR>
	  if(( answer[0] == 'n') || (answer[0] == 'N') )exit(-1);	  
	  }
 */

// Create a tif file equivalent of a bitmap (NBITS=1), yet called byte type

  	papszOptions = CSLSetNameValue( papszOptions, "NBITS", "1" );
    //papszOptions = CSLSetNameValue( papszOptions, "COMPRESS", "PACKBITS" );

	ima_out = (GDALDataset *) poDriver->Create( file_out, Pixels, Lines, 1, GDT_Byte, papszOptions );

	if (ima_out == NULL) {printf("\n\n PROBLEM opening output image file %s \n\n",file_out); exit(1);}
	//printf("\n ***  NO PROBLEM *** opening output image file %s \n\n",file_out);


// Copy the metadata (GeoTransform, projection, ...)

//	fprintf(stdout,"\nWriting geographic info to file '%s' from original image.\n", file_out);	

	ima_out->SetGeoTransform(adfGeoTransform);

// 	printf( "Origin = (%.2f,%.2f)\n", adfGeoTransform[0], adfGeoTransform[3] );
//	printf( "Pixel Size = (%.2f,%.2f)\n\n", adfGeoTransform[1], adfGeoTransform[5] );

	
//	Writing projection data to file	

	//fprintf(stdout,"Writing projection data to file\n");
	
	ima_out->SetProjection(ima_in->GetProjectionRef() );
  		
// Access first and only band	

	poBand = ima_out->GetRasterBand( 1 );

// Test

	count = 0;
	for (ii=0; ii<bmsize*8; ii++) if (testbit(vfolbmp, ii)) count++;
	//printf("\n Pixels set in output VFOL bitmap = %Ii \n", count);

// All the following code is previous to the creation of  "itc_io_g",
// thus,	write_bitmap(bitmap_out, file_out) is not used

// Write output bitmap data out to a 1-bit tif file (*** but via an 8-bit buffer) in one shot

	if(by_image)
	{

	//fprintf(stdout,"\nWriting (in one shot) VFOLBM data to file %s  \n\n", file_out);

	bitmap_out = (PixVal *) CPLMalloc(sizeof(PixVal)*Pixels*(int64)Lines); 	 // allocate memory for a "Full 8bit image" to write data out

// Turn a bitmap in memory into a tif image (wrote via  8bit, yet nbits=1)

	printf("** Turning a bitmap in memory into a 1-bit tif image (wrote via 8bit, yet nbits=1) \n");

	for ( i = 1 ; i <= ysize ; i++ )		// For compatibility with PCI(x,y), I kept image coordinates start at (1,1)
	for ( j = 1 ; j <= xsize ; j++ ) 		// However, GDAL images start at zero (similar to bitmaps), so bytenum=bitnum
	  {
	  bitnum = (i-1)*(int64)Pixels + j-1;		
	  if (testbit(vfolbmp, bitnum)) bitmap_out[bitnum] = 1; else bitmap_out[bitnum] = 0;
	  //if( (i/100)*100 == i ) printf("%d lines done\r", i);
	  }

// Write image (here, a bitmap) in ONE SHOT

	printf("\n\tWriting out image (bitmap) to file in one shot\n");

	poBand->RasterIO(GF_Write, 0, 0, Pixels, Lines, bitmap_out, Pixels, Lines, GDT_Byte,0, 0 );

// Test

	count = 0;
	for (ii=0; ii<Pixels*Lines; ii++) if (bitmap_out[ii] == 1) count++;
	//printf("\n Pixels set in output 8bit bitmap (after out by image) = %Ii \n", count);

	}		// end of "if(by_image)"


// Write output bitmap data out to a 1-bit tif file (*** but via an 8-bit buffer) one line at the time 

	count = 0;

	if(by_lines)
	{
	pafScanline = (PixVal *) CPLMalloc(sizeof(PixVal)*Pixels);	// create an 8-bit line buffer

	fprintf(stdout,"\nWriting output bitmap data \"line by line\" via an 8 bit buffer ....\n");


	for ( i = 1 ; i <= (ysize) ; i++ )		// For compatibility with PCI(x,y), I kept image coordinates start at (1,1)
	 {
	 for ( j = 1 ; j <= (xsize) ; j++ ) 		// prep a line of image
	  {
	  bitnum = (i-1)*(int64)Pixels + j-1 ;			// bitnum starts at zero, so does image, so bytenum=bitnum
	  pafScanline[j-1] = 0;
	  if (testbit(vfolbmp, bitnum)) { pafScanline[j-1] = 1; count++; }
	  }
	  poBand->RasterIO(GF_Write, 0, i-1, Pixels, 1, pafScanline, Pixels, 1, GDT_Byte, 1, 1);	// write a line
 	  if( (i/100)*100 == i ) printf("%d lines done\r", i);
	 }
	printf("\n Pixels set in output 8bit bitmap (after out by lines) = %Ii \n", count);
	}		// end of if(by_lines)
 

// Write description to output file

	sprintf(description,"ITCVFOL - Valleys of shade from %s with (%d,%d,%d)", 
				shortfilename,lower_thres, upper_thres, plusminus);
	
	printf( "\nDescription within output file will be : %s\n", description);

	poBand->SetDescription(description);


// Prep an OUTPUT color table 

	//poBand->SetColorInterpretation(GDALColorInterp::GCI_PaletteIndex);
		
	GDALColorTable * col_tab_out = nullptr;		// declare output colour table pointer
	col_tab_out =  &GDALColorTable();			// construct output colour table	
	//col_tab_out =  &GDALColorTable(GPI_RGB);			// construct output colour table
	
// Color entries
	
    GDALColorEntry * col_ent_out = nullptr;		// declare
	col_ent_out = &GDALColorEntry();			// construct (i.e., reserve memory)
	
	col_ent_out->c1 = 0; col_ent_out->c2 = 0; col_ent_out->c3 = 0; col_ent_out->c4 = 255;
	col_tab_out->SetColorEntry(0, col_ent_out);
	//col_tab_out->SetColorEntry(1, col_ent_out);		// for TESTING
	
	col_ent_out->c1 = 255; col_ent_out->c2 = 255; col_ent_out->c3 = 255; col_ent_out->c4 = 255;	
	col_tab_out->SetColorEntry(1, col_ent_out);


// Set "nodata values" for software that use that
	
	poBand->SetNoDataValue(0);
		
// Write Color Table out to bitmap(tif)  file
			
	poBand->SetColorTable(col_tab_out);	
		




// Time to check memory usage with the task manager
#ifdef DEBUG_ME
	  printf("\n ##### Check memory used just before finishing. OK to continue(y/n): ");
	  answer[0] = getc(stdin); 		// gets any answer or <CR>
	  if(answer[0] == 'n') exit(-1);
#endif

// Close input and output images

DONE:	printf("\n\t*Closing all image files and exiting program. \n");

	//GDALClose(ima_in);
	//GDALClose(nf_bmp);	// NOTE: closing it a 2nd time just kill the program with no output at all
	GDALClose(ima_out);


time (&rawtime);
timeinfo = localtime (&rawtime);
fprintf(stdout,"\n\n_______________________________\n");
fprintf(stdout,"\n %s (%s) finished at %s\n\n", PROG_NAME, VERSION,  asctime(timeinfo));



// Check if running from ArcGIS (to delay window disapperance for user to have time to read it)


// For people using this program via ArcGIS, give then some time to examine the results (before disappearing)

if ((strncmp("ArcGIS ",argv[argc-1],3) == 0) )		// if last argument is ArcGIS or ArcMap
	{
	fprintf(stdout,"\n\n######\n");
	printf("\n Type anything to make this detailed window disappear and terminate %s ",PROG_NAME);
	answer[0] = getc(stdin); 		// gets any answer or <CR>
    }
	


exit(0);			// exit properly 

} 		// end of MAIN PROGRAM





/*******************************************************************************/

/*		FUNCTIONS			*/

/*******************************************************************************/



/* Generates an histogram of the image (without non-forested area, if masked) 
   and calculates automatic thresholds
   If judged not appropriate, user entries are requested.
*/

void get_thres( PixVal *nfbmp, int nfmaskflag, int pixels, int lines)
{
#define ARRSIZE USHRT_MAX
 
	int	i, j, min_count, m_count, count_right, count_left, mode;
	int	found = FALSE;
	int	prev, curr, next, hsize;
	int	histo[ARRSIZE];
	int	first_der[ARRSIZE];
	int	r_side, min_r_side;
	void	*temp_ima;
	FILE 	*histo_fp;
	char	histo_fname[65];
	float	pminus;
	int64	bitnum;

	
// pointer to structure to store info extracted from histogram by ana_hist()
	ph = (hist_inf *) malloc(sizeof(hist_inf)); 
		
	
	if (data_type == CHN_8U) hsize = 256;
	if (data_type == CHN_16U) hsize = USHRT_MAX;

	for (i = 0; i < hsize; i++)
		histo[i] = first_der[i] = 0;

	fprintf(stdout, "\nCalculating histogram-based parameters using %d greylevels \n", hsize);

//	### Now image is already read and in memory (and global) so forget all that
//	PCI version use to open image later (cause could be by sections), thus had to read image here

/*
// Read full illunination image

	//printf("\nFor histogram generation - Reading main ILLUMINATION image from %s ... \n", illumin_fname);

	if(by_image)
	{
	temp_ima = (PixVal *) CPLMalloc(sizeof(PixVal) * Pixels * (int64)Lines);	// get memory for full image

	//printf("Raster number=%d and Type = %s \n\n", piiBand->GetRasterDataType(), GDALGetDataTypeName(piiBand->GetRasterDataType()) );

	piiBand->RasterIO(GF_Read, 0, 0, Pixels, Lines, temp_ima, Pixels, Lines, GDT_Byte, 0, 0 );

 	//printf("\n\nGot ILLUMIN image in temp_ima for histogram analysis \n\n");

// Generate histogram 

	printf("Generating histogram of image \n\n");

//	With NFmask just pickup data from unmasked (not masked) image

	  //get_pix_val = get_u8;

	  gen_hist_not_mask((PixVal *)temp_ima, get_pix_val, nfbmp, pixels*(int64)lines, histo);
	
	}		// end of if(by_image)


// Do it line by line to diminish memory needs


	if(by_lines)
	{

	printf("\tReading ILLUMIN (line by line) and generating histogram of unmasked part of image \n\n");

	pafScanline = (PixVal *) CPLMalloc(sizeof(PixVal)*Pixels);	// create an 8-bit line buffer

	for (i = 1; i <= Lines; i++)		// using  PCI notation image starting at (1,1)
	  {
	  piiBand->RasterIO(GF_Read, 0, i-1, Pixels, 1, pafScanline, Pixels, 1, GDT_Byte,0, 0 );


	  for ( j = 1 ; j <= Pixels ; j++ )
	    {
		bitnum = (i-1)*(int64)Pixels + j-1;
		if (!testbit(nfbmp, bitnum)) histo[pafScanline[j-1]]++;
	    }

 	  if( (i/100)*100 == i ) printf("%d lines done\r", i);

	  }
	printf("\n");


	}		// end of if(by_lines)

*/



//	With a NFmask, just pickup data from unmasked (not masked) image

	  //get_pix_val = get_u8;
	if ( data_type==CHN_8U)
	  	gen_hist_not_mask((PixVal *)image_8b, get_pix_val, nfbmp, pixels*(int64)lines, histo);

	  //get_pix_val = get_u16;
	if ( data_type==CHN_16U)
		gen_hist_not_mask((uint16 *)image_16b, get_pix_val, nfbmp, pixels*(int64)lines, histo);
	
// Analyse histogram just gathered 
	
	//ana_hist(histo, hsize, &first, &last, &m_count, &mode); 	// OLD ana_hist() cal
	
	init_histo_struct(ph);

	ana_hist(histo, hsize, ph);		// new ana_hist, info passed via structure
	first=ph->first; last=ph->last;  m_count=ph->m_count; mode=ph->mode;

/* Remove non-significant quantities in some bins */	
	
	min_count = m_count / 100 ; 	/* 1% of max count */

 	/* output the grey-level histogram to a file */

	  sprintf(histo_fname,"Histo_CH%02d.hist" ,illumch);
	  histo_fp = fopen(histo_fname,"w");
	  for (i=0; i<last; i++) fprintf(histo_fp," %4d %4d \n", i, histo[i]);
	  fclose(histo_fp);

	/* Report */
	
	fprintf(stdout,"\n\tIllumination channel histogram significant bin range: \n");
	fprintf(stdout,"\tFirst, last, max_count, min_count: %d %d %d %d \n",
						first, last, m_count, min_count);

	/* Calculate the first derivative sign */

	for (i = first; i < last; i++)
		first_der[i] = sign(histo[i + 1] - histo[i]);

	/* Smooth the first derivative signs */

	prev = first_der[first-1];
	curr = first_der[first];

	for (i = first; i < last; i++) 
	  {
	  next = first_der[i + 1];
	  if (curr != prev && prev == next) first_der[i] = prev; 	/* remove one-bin oddity */
	  prev = curr;
	  curr = next;
	  }

/* 	Find lower threshold 
	First *significant* sign reversal (pos. to neg.) on first derivative
*/

	r_side = 9; min_r_side = 6;
/*if (data_type == CHN_8U)  r_side = 6; min_r_side = 4;		 for 8-bit data, 4 out of 6 */
/*if (data_type == CHN_16U) r_side = 12; min_r_side = 8;	 for 16-bit data, 8 out of 12 */

	lower_thres = first;
	for (i = first+r_side; i <= last-r_side; i++)
	  {
	  if( (first_der[i-1]>0) && (first_der[i+1]<0) )
	    {
	    count_left = count_right = 0;
	    for (j = 1; j <= r_side; j++) if(first_der[i-j]>0) count_left++;
	    for (j = 1; j <= r_side; j++)if(first_der[i+j]<0) count_right++;
	    if( (count_left >= min_r_side) && (count_right >= min_r_side) )
		{
		lower_thres = i+1;
		goto s1;
		}
	    }
	  }

s1:	fprintf(stdout,"\tHistogram first inflection point: %d \n", lower_thres); 


	/* around that inflection point, miror distribution on the left to the right 
	   to get separation position (assumes that shade pixel are a Gaussian curve) */

	lower_thres += (lower_thres - first);	

	/* upper_thres assumed at upper 10% of range */

	upper_thres = last - 0.10 * (last - first); // minus 10% of range

  	pminus = 0.005 * (last - first); 
  	plusminus =  (int) (pminus+0.5);

	//free(temp_ima);

}		/* end of get_thres() */

/*************************************************/

/* Put a safety border (set bit) around a bitmap in order not to fall off the image (section) */
/* Here, the global variable "bmoffset" (a line offset) is used to work on image sections */
/* xsize and ysize are image (or section) sizes in pixels and lines */

void prep_bmp(PixVal *bmp, int xsize, int ysize)
{
  int     i, j;

/* printf( "\nPreparing bitmap safety border ...\n"); */

/* upper border */

  for (i = 0; i < BORDER; i++)
  for (j = 0; j < xsize; j++) 
	setbit(bmp, (bmoffset+i) * (int64)xsize + j);

  //fprintf(stdout,"\n Upper border done at line: %d \n", bmoffset);

/* lower border */

  for (i = ysize - BORDER; i < ysize; i++)
  for (j = 0; j < xsize; j++) 
	setbit(bmp, (bmoffset+i) * (int64)xsize + j);

  //printf("\n Lower border done at last line: %d at last position %I64d Pixels \n", bmoffset+ysize,(bmoffset+ysize)*(int64)xsize); 

  for (i = 0; i < ysize; i++) 
  { 
	  /* left side */
  for (j = 0; j < BORDER; j++)
	setbit(bmp, (bmoffset+i) * (int64)xsize + j);

	/* right side */
  for (j = xsize - BORDER; j < xsize; j++)
	setbit(bmp, (bmoffset+i) * (int64)xsize + j);

  }

}


/*************************************************/
/*
	Get user thresholds manually
	This code can deal with getting just a <CR> and 
	using recommended (previously set) thresholds
*/

void thres_manual()
{
	char chr[256];
	//fgets(chr,256,stdin);		//empty buffer

	fprintf(stdout,"\nEnter lower threshold value [%d]: ", lower_thres);
	if(fgets(chr,256,stdin))  
		if(chr[0]) sscanf(chr,"%d",&lower_thres);

	fprintf(stdout,"\nEnter upper threshold value [%d]: ", upper_thres);
	if(fgets(chr,256,stdin)) 
		if(chr[0]) sscanf(chr,"%d",&upper_thres);
	if ( (data_type == CHN_8U) && ( upper_thres > 256) ) upper_thres = 255;
	
	fprintf(stdout,"\nEnter plusminus threshold value [%d]: ", plusminus);
	if(fgets(chr,256,stdin))
		if(chr[0]) sscanf(chr,"%d", &plusminus);
	
}

/*************************************************/

void convert_bitnum(int64 bitnum, int64 *byte, int32 *bit)
{
	*byte = bitnum / 8;
	*bit = 7 - (bitnum % 8);
}

/*************************************************/

/* check return value from MALLOC to make sure it is OK */

void check_mem(void *memory_ptr)
{
	if (memory_ptr == NULL )
	{
	fprintf(stderr,"\n ITC program - MEMORY ALLOCATION ERROR. \n");
	exit(-1);
	}
}

/**************************************************************/

// functions to read 8bit image data (now, with int64 position) 
 

int32 get_u8(void * image_8b, int64 pos)
  {
  return *((PixVal *)image_8b + pos);
  }

/*************************************************/
/*******************************************************/

int32 get_u16(void * image_16b, int64 pos)
 {
  return *((uint16 *)image_16b + pos);
  }

/*************************************************/
